### ISSUE TITLE
Item checks for Mechanic Mado Gear skills allows skills to be done even if the items only in the inventory and unequipped

### ISSUE THREAD

**Issue by jezznar** [rathena/rathena#1034]
Git Hash: b98ba7a
Client: 20141022
No Modifications
Info Links:
http://www.divine-pride.net/database/skill/2263/nc-hovering
http://www.divine-pride.net/database/skill/2273/nc-neutralbarrier
http://www.divine-pride.net/database/skill/2267/nc-selfdestruction
http://www.divine-pride.net/database/skill/2269/nc-emergencycool
http://www.divine-pride.net/database/skill/2274/nc-stealthfield

screenshots:
http://prntscr.com/acxthp
http://prntscr.com/acxtr1
http://prntscr.com/acxtxq
http://prntscr.com/acxu1m
http://prntscr.com/acxu6g

**Comment by Darkelfen** [comment]
I think that is the intended behavior since:

> The following equipment reliant MADO gear skills have been changed **so that you no longer require to have the item equipped**, but simply need to have it in your inventory.
- Flame Launcher - Flame Thrower
- Acceleration - Acceleration Device
- Self Destruction - Self Destruct Device
- Shape Shift - Shape Shift
- Emergency Cool - Cooling Device
- Magnetic Field - Magnetic Field Generator
- Neutral Barrier - Barrier Generator
- Stealth Field - Optical Camouflage Generator
-  Repair - Repair Kit

kRo Maintenance 09/02/2009

source: http://forums.irowiki.org/showthread.php?t=32980

**Comment by jezznar** [comment]
I see. with this I also proposed a pull request on the RO translation Project by zackdreaver https://github.com/zackdreaver/ROenglishRE/pull/3

**Comment by aleos89** [comment]
As @Darkelfen stated, this is intended behavior.
