### ISSUE TITLE
RK's Rune Items

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#1045]
All jobs should can consume them, just if player is not RK, gives no effect.
Currently, our `pc_isUseitem` prevents those items can be consumed.

**Comment by Paoly28** [comment]
also rAthena rune stones are considered delayed consumables, this is very important as it disallows chaining with skills since it cannot bypass animation this gives the caster around 1~2 second of delay , when it's supposed to be easily chained in succession with other skills provided the item itself isn't on CD.
