### ISSUE TITLE
How the client get to know map server ip and char server ip?

### ISSUE THREAD

**Issue by cnrat** [rathena/rathena#1057]
I got an issue while forwarding server ports.
For some network reason I have to forward as following:
WAN1:6900 -> WAN2:36900
WAN1:5121 -> WAN2:35121
WAN1:6121 -> WAN2:36121
I changed clientinfo.xml in client side set 'address' to WAN2 and 'port' to 36900.
The login server works normally. From log I can see WAN2 as client ip address.
But the map server dose not. What I saw was client connecting to map server directly with its own ip.

I though it might be the login server send map server's ip and port to client side. Any one can help?

**Comment by lighta** [comment]
The loginserv, send the charservip to the client here :
WFIFOL(fd,47+n*32) = htonl((subnet_char_ip) ? subnet_char_ip : ch_server[i].ip); (loginclif.c )
And the charserv send the mapservip here:
WFIFOL(fd,22) = htonl((subnet_map_ip) ? subnet_map_ip : map_server[i].ip); (char_clif.c)

You can put a breakpoint there and debug it but I don't really see what's wrong.
I mean from your description I suppose that you have set mapserv_ip equal to WAN2 instead of WAN1.
NB : That ip is set everytime a mapserv connect himself to a charserv:
map_server[i].ip = ntohl(RFIFOL(fd,54)); (char_clif::chclif_parse_maplogin)

**Comment by jezznar** [comment]
can you please post your map_server.conf?

**Comment by cnrat** [comment]
@lighta so this is why client connected to map server directly, because the ip address send to client is read from conf files. Thank you.

It looks I have to find another workaround.

**Comment by lighta** [comment]
Idk, well if you make your mapserv connect to your charserv using the WAN1-port1pair all should be good I suppose.
Also speaking of wich, I would have change the char_lan_subnetcheck
from :
ARR_FIND( 0, subnet_count, i, (subnet[i].char_ip & subnet[i].mask) == (ip & subnet[i].mask) );
to
ARR_FIND( 0, subnet_count, i, (subnet[i].map_ip & subnet[i].mask) == (ip & subnet[i].mask) );
Just cause that thing is always confusing, like that the rules would be simplier.
if ((client_ip & subnet) == (lan_dest_serv_ip & subnet))
 return  lan_dest_serv_ip;
else return  wan_dest_serv_ip;

**Comment by anacondaqq** [comment]
oh, as i understand, you trying to make proxy servers for your game-server?
if yes, there are no problems at rathena side to re-route packets to required direction. 
All what you should to do it's diff your exe for dns / proxy support. And the rest, will do your game server & game client.

**Comment by cnrat** [comment]
@anacondaqq It more like a reverse proxy. Anyway, I have made that work as last.
The key is set rathena to use the same port as forwarding.
This issue should be closed.
