### ISSUE TITLE
getunittype doesn't seems to get the GID

### ISSUE THREAD

**Issue by Tearbytes** [rathena/rathena#1058]
Hash: c6ed8a4f92a143eca9ddc1c2161f88c1db9f70f4
No source edits

I'm having this warning on getunittype. It seems that it doesn't return the GID of the killer.
```
[Warning]: buildin_getunittype: Error in finding object with given game ID 0!
[Debug]: Source (NPC): testonpckillevent at prontera (158,174)
```

script:
```
prontera,158,174,5	script	testonpckillevent	52,{
OnNPCKillEvent:
	if( getunittype(killerrid) == 0 ) {
		announce "triggered integer",bc_all;
		end;
	}

	if( getunittype(killerrid) == UNITTYPE_PC ) {
		announce "triggered strings",bc_all;
		end;
	}
end;
}
```

OT: 
Can anyone also tell me how do I filter monsters killed by @ killmonster? Shoud I use **_(getunittype(killerid) == UNITTYPE_NPC)_** ? Thanks!

**Comment by Darkelfen** [comment]
Working fine for me, though I'm not at last hash.
hash: https://github.com/rathena/rathena/commit/b70b25945e697b3b5e6e637ac096430490ee17c5

Tested on the following script:
```
prontera,1,1,0  script  testonpckillevent   -1,{
OnNPCKillEvent:
    if( getunittype(killerrid) == 0 ) dispbottom rid2name(killerrid)+": triggered integer";
    if( getunittype(killerrid) == UNITTYPE_PC ) dispbottom rid2name(killerrid)+": triggered strings";
   end;
}
```
Result after killing a Poring:
![screenglacierro219](https://cloud.githubusercontent.com/assets/7315177/13810948/f48e2c1c-eb48-11e5-989c-eb02e19ae721.jpg)

**Comment by Tearbytes** [comment]
I got the error when killing the mob. And I didn't try to click the npc though.

**Comment by julia40124009** [comment]
killerrid is OnPCDieEvent variable

**Comment by aleos89** [comment]
As @julia40124009 stated, `killerrid` is used for `OnPCDieEvent` while `killedrid` is used for `OnNPCKillEvent` or `OnPCKillEvent`.

So when you use `OnNPCKillEvent` or `OnPCKillEvent`, the player is already attached to the NPC with the accompanying `killedrid` (the target that died).

Towards your question, please create a topic on the forum in the script support section, please!

**Comment by Tearbytes** [comment]
Hmmm. @aleos89 why did it worked on @Darkelfen ? On which revision did it got modified?

**Comment by julia40124009** [comment]
I want to know how to trigger script on @Darkelfen script ?
npc view id = -1 , x = 1 , y = 1 , no event  .........

**Comment by Darkelfen** [comment]
Sorry, I forgot to copy it fully, it's triggered on "OnNPCKillEvent" label.
BTW, I'm at b70b259, not latest hash but working.

**Comment by julia40124009** [comment]
I test scrtipt , note event and variable and dispbottom message
(kill monster) OnNPCKillEvent is use 'killedrid' get mob id (not gid)

<a href="http://imgur.com/k7aeYVw"><img src="http://i.imgur.com/k7aeYVw.png" title="source: imgur.com" /></a>

(kill player) and use OnPCDieEvent + killerrid get player gid (aid)

<a href="http://imgur.com/82YMnEn"><img src="http://i.imgur.com/82YMnEn.png" title="source: imgur.com" /></a>

**Comment by Darkelfen** [comment]
That's why you use rid2name(killerrid) for players and strmobinfo (1,killerrid) for mobs.

The only way to assign a GID to a mob is by summoning it via monster command
.MobGid=monster(... etc ...) ...
if that's the case in theory rid2name "might work" on mobs (not 100% sure though, must test it). 

Even though, most of times just fetching the mob ID is sufficient. Furthermore a myriad of mobs are spawn in RO, assigning each one of them a GID is a waste.

Also, I should use OnPCKillEvent rather than OnPCDieEvent, for events in which a player kills another player (most PvP scripts).

**Comment by julia40124009** [comment]
rid2name use
player -> aid
mob -> (gid) not mob id 

get mob gid must be use monster or bg_monster script command

**Comment by Darkelfen** [comment]
I know how I should use rid2name, thanks. I've just stated "id", because amongst these labels it could be either killerrid or killedrid, so I thought "id" should be self-explanatory enough. 

Regarding the issue itself, most mobs spawned in ro doesn't have a GID, just their mob ID, unless they are spawned through script commands as monster, as both of us stated.

If a mob was the killer(killerrid), in that case getunittype(killerrid), shouldn't work properly. But it isn't a bug, since mobs usually don't have a GID, just their mob ids.

**Comment by Tearbytes** [comment]
I'm going to try the hash: b70b25945e697b3b5e6e637ac096430490ee17c5
These scripts of mine are working before. Just got the error when I updated to the latest.
i'll look into it later.

**Comment by Darkelfen** [comment]
Same here when I got into latest.

**Comment by Tearbytes** [comment]
@Darkelfen did you make it work again?

@aleos89 I was a bit confused here. When using `OnNPCKillEvent` or `OnPCKillEvent` the killer is already attached to the npc?

So should we use `OnNPCKillEvent: if(getunittype(getcharid(0)) == 0)` to check if the mob's killer is a player? 

Now, how do we check if a mob's killer is a pet or if the killer is also a mob?

I think it's better when we can use killedrid and killerrid on those event labels. since it's already functioning that way before. I can't seem to find on which commit did this script got changed.

**Comment by julia40124009** [comment]
I don't know what to say
player GID please use getcharid(3)
You had better read script_commands.txt

**Comment by Tearbytes** [comment]
@julia40124009  Yeah. Sorry, I thought it needs char id. 
Now, how do we check if a mob's killer is a pet or if the killer is also a mob?
