### ISSUE TITLE
Deep Sleep Success Chance

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1063]
The chance seems to be 100% independent on which skill lvl you use nor which base/job level you have.

I even tried to modify the source code a little bit, but it still sticked with 100%
If i'm correct then the max possible chance should be 63.6% with max lvl 175/60

However, something seems to be wrong here.

**Comment by Playtester** [comment]
There are multiple things wrong with it right now. 

How it works on official servers:

1. Deep Sleep itself can be avoided, but it does not have any status resistance itself. So if base chance is 40%, it works exactly 40% of the time.
Different in rAthena: We apply resistance in the status code.

2. Deep Sleep has a duration reduction formula:
Duration (in ms) = BaseDuration - 25*tarBaseINT - 50*tarBaseLevel
Different in rAthena: Each base INT reduces duration by 50ms instead of 25ms (but there's a comment about kRO balance update so maybe our sources are outdated on that?)

3. All base chances are defined by the skills, so it can be different from skill to skill.
For WM_LULLABY_DEEPSLEEP we have this:
```skill_area_temp[5] = (4 * skill_lv * 1000) + ((sd) ? pc_checkskill(sd,WM_LESSON) : skill_get_max(WM_LESSON)) * 2000 + (status_get_lv(src) * 1000 / 15) + (sd ? sd->status.job_level * 200 : 0);```
It's actually 10 times higher than it should be!
I check SO_ARRULLO and it's 10 times higher there too.

4. Base duration reduction should be handled by the status code NOT by the skill code, but we have this:
```int duration = skill_area_temp[6] - (status_get_lv(bl) * 50 + (sd ? sd->status.int_ : status_get_base_status(bl)->int_) * 50);```
As you can see the resistance is actually applied here, so it actually currently applies the resistances twice! Reducing the duration double as fast as it should be.

Summary:
* Deep Sleep base chances are 10 times higher than they should be for both Lullaby and Arrullo.
* Deep Sleep needs its resist code removed.
* Skills should not apply any duration reduction as it's handled by Deep Sleep resist code.

**Comment by Playtester** [comment]
Actually I tested durations on official servers now and the result was:
```Lullaby = 12000:14000:16000:18000:20000 - 75*BaseINT - 100*BaseLevel
Arrullo = 8000:10000:12000:14000:16000 - 25*BaseINT - 50*BaseLevel```

Seems like Lullaby really has a duplicate duration resistance! But Arrullo uses the normal status change reduction.

Chance for Lullaby Level 5 seems to be a bit above 50% on level 150/50.
Chance for Lullaby Level 1 seemed a bit below 50% on level 150/50.

So I guess the formula from Gravity is accurate, we just it 10 times too high.
Same for Arrullo. As listed by Gravity, 10 times too high on rAthena.

@aleos89 is working on it.

**Comment by RagnarokNova** [comment]
I'll get some info on whether anything changed in the 175 update or not in relation to the skill, too.

**Comment by aleos89** [comment]
Character with level 175 yielded the same results as above.
