### ISSUE TITLE
Bioethics complete quest checks

### ISSUE THREAD

**Issue by AtlantisRO** [rathena/rathena#1072]
[Biochemist#Valkyrie] NPC is using variable MISC_QUEST & 64 to check if Bioethics Skill Quest is finished, but in script this quest finishes at bioeth == 13, making that newer creators can't pass the check to learn again Bioethics skill.

The MISC_QUEST|64 was the old variable that ends the quest, but it was dropped in commit 521950d and it has not been used anymore in scripts, but still mentioned in doc\quest_variables.txt.

What about adding to NPC [Biochemist#Valkyrie] a check to evaluate if player has one of both variables:

(Class == Job_Creator && (MISC_QUEST & 64 || bioeth == 13) && getskilllv("AM_BIOETHICS") == 0)

Also, it needs to merge both variables in only one, to mark completed Bioethics quest with old players that have MISC_QUEST & 64 var and prevent them to repeat the quest when it has been finished.

**Comment by Lemongrass3110** [comment]
Actually this issue is not only for the Bioethics quest but for some others too.

I could only find setting the variable for:
- 4 on https://github.com/rathena/rathena/blob/1b303d32ab0fd9f89e4a3a80585e295bfd650ba6/npc/quests/counteragent_mixture.txt#L541
- 8 https://github.com/rathena/rathena/blob/1b303d32ab0fd9f89e4a3a80585e295bfd650ba6/npc/quests/quests_prontera.txt#L52
- 512 on https://github.com/rathena/rathena/blob/56a744014b7d271d9480f9ed5e84ba3b9a7bfadb/npc/quests/quests_lighthalzen.txt#L1531
- 1024 on https://github.com/rathena/rathena/blob/1b303d32ab0fd9f89e4a3a80585e295bfd650ba6/npc/jobs/valkyrie.txt#L153
- 2048 on https://github.com/rathena/rathena/blob/1b303d32ab0fd9f89e4a3a80585e295bfd650ba6/npc/quests/ninja_quests.txt#L188

Note that I've only  looked for them by using:
https://github.com/rathena/rathena/search?p=1&q=MISC_QUEST&utf8=%E2%9C%93

Maybe @Atemo can have a look at this?

We could update the scripts and release some sql updates for setting the newer variable with it.

**Comment by Atemo** [comment]
The others MISC_QUEST are 'fine'. It seems we have an update of lhz cube and rachel sanctuary quest through. I'm on it
