### ISSUE TITLE
Repair - Mechanic

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1076]
The skill **Repair** from Mechanic does not check for item id 2807 to be equipped nor does it check for the item to be inside your inventory.

At the current state it completly ignores to check for the Repair Kit and still heals you.

Maybe it has something to do with the Source Code note in **skill.c** ?!:
>//NOTE: Please make sure Magic_Gear_Fuel in the last position in skill_require_db.txt

**Comment by Darkelfen** [comment]
Check list in Issue #1034, in kRo Maintenance 09/02/2009 Repair doesn't need Repair Kit to be equipped.

**Comment by stealth62** [comment]
:+1:

**Comment by Everade** [comment]
Then you need to have it at least in your inventory
But if you would actually try finishing reading my first sentence:

> ** nor does it check for the item to be inside your inventory**
.
Which means you can cast the skill without having the Repair Kit AT ALL.

**Comment by Darkelfen** [comment]
True, haven't noticed that, sorry. So I've done some tests on the skill.
This is NC_REPAIR in skill_require_db at db/re/
at git hash: daa9e01
```
2275,0,0,25:30:35:40:45,0,0,0,99,0,0,mado,0,0,12392,1,12392,1,12393,1,12393,1,12394,1,2807,0,0,0,0,0,0,0,6146,1,0			//NC_REPAIR
```
First, is asking for 2 units of each lesser repair in order to be cast; 2x Repairs A (12392) & 2x Repairs B (12393), but when casted, checks only for Repair C (12394).
Even if you have either repair A or B on inventory, the skill miss.
Also, as you stated, the repair kit (2807) requirement is being disregarded albeit it is stated.

**Comment by aleos89** [comment]
Confirmed on officials. Also Magic Gear Fuel is not an item requirement anymore.

**Comment by Everade** [comment]
Shouldn't Repair A and B items be consumed if your skill level is lower than 5 ?
But on my test server, i'm actually not able to decrease the skill level of Repair, nor of Pile Punker.
Is that client side issue or also rathena ?

**Comment by Darkelfen** [comment]
Yes, my fault, sorry. I was able to decrease the level by scrolling as usual, and as you stated that is working as intended.
