### ISSUE TITLE
LG_EXEEDBREAK Attack emperium Abnormal injury!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1169]
Emperium attack should be 1 mandatory damage but LG_EXEEDBREAK the damage may exceed!

**Comment by Darkelfen** [comment]
Confirmed, exceedbreak deals additional damage to emperium.

**Comment by aleos89** [comment]
The reason is because we calculate damage (here is where plant type is checked), then we return it to weapon attack, then we increase the damage if the player has Exceed Break. Seems like there are a few other skills that bypass this as well.

**Comment by Paoly28** [comment]
GG Rune and crush strike

**Comment by Playtester** [comment]
Yeah the order of processing the "div" is strange. The same also applies for assumptio. If the damage is 1 and it the skill does 5 hits, the damage should become 5 (5 hits that do 1 damage each), but if you have assumptio on, the damage suddenly becomes 2 and shows 5 times "MISS". It's kinda confusing because it shows miss but still cancels the cast.

But I think there was a reason why I couldn't move the div fix further down... I wonder what that was.
