### ISSUE TITLE
65355 visual damage to emperium with no stats during woe.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1180]
![](http://i.imgur.com/4mMCWZs.gif)

Problem: 65355 visual damage to emperium from 1 stats at WoE castle with enabled WoE.

How reproduce:
1. @ guild adfdsfdsf
2. @ glvl 50
3. @ level all guild skills
4. @ agitstart2 
5. go to castle and try to hit emperium, all of your stats must be 1
(i'm gm with gm sprite) gm level 99

Mode: pre-re
client date: 2012-04-10
packet_obf: off
hash: 88d2dde63222ef0c480a5341315f7f2ed044f6a5

**Comment by Lemongrass3110** [comment]
Sorry to tell you, but I just tried this.
If I try to hit an EMP with alstats 1 I do miss about 99% of the time. Since you hit all the time you must have at least something giving you bonus DEX.

Could you please give us infos on:

- your job
- your baselevel
- your joblevel
- a screenshot of your equip and status window

Thank you.

**Comment by anacondaqq** [comment]
Hello, after upgrading to the latest hash, i don't have this issue anymore.
