### ISSUE TITLE
Server Freeze

### ISSUE THREAD

**Issue by croxinuz** [rathena/rathena#1188]
hi , i got some problem using Lastest GIT version of Rathena.
if player login more than 1015 my server got stuck / Freeze.
it's bug or normally ?

**Comment by anacondaqq** [comment]
bug, related to some of the limitations. Maybe sockets, maybe at the same time opened files.
Depends on hosting platform. If you host your game-server with OVH -> that's maximum opened files limit (for socket connections). Limited as i know to 1024 (custom changes with OVH kernel).

Can you please before fixing that, provide me a full log of crash? Because guys from Dawn of Midgard forgot to do that, they were asking for help, and don't show how they solve the issues without helping to community.

Try compile your server with gdb

apt-get install gdb && chmod +x configure && ./configure --enable-debug=gdb && make server.

Then, run each server separate, and map server in debug mode by command:

gdb map-server
then click r (to reload map-server).
If you will get stuck again, please provide complete output here. This is important to see, maybe devs can somehow implement much better fix (if it's rathena related bug). But i guess, it's server-related bug with limitations in linux kernel..

**Comment by croxinuz** [comment]
i got this error when player 1018 :
[Error]: connect_client: accept failed (error 24: Too many open files)!
[Error]: connect_client: accept failed (error 24: Too many open files)!
[Error]: connect_client: accept failed (error 24: Too many open files)!

**Comment by Playtester** [comment]
The number of sockets you can have is limited to 1024. There are many things that limit it, like some constants in rAthena (search for 1024 or the error message you get to find them). It also might require you to modify the settings on the OS you are running the server on.

**Comment by croxinuz** [comment]
i have modified some files following another topic like change /etc/systcl.conf and /etc/security/limits.conf

**Comment by anacondaqq** [comment]
@croxinuz do as i said above. It's like i said before, the issue with the kernel, and not related to rathena.

or just upgrade your kernel (if you have ubuntu / debian based distro, try)

aptitude search linux-image*
find latest kernel (i recommend to use 4.* because they implement a lot of awesome low-level features related to network (different fixes which make you tank any ddos attack (mostly syn-flood-based) much softer.

Then install kernel via apt-get install linux-kernel-image.version.4x (maybe wrong, google for right command).

Anyway, as i remember you can increase maximum opened files without reinstalling kernel, by just increasing limit of maximum opened files at kernel (google at internet, these settings related to /etc/sysctl.conf)

**Comment by aleos89** [comment]
As stated by @anacondaqq, this is a limitation on your host, not rAthena.
