### ISSUE TITLE
NoKnockBack preventing Back/Front Slide

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1227]
The effect  **bonus bNoKnockback,0**;
(Used by Brynhild 2383 for example)

Prevents the skills **Back Slide** and **Front Slide** from Mechanic to be working properly.
It seems as if the skills are triggered as an actual knockback.
I guess Back Slide from Assassin Cross as well, haven't tested it though.

I don't know if that's an "official behaviour" but it's kinda retarded.

**Comment by Playtester** [comment]
I know that Backsliding of the Assassin works with knockback immune equip, we even have a bitset for that in skill_blown:
```0x02 - ignores players' special_state.no_knockback```

```c
	case TF_BACKSLIDING: //This is the correct implementation as per packet logging information. [Skotlex]
		clif_skill_nodamage(src,bl,skill_id,skill_lv,1);
		skill_blown(src,bl,skill_get_blewcount(skill_id,skill_lv),unit_getdir(bl),2);
		break;
```

```c

	case NC_F_SIDESLIDE:
	case NC_B_SIDESLIDE:
		{
			uint8 dir = (skill_id == NC_F_SIDESLIDE) ? (unit_getdir(src)+4)%8 : unit_getdir(src);
			skill_blown(src,bl,skill_get_blewcount(skill_id,skill_lv),dir,0);
			clif_skill_nodamage(src,bl,skill_id,skill_lv,1);
		}
		break;
```

Honestly it looks like all the renewal devs always just put flag "0" for all skills they implemented rather than testing it what kind of knockback type it is.

Of course should be tested on Aegis first.

**Comment by Playtester** [comment]
Tested: Yes, the Mechanic sliding skills should work even with Brynhild equipped. So the flag should be 2 instead of 0.
