### ISSUE TITLE
clif_parse_GMReqAccountName (CZ_REQ_ACCOUNTNAME) usage?

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#123]
0x01df,6,gmreqaccname,2
clif.c::clif_parse_GMReqAccountName
CZ_REQ_ACCOUNTNAME

**what does it do? also with the clif_account_name (ZC_ACK_ACCOUNTNAME)?**

Can we just disable it?
* We still don't know the function yet, even @lighta assumed it asking account name like 'simple ver' of `@accountinfo` command (just return the user name from specified account id) https://github.com/rathena/rathena/commit/c9532369cb3a67096ad819a13cfaae5fa0cd96a2#diff-85d990dde8caf2d72d1e2b0f7dcf9786R13062
* Even we assumed like that above, supported client by rA 2012-04-10 & 2013-08-07 doesn't request that packet
* What I tested, only **2010-07-30** client (from supported client) that asks the packet, and the client spams the request after right-clicking NPC, and this is real annoying.

but, by disabling it doesn't solve the issue, since client still keep going to spam the packet. xD
well, CMIIW

**Comment by anacondaqq** [comment]
i dunno what you need more. Really. In post above i did sent all information what need to make it reproduce. Please, dear lighta, take attention to game exe, this problem happened 100% to 2010-07-30.

Btw, for the current day, this problem is solved by some commit from cydh, he did remove this from right button action. (i forgot a commit about this)
