### ISSUE TITLE
MVPs with slaves cause a map server crash

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1238]
as the title says,
MVPs with Slaves causing Map server crash Since *r17063* up to present.

**Comment by keitenai** [comment]
as the title says,
MVPs with Slaves causing Map server crash Since *r17063* up to present.

**Comment by Vomaito** [comment]
maybe this is the same bug I post.
https://github.com/rathena/rathena/issues/1235

**Comment by spinzaku** [comment]
mvp slaves? like the slaves from AMON RA? my server didn't crash thou

**Comment by Lemongrass3110** [comment]
17063 is 55e4df14c2141f291a985c391408a045ec1b25c4 aka the overhaul of the mob modes.

I am not able to reproduce this. Please provide more information and see if you used the provided converter.

**Comment by Vomaito** [comment]
How do you know that are slaves? the mvp cast and your server crash when cast bar is 100% green?
Testing with ifrit I got a crash but only when 2 people or more are atacking, I think we have the same problem, because if you fight alone the mapserver not crash.

**Comment by keitenai** [comment]
I tried to find the main cause the of the server crash, and one of it is the skill "WZ_FROSTNOVA".
which is 100% crashing the server. i will check the other causes.

**Comment by Vomaito** [comment]
@keitenai do you have custom source mods? because my Map-server didn't crash with Frost Nova. But crash with some mobs skills.

**Comment by spinzaku** [comment]
my server just crashed using latest git

**Comment by Lemongrass3110** [comment]
I am totally unable to reproduce this on a clean clone of rAthena master.
Please provide any changes you made or information that helps to backtrace your problem.

**Comment by keitenai** [comment]
[From a Clean rAthena]

setting: renewal
clientver: 20151029
packetver: 54
PacketObfuscation: OFF

mob_skill_db:
All skills for MVP 1639 removed. except of the following:
1639,Kathryne Keyron@WZ_FROSTNOVA,chase,88,10,3000,1000,10000,no,self,always,0,,,,,,,
1639,Kathryne Keyron@WZ_FROSTNOVA,attack,88,10,3000,1000,10000,no,self,always,0,,,,,,,

100% server crash

**Comment by spinzaku** [comment]
Just tried and map server crashed.. CONFIRMED Kathryne Keyron@WZ_FROSTNOVA, causes mapcrash

**Comment by Playtester** [comment]
Weird, I still can't reproduce it. I have a clean checkout, except some changes item and removed from Kathryne all skills except those two Frostnovas. She can cast the spell just fine, I even freeze. She breaks freeze with next hit... no crash. o.o

**Comment by spinzaku** [comment]
My server crashed twice when my players went in the map where keyron is. 3rd crash from me when i tested myself.. warped to the map.. instant aggro.. 15 sec later map crash

**Comment by Tokeiburu** [comment]
I'm guessing the issue is coming from status.c, status_check_skilluse at :
```
	switch( target->type ) {
		case BL_PC: {
				struct map_session_data *tsd = (TBL_PC*)target;
				bool is_boss = (status_get_class_(src) == CLASS_BOSS);
				bool is_detect = status_has_mode(status,MD_DETECTOR);

				if (pc_isinvisible(tsd))
					return false;
```
with the following backtrace (src being NULL at this point):
status_get_status_data
status_check_skilluse
skill_attack_area

This affects the Breath skills (Fire Breath for instance, which requires Ifrit to be below 80% and have two alive targets to reach this code, because of skill_attack_area) and Frost Nova as well. You're not supposed to crash though, you should only be getting the following warning:
```
--- nullpo info --------------------------------------------
c:\*\rathena\src\map\status.c:6973: in func `unknown'
```
which then returns a dummy status. The dummy value might be null though? I wasn't able to crash, but changing the line to 
```
bool is_boss = status->class_ == CLASS_BOSS;
```
would probably fix it.

**Comment by Playtester** [comment]
Oh you found it at the same time as me, just wanted to post. XD

But your change doesn't really work because status is just some dummy status. In that function "src" is NULL if it's an AoE skill. I think we might need to check separately for source, because if I remember correctly AoE skills don't hit hidden targets (except Heavens Drive) but they can always hit cloaked targets.
