### ISSUE TITLE
GUILD SKILL 10013,GD_EMERGENCYCALL bug

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1245]
I've tested GUILD skill e.call from clean rAthena but it's not  working at all

**Comment by aleos89** [comment]
Can you provide your Git hash? Also can you provide some more details? What's your `emergency_call` configuration set to? Depending on that, is it not working on all maps or GvG maps? Is this during WoE or not during WoE?

More details helps us resolve this quicker.

**Comment by keitenai** [comment]
My apologies, i found out that there's a delay of few minutes before you can use GD_EMERGENCYCALL from the moment you log in.

**Comment by RadianFord** [comment]
I've tested it using this hash : 0c09928dd3ea75f7be745da9e87fec0cfb4b87f1 and it is working fine. you might need to see

// Activate guild skills delay by relog?
// Official setting is 5 minutes (300000 ms), otherwise allow guild leaders to relog to cancel the 5 minute delay.
guild_skill_relog_delay: 300000
