### ISSUE TITLE
Online flag in char table gets unset for autotraders

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1249]
I noticed a problem with the 'char ' table in sql data pack. When a player is online, there is a column in table ' char ' called ' online ' that mark as 1 online players. 

The problem with players with stores in autotrade . 

After a time, players are getting autotrade 0 in column 'online'. It becomes a problem since remote tracking systems rely on this column for the count. Showing an incorrect count for sites and external panels.

**\- This problem is somewhat worse by the fact hinder the player relog his autotrade, since failure to relog.**

Obs:
The atcommand who displays the correct count.

Rev: Recent emulator version -Commits on May 2, 2016
Client: 2015+

**Comment by Lemongrass3110** [comment]
Adjusted your text a little do not forget that you link other people on github when you use the @ symbol.

The atcommand displays the correct value since the map server reads the information directly from RAM and not from the char servers table.

Have you possibly noticed anything in how that might be happening(like for example your char server getting disconnected or something)?

**Comment by Badarosk0** [comment]
Right. What I realized is that ' Vendings ' table is deleting some records of some stores over time. There are more players in autotrade than shown in ' Vendings ' table. I did not see problem with char -server.

**Comment by Baalberith6** [comment]
May be connected to this: https://github.com/rathena/rathena/pull/1089

**Comment by Badarosk0** [comment]
With this setting solves ?

**Comment by anacondaqq** [comment]
I can totally confirm @Badarosk0, i have reported about this issue several times, but i have no time to find out why that trouble happened to me. Anyway, issue exist in earlier revisions (2014 - up to 2016 - march).
Right now, with the fix from @Baalberith6 i have no issues yet. 

@Badarosk0 tell me please few details about your database size & disk type. Are your db used frequency by game-server or not? Are you have ssd, or just hdd? Maybe bottleneck in disk... ( i have replaced old disk in april for a new one, and don't have any issues yet). Maybe it's because of new disk, maybe because of latest patches & @Baalberith6 patch, i dunno..

**Comment by Lemongrass3110** [comment]
Could you guys confirm that this issue was fixed by @Baalberith6 when cydh merged his pull request in 3e4d2b8 please.

**Comment by aleos89** [comment]
This was merged in 3e4d2b8.
