### ISSUE TITLE
getequipid not supporting high IDs

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1251]
Probably same issue as here:
https://github.com/rathena/rathena/issues/1160

My script using the following script command:
	if ( getequipid(1) == 63011)

_does not work anymore._

So i would bet on the 32767 limit.

Would be great if **all script commands** and **related features **would be fited to the new limit as well.

**Comment by Lemongrass3110** [comment]
Unfortunately not. It directly pushes the value from the item structure into the script stack.

https://github.com/rathena/rathena/blob/master/src/map/script.c#L8100:
```
	item = sd->inventory_data[i];
	if( item != 0 )
		script_pushint(st,item->nameid);
	else
		script_pushint(st,0);
```

I would rather think that you might be using the wrong value(1) since I refactored the constants for equipments in 2bf64c97738e05576d86774a0ba547416647f4d1.
It might be good if you use constants where possible in the future:
https://github.com/rathena/rathena/blob/master/src/map/script_constants.h#L662

If this is the problem you are experiencing please close the issue yourself and open an issue for any command you find that is not supporting the new ranges.
Thank you for understanding.

**Comment by Everade** [comment]
@Lemongrass3110 

Wrong value?

Just to make things clear:

These are all OLD scripts, with old i mean like **10 years** old.
_They worked for the past 10 years._
And they stopped working when i REPLACED the old with the new item ids.
_And updated rAthnea_

so it has to be either the id limit.
Or it's something rAthena changed recently and i have no idea what exactly.
What else could cause the problem if i haven't touched anything else?

I have now several quests which aren't working anymore because of this.


Or am i forced now to replace all 1 with EQI_HEAD_TOP ?

Would be great to know.

**Comment by Lemongrass3110** [comment]
It would have been better if you have used the constants 10 years ago already.

The problem was the original implementation of these constants, which differed in /db and /src and created an ambigous meaning. If you had used the consts you would not even have noticed this commit, since only the values behind those constants changed.
Keep in mind that not all of these constants come from us a lot of them come from Gravity and you will never know when they might change a value/id of something. So it's wise to use constants where possible. An additional sideeffect is that in increases readability of your code.

As for that exact portion of code you pasted:
EQI_HEAD_TOP had the value 1 before that commit, after this commit it has the value 6.
So you would either have to change the call to use 6 or use the constant EQI_HEAD_TOP instead.

The best way to fix all your scripts with a few find and replace actions would be to take the old values from here https://github.com/rathena/rathena/commit/2bf64c97738e05576d86774a0ba547416647f4d1#diff-eb9a3a287eb38d923881f7be07f25c59L19 and replace them with the appropriate constants for the following commands:

- getequipid
- getequipuniqueid
- getequipname
- getequipisequiped
- getequipisenableref
- getequiprefinerycnt
- getequipweaponlv
- getequippercentrefinery
- successrefitem
- failedrefitem
- downrefitem
- delequip
- breakequip
- getequipcardcnt
- successremovecards
- failedremovecards
- getequipcardid
- unequip

I'll keep this issue open, but it is definitely not an issue with the getequipid command itself.

**Comment by Everade** [comment]
Thanks for the clarification.
However i haven't scripted most of these quests, yet i'm also not the most advanced scripter myself.

Good to know that i can fix it now ;)
