### ISSUE TITLE
import/item_noequip does not overwrite original entries

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1319]
the item_noequip inside the import folder does not overwrite original entries which are used in the db/re folder.

Instead it stacks.

Is this intended?
- If yes consider this a suggestion.
- If no, looking forward for a fix.

**How to reproduce :**
I want Giant Fly Wing to be restricted in PVP maps only, so i create a custom entry which fits my needs as follows

_db/re/item_noequip.txt_
12212,1	//Giant Fly Wing  **(OFFICIAL ENTRY)**

_db/import/item_noequip.txt_
12212,2	//Giant Fly Wing  **(WHAT I WANT)**

**Outcome:**
Giant Fly Wings is still blocked on Normal Maps, and additionaly i can't use it in PVP maps.
But if i'm already customizing it on my own, i expect it to do what i want without modifying the official entries (like on all other import folder files)

Thank you

**Comment by Stolao** [comment]
Hmm that seems wrong imo

**Comment by aleos89** [comment]
The reason is because of this line:
```
id->flag.no_equip |= atoi(str[1]);
```
It comes down to the possibility of adding multiple defines of an item in the file (so they can be defined in each "zone"). During the import process we don't account for this and things read from the main file are just added onto the import.

Here comes the zinger -- how do we determine if the person wants to overwrite the entire flags defined on an item (which usually is what the import feature is for) or if we want to add on to the flags.
