### ISSUE TITLE
[BUG] Skill Enchant Blade RK

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1327]
When using the skill , you can cross any protection.
Safety wall
White Imprison
Kings Grace
...
Any skill is useless when the RK uses enchant blade .

**Comment by Playtester** [comment]
Hmm, I gotta test that on official servers. It could be that our final attack modifier function is misplaced, but that would affect several other damage skills too.

I'm pretty sure the damage part goes in `battle_calc_weapon_final_atk_modifiers` because it overrides all resistances, including elements. Gotta test with Safety Wall I guess.

**Comment by Playtester** [comment]
Confirmed, Enchant Blade should not work for blocked attacks like from Safety Wall and King's Grace.
