### ISSUE TITLE
ItemInfo maximum amount of results

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1345]
Atcommand Iteminfo does not display the "Displaying X out of Y matches" when a player searched a term that has more than Max_search results.

It is because of the code here:
```
if ((item_array[0] = itemdb_exists(atoi(message))) == NULL)
		count = itemdb_searchname_array(item_array, MAX_SEARCH, message);
```

It sets count to whatever max_search is and then the next part of the code:
```
if (count > MAX_SEARCH) {
		sprintf(atcmd_output, msg_txt(sd,269), MAX_SEARCH, count); // Displaying first %d out of %d matches
		clif_displaymessage(fd, atcmd_output);
		count = MAX_SEARCH;
	}
```

Always thinks count is not bigger than Max_Search.

**Comment by Lemongrass3110** [comment]
Please do not use the @ symbol, write atcommand instead, because otherwise you will link a user on github. Funny enough that a user with the name "iteminfo" exists.

This is a general problem of the function itemdb_searchname_array since the loop in there is canceled after MAX_SEARCH hits. Since this function is only used by atcommands who all have the same error handling I would suggest to either edit the core function or change the error handling code. What would you like better @aleos89?

**Comment by aleos89** [comment]
It would be best, in my opinion, to rewrite the core function since it's used across multiple atcommands.
