### ISSUE TITLE
Related to #1382 (more issues with quests)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1385]
Hi, first of all check this issue: #1382 

After deep code-review of each NPC which uses 
`changequest ID,ID2` i found many interesting things, that a there are not extra checks before changing quest from ID1 to ID2, and if player will talk again to npc with `changequest ID,ID2` we will get error in map-server output log.

I have verified around 64 npc scripts, and found a way how easy it to fix.
If you have NodePad++ or Sublime Text, find with next regex pattern strings, and replace by next statement.

#### find regex:
> (changequest (\d{3,5}),\d{3,5};)

#### replace (regex)
> if (isbegin_quest($2) == 1) $1

where $1, and $2 it's regex variables (do not touch them).
These strings will totally fix ALL issues with change_quests errors in map-server log for all NPC's (sure, if you will apply it to all).

Revision: all latest
Mechanic: pre-re and renewal.

P.S. you can test regex strings here: https://regex101.com/
P.S. with sublime text, you can do it for all files in npc folder out the box.

**Comment by Lemongrass3110** [comment]
Hey @anacondaqq,

thanks for your report. I think that it is more critical to find out where the issue comes from, since these kind of warnings do show us, that something in the quest flow might be wrong/incomplete.
So instead of just catching all the errors beforehand it would be wiser to look into the quest flow where the changequest is issued and cannot be done.

If you found some certain changequest commands where you think this could happen, please let us know the details about it so we can look into it!

**Comment by anacondaqq** [comment]
@Lemongrass3110 you are totally right!

**Comment by secretdataz** [comment]
@anacondaqq You can also submit your change as a pull request, so we can just review it and hit the merge button. :)

**Comment by Lemongrass3110** [comment]
#1405 is unrelated to this one.

**Comment by Lemongrass3110** [comment]
No further comment since june. Closing this.
If you find some more please open an issue or create a pull request.

**Comment by anacondaqq** [comment]
okie :+1:
