### ISSUE TITLE
[BUG] Skill LANDPROTECTOR failing border

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1404]
Currently LANDPROTECTOR ability is a problem. The test was done with 2 Chars in PvP. 

A char uses the ability LANDPROTECTOR the other uses a skill in an area, for example, Psychic Wave with center outside the skill in LANDPROTECTOR, noting that part of the area affecting the target within the LANDPROTECTOR. 
The target takes damage. 

If the center of Psychic Wave is born in the LANDPROTECTOR does not affect the target that is in LANDPROTECTOR.

If you are not clear, I can post picture showing.

Link old bug: https://rathena.org/board/tracker/issue-5237-land-protector-border/
Link old bug 2: https://github.com/rathena/rathena/commit/e7e8b54

**Comment by secretdataz** [comment]
Uh, well, I can't understand what you are trying to say.
Care to explain more?

**Comment by secretdataz** [comment]
Tested on official.
If PW's center is placed outside of LP, it will still does damage to anyone in its AoE even if that player is standing in LP.
If PW's center is placed inside of LP, it will simply does nothing but showing its visual effect.

**Comment by Badarosk0** [comment]
Use the protective land skill. Enter the skill area . With another character use Psychic Wave or any other skill area. The center of this another skill must be out of the protective land . If someone is on the edges of protection will be affected.


Images demonstrating the problem: http://postimg.org/gallery/wjm47igy/

**Comment by secretdataz** [comment]
That's intended behavior of LP. It does not protect players standing on it from splashing effects caused by units outside it. LP just prevents placing of any unit on top of it.

**Comment by anacondaqq** [comment]
Hi Dear @secretdataz 
You are totally right, and right now Land Protector works fine like it should at officials, but closing the issue is not a solution, let me explain why.

The issue with land protector were confirmed and fixed around 9-12 monthes ago, as i remember @Playtester have fixed the issue. Have fixed the issue after **ATTENTION! more then 8 years**.

A lot of people who don't playing at official servers do not understand this change, they start to blame GM's, rAthena emulator developers, and they start to insult all of people who trying to make official server for them. The reason why they do that is very simple: *They are accustomed to the old, and do not want to change anything, and they will not change anything, because they like how it was. They start to report about the issue like about critical bug, and then a lot of peole just quit a server.*

The problem is very popular, and be sure a lot of people will report about the issue again, and again, and again, here is founded by me reports about the issue from hell a lot of admins.

A lot of server owners DO NOT WANT to use rAthena because of the issue for pre-renewal servers. And yes, i'm talking only about pre-renewal mechanic. A lot of GM's do not want to update their servers because of land protector.

I'm too lazy for finding in my bookmarks a different ro-servers forums with the same bug-reports about borders. But this is very popular problem for now.

Just suggestion: please make config option in skill.conf for returning back old (bugged but which were for last 8 years) behavior of land protector? 

#### For example:

**skill.conf**
```
// Land protector behavior
// 0 - default, official Land Protector border behavior.
// 1 - old (bugged), eathena style Land Protector behavior.
land_protector_behavior: 0
```

**Comment by Badarosk0** [comment]
Very good this information. In fact I've heard reports of it being a bug and indeed their explanations were complete.
There was one or two that said it was a bug ... Thanks to both the information and tests.

**Comment by Skormie** [comment]
I strongly support adding a condition for both land protector effects although more description should be added to the old condition. Just wish I had my time to make it myself.
