### ISSUE TITLE
error in Thor Volcano Base Quest

### ISSUE THREAD

**Issue by dynaraan** [rathena/rathena#1405]
![bug](https://cloud.githubusercontent.com/assets/19202072/16452000/6cae4738-3e30-11e6-8b77-3bfabe8c4165.png)
there seems to be an error in Thor Volcano Base Quest

**Comment by secretdataz** [comment]
Relevant issue: #1385

**Comment by Lemongrass3110** [comment]
Regarding your errors with "quest_change". These are not related to #1385.
You simply do not have them in your quest_db or they can not be read by the mapserver(syntax error for example). The quests have been in since 2010-11-23(85a42500604c4280949848ec77615103c5f066a4). So if you do not have them yet you might want to upgrade your emulator...
