### ISSUE TITLE
Bug bAddClass

### ISSUE THREAD

**Issue by VXPlay** [rathena/rathena#1406]
Hello everybody, I was testing a few items here and saw that the bonus is not working .

Item:
`2910,Bakonawa_Tattoo,Bakunawa Agimat Tattoo,4,20,,100,,0,,0,0xFFFFFFFF,63,2,136,,1,0,0,{ bonus2 bAddClass,Class_All,7; bonus bAspdRate,10; },{},{}`

Bonus:
`bonus2 bAddClass,Class_All,7; bonus bAspdRate,10;`

The speed bonus works, but not to attack.

Without the amulet:
http://prntscr.com/bn2nkn

With the amulet :
http://prntscr.com/bn2o2y

**Comment by Lemongrass3110** [comment]
Unable to reproduce this bug on cf4e6495fe401d20ebe8e02fb94e4a48c2c67143 in renewal mode.
Please also note that you might want to try it with a little more damage.
I tried it with item 1177 and my RKs damage went up from ~1250 to ~1450.
`1177,Muramash,Muramash,5,20,,0,120,,1,0,0x00004082,63,2,34,1,0,0,3,{ bonus2 bAddClass,Class_All,50; },{},{}`

**Comment by Atemo** [comment]
Unable to reproduce as well in pre-renewal on b8a221fc99d0bf087ff0f04ca3fac5b015631afb. Please read https://github.com/rathena/rathena/issues/718#issuecomment-152495018

**Comment by Paoly28** [comment]
i was able to reproduce it on fbf7957, using any equipment it works however it doesn't work on Shields.

**Comment by Paoly28** [comment]
your test is obsolete VXPLAY since modifiers doesn't work with status atk. i tested with +20 Grimtooth w/  power maximize and tournament shield damage didn't increase

**Comment by Paoly28** [comment]
i changed shield of death into

`2177,Shield_Of_Death,Shield Of Death,4,20,,2000,,150,,1,0xFFFFFFFF,63,2,32,,90,1,3,{ bonus2 bAddClass,Class_All,100; bonus2 bMagicAddClass,Class_All,100; },{},{}`

![screennew heimdall015](https://cloud.githubusercontent.com/assets/8035101/16645856/74ce0bae-4459-11e6-9e0a-f042252aa84e.jpg)

your test is obsolete VXPLAY since modifiers doesn't work with status atk.
