### ISSUE TITLE
Non-ranged skills problem

### ISSUE THREAD

**Issue by alternateRath** [rathena/rathena#1423]
when using some regular skills like bash or envenom.. if the character is too far from the target it will walk until 1~2 cells from it and stop without using the skill.. if the distance between the character and target is something like 3~4cells the character will remain at the same place without walking to the target
and sometimes the character can reach target and use skill without no problem

client date- 2012 04 10
git hash? how do i get that?

i uploaded some ragnarok replay files and this youtube video

https://www.youtube.com/watch?v=SPPXHC7TRgc

[Replay.zip](https://github.com/rathena/rathena/files/356024/Replay.zip)

**Comment by RadianFord** [comment]
I also noticed this one i thought it was just my internet connection...

**Comment by Playtester** [comment]
Seems to happen when the distance is 2 in one direction and 1 in another direction. But it works fine on my client, maybe client related problem?

When enemy is 2 west and 1 south of me and I use bash, I walk one cell southwest so I'm just one cell east of the monster and only then attack.

**Comment by RadianFord** [comment]
I am using 20131223cRagexe pre renewal mode i am uploading the video now it may take some time...

**Comment by RadianFord** [comment]
So i did record a video with a mobs that is not moving and here it is
https://www.youtube.com/watch?v=XvqgZn4VAyI&feature=youtu.be

**Comment by LiamKarlMitchell** [comment]
From some observations of my own.
This seems to happen for ranged skills, ranged attacks and skills such as steal and turn undead.
Maybe on others, I have not checked yet.

2015 client.
Recent-ish git clone.

In a straight line range can be counted in tiles between you and target.

What I think happens
![image](https://cloud.githubusercontent.com/assets/1968109/24547614/3c2db498-166d-11e7-91f2-2f72aba9c682.png)

Distance is checked with range + 1
Target can be considered in the center, and character/attacker on outside.

It seems like the horizontal and vertical ranges get an extra +1 added to them.
Being in the black areas are no walk areas, the server will consider you out of range but will not walk you into range.

If you stand 1 outside the black area and click to use skill on target it will walk 2 tiles and be in the blue area.

What a square check would be like
![image](https://cloud.githubusercontent.com/assets/1968109/24547625/4583c7e4-166d-11e7-8f38-57319a822097.png)


What I think the circle check should be like.
![image](https://cloud.githubusercontent.com/assets/1968109/24547632/4d8568bc-166d-11e7-9df3-5ebcb02bf000.png)

The target should always be in the center. (Or caster I guess either way same thing)
The max distance away is the range.
Black areas must walk into the range as must outside black areas.

The black areas would be considered in range if using a square area of effect. Such as Pneuma?

The circle edges would get more interesting at further radius ranges, but the logic should remain the same.

Source: Kinda... cant use every circle as is because user should be in the center.
https://i.imgur.com/9PGer.jpg

But maybe same range should be considered for all direction? Unless sub tile accuracy is a thing.

Anyway, I'll try to have a play at some point with the range checks for the skill. I think its in battle_check_range in the function call elemental_action in elemental.c and unit.c unit_skilluse_id2.

**Comment by anacondaqq** [comment]
@LiamKarlMitchell i think you are not wrong, please check this too: https://github.com/rathena/rathena/issues/1427 maybe it's related to problem.

**Comment by LiamKarlMitchell** [comment]
@anacondaqq Thanks I have seen a few issues that may be related to this.
I was considering making own issue just for skills but eh. I figure its related to this too because I also tested with just bow attack.

Hmm yeah that appears to be the problem me and some friends are experiencing.
If your in those black corners shown on the top one.
You can't attack, and it does not walk into range.

Thanks for the info you put on the other issue, I will have to read it further when i'm more awake and in that head space /heh.

**Comment by TheNoobCompany** [comment]
Can confirm on c87dba5a52594772a6fbdbbff209bef0e22e85a7 + 20130807 pre-renewal

Cannot cast certains skill, it'll move up to 3case away from target then stop and do nothing.

the work arround provided by Playertester do works, until you fix the issue for good ;)

**Comment by Playtester** [comment]
The issue is still one that doesn't occur on my system. I already coded a timer logic in that delays you skill casting until after your movement is done, so even though the client already makes you move one cell closer than what you should need, the range check still fails. Seems impossible to me unless the target is moving away. I already made sure the client range check is identical with the server-sided one, so that can't be the issue either.

In the end the issue is caused by me fixing a range exploit. We now deny attack commands when the target is not in range. Beforehand, the skill would just have happened, but that opens also the exploit that you could just send attack requests out of range. Consequently I really don't want to "fix" that. 

If anything, I could add a config where people can decide between secure or smooth.

**Comment by LiamKarlMitchell** [comment]
Yes I think a config is a good idea, would a #define in mmo.h and using #ifdef or similar be the appropriate way to do this kind of thing?

During my testing the target has been standing still.
I shall continue to play with it when I get some time, thanks for your input.

**Comment by whateveremer** [comment]
It also happens to ground skills like land protector check this video
https://youtu.be/FoXP9OX6ee8

**Comment by LiamKarlMitchell** [comment]
@whateveremer Oh wow how are you showing the tiles? I remember seeing some blog post to do with it somewhere years ago but can't remember the software.

**Comment by whateveremer** [comment]
I edited it and used photoshop, the bug I posted is not related to this issue I found out that i'm using an outdated luafiles version, the lua files I used has no attackrange in skillinfolist

**Comment by Playtester** [comment]
That video is really strange, it's as if the client range is one larger than the server range. I really don't have that issue in my client. =o

**Comment by TheNoobCompany** [comment]
try using the 2013 client ? 20130807

**Comment by anacondaqq** [comment]
@Playtester this is not first time when you don't have issue at your own side while around minimum 5+ totally different administrators has it.

**Comment by Playtester** [comment]
Yeah, because it's still the same issue. And I tried it with both recommended clients.

I'd be curious if any of the other rAthena devs could reproduce it, because whoever can reproduce the issue can also fix it.

**Comment by Stolao** [comment]
I have done some testing on this using 20130807a client, and with a clean sec and client I am unable to reproduce this error,

However when using a custom skill where I have failed to define skill range it the skillinfoz.lua i am able to replicate this issue though even 10% of the time. 

This leads me to believe it's most likely a client issue rather then a server issue.

**Comment by Jeybla** [comment]
Thanks @Stolao !

@alternateRath @LiamKarlMitchell @TheNoobCompany does updating your `skillinfoz.lua` fix this issue?

**Comment by Playtester** [comment]
The client has an internal range it remembers and based on that it knows when to send a skill request and when to send a move request instead.

If we receive a skill request on the server and the target is not in server-sided range, the skill request will be dropped (simplified).

**Comment by TheNoobCompany** [comment]
Where do you find the updated skillinfo.lua when you says "installed to default settings" ?

**Comment by TheNoobCompany** [comment]
Still having the issue with an updated skillinfolist.lub with Investigate:
```
[SKID.MO_INVESTIGATE] = {
		"MO_INVESTIGATE",
		SkillName = "Investigate",
		MaxLv = 5,
		SpAmount = { 10, 14, 17, 19, 20 },
		bSeperateLv = true,
		AttackRange = { 2, 2, 2, 2, 2 },
		_NeedSkillList = {
			{ SKID.MO_CALLSPIRITS, 5 }
		}
	},
```

Is it correct ?

**Comment by Playtester** [comment]
So range is 2 and you are 3 cells west and 1 cell north of target?

**Comment by TheNoobCompany** [comment]
Yeah but what is wrong then ? 

Range at 2, auto walk, server ?

**Comment by Playtester** [comment]
Hmm, still can't reproduce it. When I'm 3 cells west and 1 cell north of the target and use Investigate my Champion moves 1 cell east and then uses Investigate.

**Comment by secretdataz** [comment]
Can't reproduce this. My char was 3 cells south and 1 cell west. It walked and used investigate normally. Same for other direction with 1+3/3+1.

![screenrathena035](https://cloud.githubusercontent.com/assets/2021243/25750236/48022d92-31db-11e7-914d-46587b0cdfe0.jpg)

![screenrathena036](https://cloud.githubusercontent.com/assets/2021243/25750239/48fe518a-31db-11e7-9a6b-7532a50bf870.jpg)

**Comment by Jeybla** [comment]
It is very likely a client side issue. Secret, Playtester and me weren't able to reproduce it. Only @Stolao was by messing up the `skillinfoz.lua`. So at this point we are in need of further informations. So please try to update your Client. If you found which part is causing this error, we'd be glad to hear your solutions.

Also @Playtester provided a workaround here: https://github.com/rathena/rathena/issues/2083#issuecomment-296143054
I wouldn't recommend the workaround, but it's still an option for you.

**Comment by RadianFord** [comment]
This is not related to this one right?
```
// Change attacker's direction to face opponent on every attack? (Note 3)
// NOTE: On official servers knockback of some skills like Firewall is always based on the
// last direction walked. Even when attacking in a completely different direction, the
// knockback direction won't change, so e.g. if you walk north and then attack an enemy to
// the south you will still be knocked back to the south by Firewall. Immobile monsters
// will always be knocked back to the south as their default direction is north.
attack_direction_change: 0
```

**Comment by TheNoobCompany** [comment]
@anacondaqq Do you still experience the issue ? How did you fix it if no?

**Comment by LiamKarlMitchell** [comment]
Client Date: 2015-09-16aRagexe

**Comment by TheNoobCompany** [comment]
I've tryed this file here: https://raw.githubusercontent.com/norb42/Translation/master/data/luafiles514/lua%20files/skillinfoz/skillinfolist.lub

It returns: 
---------------------------
Lua Files\SkillInfoz\SkillInfoList
---------------------------
[string "buf"]:3245: table index is nil

upon starting the game.

Where can I get updated files? (20170708)

**Comment by TheNoobCompany** [comment]
After updating the client files.

(which changed the  name of the spells to the original ones (like Asura => Guillotine))

this is no longer an issue, so I can confirm this is a bad client setup issue, not rAthena core one.

**Comment by RadianFord** [comment]
@TheNoobCompany can you link me the client files you we're using? if you dont mind.

**Comment by LiamKarlMitchell** [comment]
@TheNoobCompany Yes, would be most interested in knowing what I did wrong when setting up the lua files and such.

**Comment by TheNoobCompany** [comment]
Here's the luafiles514 folder, beware, it's not a reference, and it may contains customs stuff.
https://www.mediafire.com/?85c9l4eiekwrimf
It's for 20130807 client
