### ISSUE TITLE
pre-renewal rod MATK is out of synch!

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1435]
in renewal of course matk is its own column in item db, so its easy there. 

but this is about pre-renewal!! as you know, in aegis it's hardcoded that rod (and 2hand rod) gives an automatic 15% matk boost (who knows why they would do it this way). a few staffs have a bonus in their script like hypnotists in addition that may look like 5% matk boost, but because its a rod its really 20%, and appears as suchin our db.

some lack the default 15% matk boost entirely though, this should never happen! see Krieger_Onehand_Staff1 and Krieger_Onehand_Staff2
Krieger_Twohand_Staff1 as well lacks 15% base matk boost

Destruction_Rod should have a base of not 25 but 40% matk! makes it look a lot scarier with that kick

there might be a few others i missed. someone should sweep through and save our poor wizard friends from only doing a semi-extraordinary amount of aoe dps.

**Comment by mrjnumber1** [comment]
mmm, dunno if i should make new issue or not but another thing i notice:

diabolus ring should give 15% frozen resistance but doesn't. 

KVM armor combo should be doing bhealpower, instead its using bSkillHeal2. under default behavior this is fine, but it violates the promises of battle config skill_add_heal_rate!!! minor nitpick, really ..

**Comment by Playtester** [comment]
Can confirm, all rods have a hidden MATK+15% in pre-renewal. It adds together with the MATK in the script so MATK+5% in the script should lead to MATK+20%.

So yeah, all staffs should have at least MATK+15%, if nothing is in their script.

Can't confirm the thing about Destruction_Rod. It has +10% MATK in its script, so it should be +25% MATK by default. It increases every second refine, though.
If it's really +40% MATK, which would need some proof, then that would mean that all two-handed staffs should have a +30% MATK hidden bonus rather than +15% MATK.

And yes, Diabolus Ring indeed gives 15% resistance from freeze. It's in the renewal script and it was already listed as bonus before renewal, so it should be in both.

**Comment by mrjnumber1** [comment]
hm i see, in asb5_beta2 it's listed as (base 15)+25% bonus, but in all others it's the 10% bonus


BONUS: Edge coma rate is off by a factor of 10 based on what Lord_Of_Death_Card has.

**Comment by Playtester** [comment]
```
1132,Edge,Edge,5,20,,700,115,,1,0,0x000654E2,7,2,2,4,40,1,2,{ bonus2 bAddEff,Eff_Curse,30; bonus2 bComaClass,Class_Normal,10; },{},{}

4276,Lord_Of_Death_Card,Lord of The Dead Card,6,20,,10,,,,,,,,2,,,,,{ bonus3 bAddEff,Eff_Stun,500,ATF_SHORT; bonus3 bAddEff,Eff_Curse,500,ATF_SHORT; bonus3 bAddEff,Eff_Silence,500,ATF_SHORT; bonus3 bAddEff,Eff_Poison,500,ATF_SHORT; bonus3 bAddEff,Eff_Bleeding,500,ATF_SHORT; bonus2 bComaClass,Class_Normal,1; },{},{}
```
That's already correct in the database.

**Comment by mrjnumber1** [comment]
you're right, i totally missed it

although i'm not sure if the chance is meant to be .01% on LoD or .1%.. stupid inconsistencies.
