### ISSUE TITLE
Having 0 SP does not immediately cancel the effect Crystallization.

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1477]
As stated here:
http://irowiki.org/wiki/Status_Effects#Crystallization

> Having 0 sp will immediately cancel the effect. 

Steps to reproduce: Use diamond dust on player with 0 SP and they'll still be in Freezing State.

I'm using rAthena's latest version

**Comment by RagnarokNova** [comment]
Outdated. This was a bug which was semi-recently fixed in kRO:
http://ziu-ro.blogspot.com/2015/12/02122015-mantenimiento-kro.html

"- El estado [crystallization] se cancela si tu SP es menor 0 y este fenomeno se corrige."

"Crystallization state would cancel if your SP is less than 0, and this phenomenon has been corrected."
