### ISSUE TITLE
AddEff Bonus

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1638]
Hash: b2f0ffb
Mode: Both

The AddEff bonus is not behaving as it does on Aegis. The effect should still trigger even if the target has more resistance.

rAthena Behavior:
- Checks if you have an AddEff bonus.
- If you do, call `status_change_start(..., rate,...);`
- This never happens because the rate gets reduced to a negative number due to resistances, so the bAddEff has a 0% chance of success.

Aegis Behavior:
- Checks if you have an AddEff bonus.
- Does a `(rnd() % 10000 >= rate) ? continue : else`...
- Call `status_change_start(..., 10000,...);`

Thanks to @Tokeiburu for confirming!

**Comment by Playtester** [comment]
That's interesting, that means the self-inflicted status changes actually can happen even if you have 1+ LUK. It's just that the chance can be as low as 0.000001%. That why it never triggered even after 50000 attacks when I tested.

**Comment by Playtester** [comment]
I still have my doubts on the validity of this issue. In both pre-renewal and renewal episode 14.1 it does not work like this. A 0.1% chance for example can be resisted with a single point in LUK. For example if you equip a Murasame, you always need 1 more LUK than BASE LEVEL because each base level increases the chance by 0.1% and each LUK decreases it by 0.1%.

Can you please posts the detailed tests Tokeiburu did to proof this?

**Comment by aleos89** [comment]
With some more testing we were able to prove the real culprit is renewal status resistances are not implemented.
