### ISSUE TITLE
Client Walk Jerk 2015-10-29

### ISSUE THREAD

**Issue by Smokexyz** [rathena/rathena#1655]
Not sure if it's a client issue but there's a jerk every second, when a character is walking.

Client date : 2015-10-29
Packet Ver : 54
rA revision : 40430d6cb56301aa7ac7580733051de8cd6177e2
[Image URL](https://i.gyazo.com/7a430066464afbbfc0d6679ea9d76b4a.gif)

**Comment by LiamKarlMitchell** [comment]
Hey, I notice this as well.

I think its a client side issue.
I have an NVIDIA graphics card and Windows 7 if that helps, Its a noticeable problem, but I don't think it is rAthena specific.

**Comment by anacondaqq** [comment]
Guys, 2015-10-29 client is very unstable because of a lot of problems with the exe, unknowed packets, etc. Try to use any near client (for example 2015-11-04 (this is better choise, but 2015-11-04 has some issues with linking system))

**Comment by KrokusPokus** [comment]
Try using /skip in the client to turn OFF frame skip and see if it helps. The frame skip limit's purpose is actually to prevent slowdown if a frame takes longer than ~16.67 ms to render, but it's implemented in a way that if you run at a frame rate of or slightly lower than 60 Hz, it still triggers once to twice a second, depending on your exact refresh rate. (Actually the implementation in the client is idiotic. It uses a fixed value for the maximum frame time instead of taking the used refresh rate into account. This has been a gripe for me since 2005 when I switched from a 85 Hz analog monitor to a 60 Hz TFT. If you run your screen at more than 60 Hz, the stutter goes away, if it's the one caused by frame skip.)
