### ISSUE TITLE
Bug Instances

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1661]
Is there a way of abusing some instances that need to be rectified.

A player can leave a group and enter the instance with another character while the instance is still generated, so if a player up the endless tower, after descending the group leader to stay up there, the player who left can get another character, the leader invites him to the group, and this guest player climbs the tower with the other character ... I believe this should not happen.

**Comment by Jeybla** [comment]
Related: 109b30dd5184e06806253e692fa0d893b24282e5

Why do you call this abuse if its simply a character joining another et group? This should be okay since you don't get any more MvPs.

From http://irowiki.org/wiki/Endless_Tower:

> Warning: If any party member leaves their party while inside the dungeon, they will be kicked out and sent back to their save point! However, they can be reinvited to the party and reenter the tower.
> [...]
> There is no limit on how many instances a party can create within the 4 hour limit. A new instance can be created under a different party leader if the previous instance was destroyed. Once the time limit is up, there is a 6 day 20 hour cooldown period for all party members in which they cannot enter a new Endless Tower instance. **However, additional instances will not allow access to additional MVPs.** 

But currently it's possible to kill many MvPs by just staying in the party and reopen the instance with a dummy party leader.

Quickfix: Disabling re-entering the instance completely.

Official: Extend the fix from @Atemo : Killed MvPs should be safed to a "party-attached" variable so they won't spawn by reopening the instance.

**Comment by cydh** [comment]
Well, it's official way to abuse the official server :D
but for PS owner, maybe will find this thing is annoying, you can add permanent char variable for quest delay when player enter the instance, and check it again before player re-enter the instance.

**Comment by Atemo** [comment]
The previous update was based on iro. However a player should get 2 ashes at the start and use 1 ashe to re-enter.

**Comment by admkakaroto** [comment]
regardless of the official, I think half wrong can abuse the ability to re-enter

**Comment by Lemongrass3110** [comment]
Officials solved this problem in 2017. Now you cannot leave, invite or expel from parties while an instance is active. I will be creating a pull request for this soon.
