### ISSUE TITLE
Automatic BLITZ BEAT skill not working with ATK_MISS

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1663]
According to my testers information this skill should work with monster/player with ATK_MISS. Can you check it and confirm? For now it's works only when you hit monster. If you miss - skill is not working, Thank you!

**Comment by Playtester** [comment]
Cannot confirm this one. On renewal at least, it clearly only triggers on hits. Given the fact that it worked like this on eAthena ever since it was implemented, I'd say it's highly likely that it's already working as intended.

If your tests show something else, please provide some proof like a video from official servers.

**Comment by mgksrt8** [comment]
No, I just need your answer to re-direct them. If they don't have proofs I will not fix it. Thank you. But, can you check it on pre-renewal AEGIS? Thank you.

**Comment by Playtester** [comment]
We have no pre-renewal Aegis server, can only test on iRO classic.

**Comment by mgksrt8** [comment]
Btw: http://irowiki.org/classic/Blitz_Beat

> May be triggered **even if the attack misses or is blocked by a skill**. Basically, a chance for every arrow.

**Comment by Playtester** [comment]
iROwiki is wrong on many things, shouldn't rely on that.

**Comment by Playtester** [comment]
Alright, I investigated it now and that auto-blitz triggers on misses was something that was patched in 2004 already with the Comodo patch.

Reference (old German hunter guide that clearly states that auto blitz no longer triggers on miss since the Comodo patch): http://rns.gamona.de/forum/topic/14071-dexagi-hunter-guide/

So this one is working as intended.
