### ISSUE TITLE
METEOR STORM should be placeable on Land Protector

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1699]
Git: cbc365d0f2f02ebceece4b6de7d58c8fe487f88f
Mode: Pre-Renewal
Bug: skill/unit
Issue: Meteor Storm should be placed on Land Protector but without any damage except someone remove Land Protector. This is official behavior. Example:
Player 1 cast Meteor Storm on the ground ( Scenario 2: Player 1 cast Land Protector );
Player 2 cast Land Protector under the Meteor Storm ( no damage ) ( Scenario 2: Player 2 cast Meteor Storm on the Land Protector - no damage );
Player 1 ( or another player ) cast Ganbantein on the Land Protector or another Sage/Professor cast Land Protector to remove the first one - in this case Meteor Storm WILL DAMAGE this area because on official server every HIT of Meteor Storm calculated separetly and counting as separate wave ( Storm Gust works in different way ) ( Scenario 2: Player 2 or another player remove Land Protector and Meteor Storm continue damage );

Thank you.

**Comment by Playtester** [comment]
This is not official behavior but old emulator behavior.

Official behavior is that the cells where the meteors land are calculated and placed on cast end. Putting Land Protector on them will remove them and cause the meteors to not appear even if LP is removed again later on.

Sorry, but this is definitely invalid because I investigated this a lot, including people using special grf files on official servers to make Meteor Storm cells visible.

**Comment by Playtester** [comment]
Reference: https://github.com/rathena/rathena/commit/1365d9418e96c028cad903fe5cab8edb7c8ae0fc

**Comment by anacondaqq** [comment]
Hi @mgksrt8 take a look for this fix: https://rathena.org/board/topic/107922-old-land-protector/
