### ISSUE TITLE
Bangungot Instance

### ISSUE THREAD

**Issue by gmsour** [rathena/rathena#1757]
No Bangungot spawned and warp portals show up (should show up only when Bangungot's life is critical).

**Comment by Darkelfen** [comment]
On your reports, as you have been told before, please provide further info so that the devs can pinpoint the problem and solve it more quickly. Things as:

Mode: renewal or pre-renewal.
Githash: at which hash are you (for example 561a874 I'm on this ATM).
Clientdate: The date of the client that you are using.
Steps to reproduce it: How can we replicate it.
Any custom mods?

**Comment by Akkarinage** [comment]
No additional information provided. Closing issue.
