### ISSUE TITLE
Tarot Card effect and rng rates dont' match official

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1768]
Currently our `CG_TAROTCARD` is very wonky, with a 1/14 chance of running off each its effects, but looking in aegis every effect has a variable chance, a few of the effects seem to be slightly different as well. for example the break card only affects helm, shield, and body armor.

here's my **UNTESTED** version working from disassembly to compare

```
// inside skill_castend_nodamage_id
	case CG_TAROTCARD:
		if( rnd() % 100 > skill_lv * 8 || (tsc && tsc->data[SC_BASILICA]) ||
		(dstmd && ((dstmd->guardian_data && dstmd->mob_id == MOBID_EMPERIUM) || status_get_class_(bl) == CLASS_BATTLEFIELD)) ) {
			
			if( sd )
				clif_skill_fail(sd,skill_id,USESKILL_FAIL_LEVEL,0);

			map_freeblock_unlock();
			return 0;
		}
		
		status_zap(src,0,skill_get_sp(skill_id,skill_lv)); 
		clif_specialeffect(bl, 523 + skill_tarotcard(src, bl, skill_id, skill_lv, tick), AREA);
		clif_skill_nodamage(src,bl,skill_id,skill_lv,1);
		
		break;


// and skill_tarotcard function below
/**
 * Process tarot card's effects
 * @ param src caster of CG_TAROTCARD
 * @ param target target of tarot
 * @ param skill_id id of the skill (hopefully, CG_TAROTCARD!)
 * @ param skill_lv level of skill_id used
 * @ param tick processing tick time
 * TODO: clean me up and vanish some magic numbers ?
 **/
static int skill_tarotcard(struct block_list* src, struct block_list *target, uint16 skill_id, uint16 skill_lv, int tick)
{
	int rate = rnd() % 100;
	
	if (rate < 10) // THE FOOL
	{
		status_percent_damage(src, target, 0, 100, false);
		return 1;
	}
	else if (rate < 20)  // THE MAGICIAN
	{
		sc_start(src, target, SC_INCMATKRATE, 100, -50, skill_get_time2(skill_id, skill_lv));
		return 2;
	}
	else if (rate < 30) // THE HIGH PRIESTESS
	{
		status_change_clear_buffs(target, SCCB_BUFFS | SCCB_CHEM_PROTECT);
		return 3;
	}
	else if (rate < 37) // THE CHARIOT
	{
		status_fix_damage(src, target, 1000, 0);
		clif_damage(src,target,tick,0,0,1000,0,DMG_NORMAL,0,false);
		if( !status_isdead(target) ) 
		{
			unsigned short where[] = { EQP_ARMOR, EQP_SHIELD, EQP_HELM};
			skill_break_equip(src, target, where[rnd() % 3], 10000, BCT_ENEMY);
		}
			
		return 4;
	}
	else if (rate < 47) // STRENGTH
	{
		sc_start(src,target,SC_INCATKRATE,100,-50,skill_get_time2(skill_id,skill_lv));
		
		return 5;
	}
	else if (rate < 62) // THE LOVERS
	{
		status_heal(src, 2000, 0, 0);
		if( !map_flag_vs(target->m) )
			unit_warp(target, -1,-1,-1, CLR_TELEPORT);
		
		return 6;
	}
	else if (rate < 63) // WHEEL OF FORTUNE
	{
		// i suppose a nightmare scenario exists where
		// this ends up occuring recursively but if so you made a miracle !!
		skill_tarotcard(src, target, skill_id, skill_lv, tick);
		skill_tarotcard(src, target, skill_id, skill_lv, tick);
		
		return 7;
	}
	else if (rate < 69) // THE HANGED MAN
	{
		enum sc_type sc[] = { SC_STOP, SC_FREEZE, SC_STONE };
		uint8 rand_eff = rnd()%3;

		sc_start2(src,target,sc[rand_eff],100,skill_lv,(rand_eff == 2 ? src->id : 0),skill_get_time2(skill_id,skill_lv));
		
		return 8;
	}
	else if (rate < 74) // DEATH
	{
		status_change_start(src, target, SC_COMA, 10000, skill_lv, 0, src->id, 0, 0, SCSTART_NONE);
		sc_start(src,target,SC_CURSE,100,skill_lv,skill_get_time2(skill_id,skill_lv));
		sc_start2(src,target,SC_POISON,100,skill_lv,src->id,skill_get_time2(skill_id,skill_lv));
		
		return 9;
	}
	else if (rate < 82) // TEMPERANCE
	{
		sc_start(src,target,SC_CONFUSION,100,skill_lv,skill_get_time2(skill_id,skill_lv));
		
		return 10;
	}
	else if (rate < 83) // THE DEVIL
	{
		status_fix_damage(src, target, 6666, 0);
		clif_damage(src,target,tick,0,0,6666,0,DMG_NORMAL,0,false);
		sc_start(src,target,SC_INCATKRATE,100,-50,skill_get_time2(skill_id,skill_lv));
		sc_start(src,target,SC_INCMATKRATE,100,-50,skill_get_time2(skill_id,skill_lv));
		sc_start(src,target,SC_CURSE,skill_lv,100,skill_get_time2(skill_id,skill_lv));
		
		return 11;
	}
	else if (rate < 85) // THE TOWER
	{
		status_fix_damage(src, target, 4444, 0);
		clif_damage(src,target,tick,0,0,4444,0,DMG_NORMAL,0,false);
		
		return 12;
	}
	else if (rate < 90) // THE STAR
	{	
		sc_start(src,target,SC_STUN,100,skill_lv,5000);
		
		return 13;
	}
	else // THE SUN
	{
		sc_start(src,target,SC_INCATKRATE,100,-20,skill_get_time2(skill_id,skill_lv));
		sc_start(src,target,SC_INCMATKRATE,100,-20,skill_get_time2(skill_id,skill_lv));
		sc_start(src,target,SC_INCHITRATE,100,-20,skill_get_time2(skill_id,skill_lv));
		sc_start(src,target,SC_INCFLEERATE,100,-20,skill_get_time2(skill_id,skill_lv));
		sc_start(src,target,SC_INCDEFRATE,100,-20,skill_get_time2(skill_id,skill_lv));
		
		return 14;
	}
}
```

it's possible i spaghetti myself with how it's written and left a gap somewhere in the ifs, sorry im in a rush atm!i did my best to convert from disassembly to this and likely screwed up, so please double triple check before implementation.

i didnt see specifically if the sun attacked hit/flee/def but it was stated as such on irowiki so it seems accurate. this will help alleviate a lot of the painful rng involved in CG_TAROTCARD, some have higher chance effects, and some have much lower as you can see (1% on dmgs, 5% coma instead of ~7%, etc!)

**Comment by Playtester** [comment]
I see, in short, the chance is different for each card.

**Comment by mrjnumber1** [comment]
spilled my spaghetti a little sorry. when the card returned is 6, it should run `clif_specialeffect(**bl**, 522+card, AREA)`, but otherwise, it should be `clif_specialeffect(**src**, 522+card, AREA);`

**Comment by Playtester** [comment]
I tested the change on official to confirm:

After 105 cards:
15x Lovers
2x 6666 damage
2x 4444 damage
2x Wheel of Fortune

But I noticed something quite interesting too. If the "Sun" one appears the target is immune to Tarot Card. It can still be targetted but nothing happens, no card appears, there is no "skill has failed" message either (such a message usually appears if you fail the 40% chance).

So basically, confirmed.

**Comment by anacondaqq** [comment]
dear @Playtester when you will implement it, please keep option to use old mechanic behavior. I know, that need to follow official behavior bla bla bla, but please think about players too, over the years players have become accustomed to the old mechanics (even if it bugged), and they are very sharp and react negatively at any changes. So, please if someone will implement it, keep old classic eAthena / rAthena behavior in options too, either you will see a lot of bugreports and issues here and a lot of drama from different GM's.

**Comment by Playtester** [comment]
Hmmm Lovers does not actually heal me. o.o

**Comment by Playtester** [comment]
Ah, Lovers actually heals the target not the caster.

**Comment by Playtester** [comment]
I can't make it configurable, but if you want to modify the chances you can just modify `skill_tarotcard` and set the chances you want.

If you don't want SUN to make you immune to other tarot card effect you just need to remove the following code:
```c
			if (tsc && tsc->data[SC_TAROTCARD]) {
				//Target currently has the SUN tarot card effect and is immune to any other effect
				map_freeblock_unlock();
				return 0;
}
```

**Comment by anacondaqq** [comment]
nah, i don't worry about myself, thank you. I can revert your changes or make configurable tarot card option, i have worried for a lot of drama which will begin in +- 8-12 weeks (or earlier) when many server developers will implement it and start to receive "bugreports" from players 😃

**Comment by secretdataz** [comment]
That will be a drama we won't even care. It is specified in the goals of rAthena that we aims to emulate official behaviors, and we assume that our users know this fact from the start.

**Comment by anacondaqq** [comment]
> That will be a drama we won't even care. It is specified in the goals of rAthena that we aims to emulate official behaviors, and we assume that our users know this fact from the start.

You need to look for compromises and not to shout about what you do not care. RO scena very small for now, and very old. There are no new players anymore since 2010? Or earlier? Every change which breaks the usual game - kills RO, because players do not accept such changes, even if they are official, and there are no point for return for server owners because of luck options at server-side to switch back option "how it was for years", even if it wrong and not official behavior. Because server ownsers keeping players to play RO, not showing to them "official features, when 99% of all RO players were played on eAthena based emulators for 10+ years with current mechanic".

But if keeping balance between official and classic "usual eAthena behavior for players" will save a lot of players, and will resolve a lot of problems. It's called "compromise". 

Anyway, it's really sad to see that some member from rAthena developers saying: "we don't even care about critical stuff which will kick off a lot of players from servers". Nothing to say about it, it's your choice 😧

**Comment by secretdataz** [comment]
> Only those who can adapt to changes survive.

To be honest, people who like eAthena-favored RO could fork rAthena and revert official behavior fixes we have committed and maintain it if they want to 'keep RO alive' in that way.

**Comment by anacondaqq** [comment]
looks like you don't own any server ^_^ anyway, i got your point and official rathena developers point : "we won't even care". So here is nothing about to talk anymore. 🤔

**Comment by Playtester** [comment]
Emulator goal is to emulate official behavior. Server owners can modify things however they or their players want.

Making it easy to modify for server owners is okay, but it's already quite easy to modify via the source code the way it is written now (you can even put the exact percentages you want now) and a config would mean that you have to write the whole function and CASE twice, so you have a lot of redundant code. Not to mention that then you have server owners that want some of the fixes but not all, etc.
Leaving an old bugged code version in the source code just seems counterproductive in this case.

Also, not all players are like that. The Land Protector change for example was requested by kyeme who is/was a server owner and his players want everything exactly to official. A lot of other official changes (including this one actually) came from Dawn of Midgard which was a server with 1000+ players that either wanted these changes because they transferred right from iRO classic or because they thought the change would improve the WoE balance. Also if you look on popular renewal servers like NovaRO you will also find many players that are very open to change.

I grant you that for Land Protector a config would be reasonable, but then again there are tons of different ways to implement it. Not everybody just wants old eAthena behavior. Often it's so they want some of the fixes and not other. Many WoE players are for example in favour of nerfing LP so they dislike the change that even if you remove LP, the damage does not immediately return, on the other hand, they like the change that the damage can splash into LP. Then there are those that want LP to be stronger and want exactly the opposite. Some also like LP behavior with LoV and SG but don't like it with MS. Others again want official MS because it's otherwise too powerful when spamed. Or they want the timer limit to be reduced again to limit MS, but that again also affects other skills negatively.

In the end it really makes a lot more sense to let the server owners handle all these things and keep the rAthena code clean of any customizations.
