### ISSUE TITLE
Impossible cases in guild relay

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#1785]
In the guild relay quest there might be some impossible cases with the time checks:
https://github.com/rathena/rathena/blob/master/npc/quests/guildrelay.txt#L1432
```
if ((gettime(3) > 0101) && (gettime(3) < guildtime)) {
```
gettime(3) returns the hour of the day. I think we all agree that a day has 24 hours at max and not more than 101.
https://github.com/rathena/rathena/blob/master/doc/script_commands.txt#L3002

There are other similar checks in this script as well which might need to be looked into.

Another example:
https://github.com/rathena/rathena/blob/master/npc/quests/guildrelay.txt#L1459
```
if ((gettime(3) - guildtime > 0300) && (guildrelay_q == 4) && (BaseJob == Job_Blacksmith)) {
```

**Comment by mkbu95** [comment]
Looking at the AEGIS files, the global variable `ServerTime` is used. It has the format `HHMMSS`.  
The line 1432 you mentioned in the original file: 
`if (((ServerTime/100) > 0101) & ((ServerTime/100) < v[guildtime]))`  
So dividing the variable by `100` gives us `HHMM`. The interesting thing is this "method" to check for `HHMM` is only used in the guild relay quests. Everywhere else and the line of code above would've been:  
`if ((ServerTime > 010100) & (ServerTime < v[guildtime]))`  
  
This means our version has a 1 minute offset, or better yet, 59 seconds (the entire file).  
AEGIS's `guildtime` has the same type of ServerTime (whatever type that is).  
But our `guildtime` is an integer, this means in order to accommodate and check for minutes as well we would need another variable or making `guildtime` an array of int.
