### ISSUE TITLE
Hope to increase Hercules manners.txt system!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1858]
Hope to increase Hercules manners.txt system!
Thank!
https://github.com/HerculesWS/StaffPlugins/blob/master/shennetsind/manners/manners.c

**Comment by anacondaqq** [comment]
## tl;tr

First of all this is very bad place for writing suggestions about development, better to use forum for such topics, because this is very complex and hard problem at all, and it has some solutions, but it should be planned very much before implementation.

## My few cents about manner.c at server-side

This system very resource-heavy feature. That's why Gravity decide to add manner.txt to client-side and parse strings on client-side -> for avoiding extra heavy and not important at all with no sense feature at server-side. Why this feature do not have any sense? Because "bad words" can be easy falsify by adding extra spaces or replacing characters. For example: "some word string", can be writed like "s0m3 w0rd s t r1 ng". Is it readable? Yes, for saying bad words it's readable. Is it bypass your manner system above and or client-side manner.txt file? Yes, it is. So if it bypassed, why it should be implemented? This is rhetorical question. 

But problems with spammers is very big at all. I see only one benefit from the server-side system above it's because hacker can't edit his client-side manner.txt for bypassing filters via client manipulations. 
But what about performance? I think performance will be decreased. Why? Because any string manipulations in C very resource heavy operations. And manner system will have array of strings (many string at the same time which need 1 by 1 to compare with grep at real-time). Another problem it's spam and typical flood from skills like Tarot Cards. Another problem of server-side it's imagine that every object in the game (every player) input should be verified for big amount of strings in pre-defined file everytime when they enter any messages to chat. What will be happened at WoE? 

1. player A enter message
2. triggered recursion for string verification against bad words from array of words in manners.txt
3. after this operation do nothing or print something if player saying bad words.

Increase these operations in 30x or 50x. As i remember rAthena don't support multi-thread's, that means all of these operations will be added to only 1 CPU core queue. 

## deeper into the problem

It's impossible with limited resources at server-side to manipulate by players strings. Yes, there are algorithms which allow to check against even "b3d stup1d M3 GA h4Яd vv0rds l1k3 dhis", but these solutions very very very resource heavy, and used mostly in AI systems. 

The best thing how to avoid bad words or unwanted content at community it's make a system for community auto-regulations. Where people can right click on bad message and mark it as spam. If marked 3-5 players (or depends on your server-side config) then need to mute such guy for some time for all of his accounts. But this system very complicated too.

**Comment by Akkarinage** [comment]
I agree with @anacondaqq, this plugins is rather pointless and would only serve to hoard resources. Aegis doesn't have this, neither shall rA.
