### ISSUE TITLE
quests_13_1.txt OnTouch_ bug.

### ISSUE THREAD

**Issue by kukuasir1** [rathena/rathena#1878]
File:npc\quests\quests_13_1.txt
NPC:#moc2_event_on
When first time warp to the **que_dan01** map, everything is ok!
but if you don't click the **Corpse#moc2_dead01**, and wait the timeout. you will be warp out.
talk with **Mr. Kidd#ep13_dan01**, you will warp to  **que_dan01** map again.. In this time **#moc2_event_on**  's **OnTouch_** event can't be run!
if use **OnTouch**, it's ok!

**Comment by mrjnumber1** [comment]
just wanted to add that i had a similar issue with ontouch_ in the niflheim piano keys quest, because there are multiple npcs overlapping in nif_in at its pianothere might be some issues. i couldn't debug it at the time but i believe nd->touching_id might not have reset properly? i'm sorry i couldn't provide more useful information.

also make sure that on load that xspan yspan are loaded properly.
for example, in npc_add_warp ignores yspan sent
https://github.com/rathena/rathena/blob/master/src/map/npc.c#L2428-L2429

both are using xs and ignoring the ys requested

**Comment by Atemo** [comment]
Confirmed for NPC __#moc2_event_on__

**Comment by vykimo** [comment]
Confirmed Medicine Quest

**Comment by Lemongrass3110** [comment]
@Atemo you confirmed this about 1 1/2 years ago. Is this probably related to #2382?

**Comment by Atemo** [comment]
More or less. Like Tokei said, currently https://github.com/rathena/rathena/pull/2382 only affects `OnTouch` while this issue is because of `OnTouch_`

>The OnTouch_ areas and behavior have not been modified. This PR only affects OnTouch areas.

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/commit/c977558cfdc170be51e86a39d6b3426b8b3f677c should have fixed the issue.
