### ISSUE TITLE
Missing entry for 0x0A0E in packet_db

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1918]
* **rAthena Hash**: 

all since unspecified time?

* **Client Date**: 

depends on what packet, but in this example, client dated over 20140613

* **Description of Issue**: 

so here's the deal, we have in packet_db.txt lots of info, along with a default set table on packet_db_readdb. this is actually overwriting values in the hard coded packet len table!
an example of this failing is clif_bg_hp for 20140613 or more clients!

since the packet len of 0x0A0E gets overwritten by the current packet_db.txt to 0, clif_send will see that it has no len and elect not to send it, even though we know the client supports it by using explicit WFIFOHEAD/copy ing/WFIFOSET to any fd. as a result, clif_bg_hp hasn't been working for anyone who didn't explicitly set it in their packet_db.txt for a long time!

there might be other functions with side effects like this. please investigate!!!

as an unrelated aside, is it on purpose for bg hp to be updating on every damage received? it's likely that aegis sends it with bg_xy_timer similar to how party hp is updated. there is the party hp setting battle config flag currently, we could i suppose add a bg version as well. i don't have official info to know how often the bg mate hp ticker is updated, sorry.

**Comment by Lemongrass3110** [comment]
If you use WFIFOHEAD/WFIFOSET by yourself there will not be any packet that can be ignored/dropped by the server. This can only happen if you use clif_send with a prefilled buffer and a send target. There it will check for a valid packet length(-1 or > 0) or the target clients packet version to drop out invalid packets.
So this part is basically working as intended.

We try to keep the files up to date, but we also plan to overhaul this whole system, because of the redundency and other things. But this will probably not be happening before we go C++. Seems like whoever added support for that packet(too lazy to use blame now) forgot to add it to the packet db as well. If you find some more, please let us know.
