### ISSUE TITLE
Leader leaving party in instance crashes mapserver

### ISSUE THREAD

**Issue by darknessfmy** [rathena/rathena#1928]
rAthena Hash: e8b9cf0 
Client Date: Any
Server Mode: Renewal
Description of Issue:

in **customs*** Instance for partys (with generated instance), If leader of party use the command:  /leave
- Within the instance map= map server is crashed.
- Out of the instance map, but the instance created = map server is crashed.

Note: in party are 2 people (X player and leader), the "player x" are killing mobs in instance map.
**Note: if you test this with only 1 player, no cause error. Is necessary 2 or more players into party.**
*Custom Instance = 100% based in code from official instances in rA
@aleos89

**Comment by Lemongrass3110** [comment]
I just tried to reproduce it. It works perfectly fine for me.
Which instance did you use?

**Comment by aleos89** [comment]
I was also unable to reproduce using e8b9cf0.

**Comment by darknessfmy** [comment]
i change all the script... is necesary copy the total structure of other instance for this work fine.... if you use the other structure of script this cause crash in map server if player use /leave
Curious...


now show this error in map server if use @reloadscript in custom instances...
![image](https://cloud.githubusercontent.com/assets/7623682/22510646/88d2cd62-e871-11e6-9a47-d33b800226d6.png)

**Comment by sigtus** [comment]
Maybe this can be related, or not. In your script two partys can enter because you check the instance with a npc variable. That should not happen, because you register the instance in default mode (i.e. party). You should check it with the instance_id command in an NPC outside the instance (in Prontera or another place you might want to put it). You could test like that and see if it works.
Use the example here: https://raw.githubusercontent.com/rathena/rathena/master/doc/sample/instancing.txt
Regards,

**Comment by aleos89** [comment]
Please use the forum for support of your instance script. Other than that, this is working just fine.
