### ISSUE TITLE
VIP ignoring hard requirement of 1 gemstone for Hocus Pocus

### ISSUE THREAD

**Issue by Gloomi** [rathena/rathena#1975]
* **rAthena Hash**: latest

* **Client Date**: 2015-11-04

* **Server Mode**:  RE

* **Description of Issue**: VIP ignoring Hocus Pocus gemstone requirement
  * Result:  VIPs using Hocus Pocus do not consume yellow gemstone on skill use
  * Expected Result:  Hocus Pocus should has a minimum 1 gemstone requirement
  * How to Reproduce:  Enable VIP system, register char as vip, use Hocus Pocus.
  * Official Information: n/a
  

* **Modifications that may affect results**: 
  https://github.com/rathena/rathena/commit/320bf9073bb2a99e75803508e00f9f0c0c8c2a37

**Comment by aleos89** [comment]
Can you confirm on iRO if this is how it should be?

**Comment by Gloomi** [comment]
I'm not even sure if gemstone VIP feature is official. But as you said on initial release, it should mimic Mistress card.
![image](https://cloud.githubusercontent.com/assets/25794037/23128885/7bad2af2-f7bb-11e6-9ef3-9f612895378a.png)
So that's where I am basing this issue.

From : http://irowiki.org/wiki/Hocus-pocus
![image](https://cloud.githubusercontent.com/assets/25794037/23128660/ba94fa02-f7ba-11e6-8478-ee67c3a72c69.png)

Mistress card works as it should, just the VIP system not behaving like Mistress Card.

**Comment by Akkarinage** [comment]
The No-Gemstone VIP benefit was removed on iRO some time ago: http://www.playragnarok.com/gameguide/premiumservice.aspx

In all fairness, if i purchased VIP i'd expect to negate the gemstone requirement across-the-board, instead of mimicking the benefit from Mistress Card.

Besides, the benefit in the News post your ss'd says "Gemstone skill requirement removal (Works like Mistress Card)" and not "Gemstone skill requirement removal (Works the same as Mistress Card)". The same would mean negates Blue Gemstone but still adheres to other Gemstone requirements on skills in the same way that the Mistress Card provides. "Like" is just to give an idea of how the option works.
