### ISSUE TITLE
EXPLOIT BUG: Avoid ANY kind of damage by getting out of caster's screen

### ISSUE THREAD

**Issue by mmalka** [rathena/rathena#2072]
* **rAthena Hash**: 
a75133eb4d8976c1c890d5420665e7a76349e226

* **Client Date**: 

all/irrelevant

* **Server Mode**: 
both

* **Description of Issue**: 
  * Result: 

We can currently (and have been able to for a very long time it seems, without anyone thinking that was only a private server exploit) avoid ANY damage/status change as long as we get out of caster's screen between the end of damage calculation and the application of the damage or status change.

  * Expected Result:
If you see a demon pungus stone cursing you and you're not immune and you flywing away => you should arrive and continue the stone curse animation.

If you see someone casting asura strike on you and you snap away or walk away during the cast (far), you should receive the red damage calculated. Unless the spell missed due to Line of Sight breaking which is normal.

If you see a MVP casting some of the crazy spell like Earthquake, Pulse Strike, or w/e and you see that you receive  40000 damages, you should just take your 40000 damages, even if you flywing away.

  * How to Reproduce: 
Get hit by anything, fly away, move away, snap away...

  * Official Information: 
https://forums.warpportal.com/index.php?/topic/159767-question-about-snapbody-relocation/ 

* **Modifications that may affect results**: 
I have no idea about this, but on a more developper oriented statement:

Calculated damages or status change must be applied even if the target is no longer in caster's point of view. Wether it's flywing, teleport, warp, walk out, snap out, doesn't matter.

Same applies to status change that have been applied after the immunity/vit check.

The only way to dodge a damage, is to break line of sight during the cast, and it should show "MISS", not a damage calculation anyway. (You can hide during the cast of Asura and if the champion doesn't ruwach, it'll miss, that's normal)

**Comment by walkietalkie89** [comment]
https://github.com/rathena/rathena/blob/master/conf/battle/battleground.conf
```
// Should the target be able of dodging damage by snapping away to the edge of the screen?
// Official behavior is "no"
snap_dodge: no
```

what's your snap_dodge? yer / no? it should be fix if u put "no" on it.
but i'm not sure if teleport still take the dmg or not.

**Comment by TheNoobCompany** [comment]
The snap dodge is a setting for "in-screen" dodging for sure and snap never dodged an asura strike ever on official unless you double snap and break line of sight by snapping behind an obstacle so the setting itself is meaningless.

I'm talking about a bug much much much bigger than you realize that always been on pServ and never been on official.

Doesn't matter the way you get out of range of the caster, you'll dodge the damage 100% currently.

Wether you walk out, snap out, fly out, tele out, warp out.

You should always get damaged as long as the damage have been calculated (mean it didn't miss).

If you miss, you miss. If you don't, you hit.

**Comment by Playtester** [comment]
Snap dodge isn't an official mechanic. There's no max range for damage on official servers, the only thing that prevents you from taking damage is when there's an obstacle between you and the caster.

That's also how rAthena works if you set snap_dodge to "no".

**Comment by TheNoobCompany** [comment]
http://irowiki.org/wiki/Snap

Snap dodging of skills is an official mechanism, just not asura strike, please focus on the exploit bug here.

"Snapping away will save the user from area skills, but will not release them from most single-target skills, even if they have moved all the way off the screen from the attacker (unless the attacker no longer has a line of sight to the caster). An exception is that this skill can release the player from Fiber Lock."

**Comment by Paoly28** [comment]
@TheNoobCompany what you are stating was never an official mechanism

Disabling Snap Dodging will also affect everything , regardless of distance once a skill is casted it will follow the target unless the skill casted has limited range.

**Comment by Playtester** [comment]
I assume what he means is this:
```
dat->distance = distance_bl(src, target) + (battle_config.snap_dodge ? 10 : AREA_SIZE);
```
If you are hit and there is a damage delay, then the damage is only deals if you haven't moved away more than 10 cells with snap_dodge or more than AREA_SIZE (14?) cells without snap_dodge.

I guess that could really be considered a but because instead of AREA_SIZE it probably should be the whole map size.

The impact should be small, though, because if you flywing, the chance there's an obstacle between you and the caster is actually pretty high and I can't imagine any other way to get more than 14 cells away during damage delay.

As not all skills go through this part, a report saying that "everything is wrong" isn't so helpful. Might be better to look at specific situations.

**Comment by TheNoobCompany** [comment]
I understand doing LoS check map-wide is not the best cputime you expect but...

=> If it did hit, it means there was no LoS issues at the time => "damages" is displayed.
=> if it didn't hit due to LoS check (or fly during cast => Damage is "miss" anyway.

The difference is quite important.

To go into your direction:
If you cast a spell on me, and I use flywing during the cast, it has huge chance of "missing" if I break LoS (or if you assume a certain distance where it'll miss due to high probablity of having an obstacle).

But if I use flywing AFTER the spell has started/damages have been calculated, the LoS check already been done, no ?

**Comment by TheNoobCompany** [comment]
I'm closing this as you don't seem to want to fix that.

**Comment by cydh** [comment]
so there's opened issue like this.
I don't test much on rAthena. but after playing back on official server I can tell this issue is valid.

The most skill I experienced is the Bash skill from Anolian, it has cast time, and yes it's melee. I always try to run when Anolian start the cast, but just getting out of range I still can received the damage, except what I do is teleporting away.

as well, that stone curse case (or maybe other statuses too) even teleport before the cast done, once I spawned I still get the status.

and the exploit on official is, when u just received damage then teleport right-after damage received (say before 1 sec) the damage is canceled, but u still got the red-damage number and log in battle/damage log.

**Comment by mmalka** [comment]
I've been pinged but I don't see any message.
![image](https://user-images.githubusercontent.com/1161961/117832607-e9e5c780-b275-11eb-9d71-fa2b5e496f38.png)


Anyway, good time for a little bump anyway. Hello 2017, this is 2021 !

**Comment by secretdataz** [comment]
Since I've started playing on official server (kRO) again. I'll list my first-hand test results here.

- Monster attacks are dodge-able with Fly Wing, if timed correctly.  
- You can Fly Wing reflected damage, if timed correctly.

**Comment by Playtester** [comment]
As I said before, on offiicial servers it only matters if there's an obstacle between the caster and the target, there's no maximum range it can still hit. But if you teleport there's a high chance there will be an obstacle between you can the caster.
