### ISSUE TITLE
Skill Tetra Vortex doesn't work when cast by a monster

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#2128]
rAthena Hash: 4a004ad
Client Date: 2017-01-25RagexeRE
Server Mode: Renewall

**Description of Issue**: Skill Tetra Vortex doesn't work in a mob

**Result**: When a monster cast the skill Tetra Vortex in any target, nothing happens. Apparently the skill fails.

**How to Reproduce**: Summon a monster like Fenrir (2564) and wait for it cast the skill on yourself.

**Comment by aleos89** [comment]
It's failing because of this check:
```c
	case WL_TETRAVORTEX:
		if( sd && sc ) { // No SC? No spheres
```
Does the mob require the spheres to cast? How does it determine which type (fire, earth, etc)? Does it just pick at random for monsters?

**Comment by Felleonel** [comment]
Spheres, in the case of Fenrir, isn't necessary. And about type, I don't know how to identify which type is. If can help, there are some videos from iRO that Fenrir hits the skill.

https://youtu.be/owKfy9BlQ1o?t=57
https://youtu.be/cPNX2IzooD0?t=368
https://youtu.be/e0ep6YmpaK8?t=641
https://youtu.be/UHqmzhB_VYk?t=457
https://youtu.be/784xQunqQhc?t=403

**Comment by qwerty7vp** [comment]
I tested and Mob's Tetra still failing
does this issue fixed ? or am I miss something ?
@aleos89 fyi
It works by hitting the target 4 hits, Neutral element, No sphere required

**Comment by mrjnumber1** [comment]
Well. It's quite strange, from what I've determined in the zone.
Tetra Vortex for players and npc tetra vortex is different. PC tetra vortex looks fine in our code (although the times should be the default times on burning/stune/freezing/bleeding, instead of our hard coded numbers)

in 15.2 zone, it apparently works as such
first, matk% is 2000 * skLevel + 500 (so skillratio += 400 + 2000* skill_lv)

1. WL_TETRAVORTEX_FIRE at Neutral
2. WL_TETRAVORTEX_WIND at Earth
3. WL_TETRAVORTEX_WATER at Water
4. WL_TETRAVORTEX_GROUND at Fire
5. Randomly use, without doing any damage, WL_TETRAVORTEX_FIRE/WATER/WIND/GROUND+ their given effect (burning/freezing/bleeding/stun)

seems really weird. oh well, thats what i get from it.

**Comment by qwerty7vp** [comment]
hello, @aleos89 this issue is good to go ?
or still need more info
