### ISSUE TITLE
False Duplication of Items.

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2143]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/79ad0a1902009b7509e0b2a97ecb2571fd0af6f1

* **Client Date**: 2015-11-04 | 2016-02-03 | 2016-12-28 | 2017-01-28 | 2017-03-15

* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: It is possible for you to non-realistically duplicate your character's inventory items by using @refresh during a negotiation, and then canceling it.
  * Expected Result: Let this not happen.
  * How to Reproduce: 
1 - Start a negotiation between 2 characters.
2 - Place an item in the trading with character 'A'.
3 - The character 'B' clicks on 'ok' in the negotiation, but the character 'A' does not click on 'ok' and uses the command '@refresh', after that the character 'B' cancels the negotiation and the character item will appear Double.
* **Prints:**:
Img: http://imgur.com/A75I0Gr
Img: http://imgur.com/ecBuut4

**Comment by RadianFord** [comment]
I can confirm this using 2015-05-13 client which is weird because you cant drop it you just need to relog to fixed the issue. I think both PRE / RENEWAL is affected by this.

**Comment by Jeybla** [comment]
I can confirm it, too. `@refresh` refreshes the screen of player A, but does not display the ongoing trade again. Since the item still belongs to player A, the item is displayed in the inventory even though it's actually (hidden) in the trade window. When player B closes the trade, there is just a visible effect shown to player A for getting the item.
After a second `@refresh` the correct number will be displayed.

Because it's just a visible bug, I'll give it a low priority. Simple solution I'd suggest would be to close ongoing trades on `@refresh`.

**Comment by admkakaroto** [comment]
@Jeybla Is it possible to use the items in npc's? If it is can be a problem.

**Comment by secretdataz** [comment]
@admkakaroto Visual bug = only client sees it
