### ISSUE TITLE
Adding a player to party with fake name

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/rathena#2145]
rAthena Hash: a3282c1
Client Date: 2015-11-04aRagexe
Server Mode:
Renewal

Description of Issue:

Result: 
We have a system that gives out fake names as a title. Example Captain "players name" when adding a player to the party by right click and invite its says player is not found. But if you open the party window and add the player name without the title then you are able to add them to party. 
Expected Result: 
Since its a "Fake name" it shouldn't be considered when right clicking and adding player to party. It should add player to party based on the char real name.
Official Information:
N/A
Modifications that may affect results:
no mods just enable fake name on a player and try to add them to party with right click.

**Comment by Lemongrass3110** [comment]
The problem with this is that the client only sends the name of the target player to the server.

As you might know the fakename is not checked for uniqueness, so if I have player A called Lemongrass player B can also use fakename to call himself Lemongrass.

But if you send a party request to player B now, player A will receive it.
If the target character name is not online at all you will end up with your scenario and getting the error message, that the target player is not online at all.

This is nothing that can be fixed completely from our side, since it will just cause another issue in the future if we fix this now.
As for your feature I would like to refer you to pull request #2044 which includes the title system, which actually does something similar like what you are implementing through fakename right now.

**Comment by Jeybla** [comment]
Thanks for the detailed clarification. Closed.
