### ISSUE TITLE
command npcskilleffect show no effect on most skill

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2156]
* **rAthena Hash**: Latest

* **Client Date**: -

* **Server Mode**: -

* **Description of Issue**: 
  * Result: The command didn't show effect on coordinate on most skill.
  * Expected Result:  It should be work just like how the document said.
  * How to Reproduce: Just loop the skill id in the skillid parameter to see the result.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by jezznar** [comment]
can you please provide an excerpt of your script?

**Comment by Lemongrass3110** [comment]
The packet behind that script command is ZC_NOTIFY_GROUNDSKILL which is used for non-damaging ground skill effects. This prevents all skills that do not fall into that kind of category to be rendered of course.

The script documentation is wrong in this case, because it states that it behaves just like 'skilleffect', which does not use x and y coordinates and uses another packet(ZC_USE_SKILL), which is used for all kind of non-damaging skill effects.

So I guess both of them might need additional checks to call the correct clif functions.

**Comment by ignizh** [comment]
Still broken, don't work with any skills (tested non agresive and agresive ground/not ground types)
