### ISSUE TITLE
Feint Bomb Bug

### ISSUE THREAD

**Issue by ilovelemon** [rathena/rathena#2163]
* **rAthena Hash**: I really do not know where I can see this. But my Git was downloaded on 04-25-2017

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Monsters follow the Shadow Chaser even when the hiding status of the Feint Bomb is active. However, Demon, Insect, and Boss monsters do not follow when the hiding status is active.
  * Expected Result: ALL monsters, regardless of race, should not follow the Shadow Chaser when the hiding status of the Feint Bomb is active.
  * How to Reproduce: 
  * Official Information: When the user hides at the end of casting this skill, monsters will not follow the user, but remain fixated on the afterimage. Demon, Insect and Boss monsters will also remain in place and do not chase after the user once he/she has hidden after drawing the copycat. (http://irowiki.org/wiki/Feint_Bomb). Confirmed by Playtester in the rAthena forums (https://rathena.org/board/topic/111056-feint-bomb-question/)
  

* **Modifications that may affect results**: None

**Comment by Jeybla** [comment]
This bug is likely caused by changing the OPTION_INVISIBLE to ` #define pc_isinvisible(sd)    ( (sd)->sc.option&OPTION_INVISIBLE && !((sd)->sc.data && (sd)->sc.data[SC__FEINTBOMB]) ) `.

`OPTION_INVISIBLE` is often checked directly instead of using `pc_isinvisible`.
Example:
```C
map/clif.c:	if(bl->type == BL_NPC && !((TBL_NPC*)bl)->chat_id && (((TBL_NPC*)bl)->sc.option&OPTION_INVISIBLE))
```

So currently every monster with `MD_DETECTOR` may see the feint bomb user.

I'll check it in detail.
