### ISSUE TITLE
Marriage/Adopt share EXP

### ISSUE THREAD

**Issue by feltenc** [rathena/rathena#2265]
* **rAthena Hash**: b2aa7e698da55bcae198dfcda7ab706f35d958e3

* **Client Date**: 2017-01-25RagexeRE

* **Server Mode**: Renewall

* **Description of Issue**: A family Can not share the experience with the baby lower level.

  * Result: Can't share EXP.

  * Expected Result: The child will be able to share with either (or both) of their Parents at any given level, as long as the Parents are both 70+. This makes leeching from 1/1 to 175/60 possible. All members of the family must be on the same map to set party share.

  * How to Reproduce: Marry with another player, adopt a baby, increase your level to max or something higher than the baby, try to share EXP.

  * Official Information: http://irowiki.org/wiki/Adoption_System#Benefits_of_being_Adopted

* **Modifications that may affect results**: None

**Comment by Lemongrass3110** [comment]
int_party.c::party_check_exp_share is at fault here.
Since this is checked in the inter-server we might need to save the party prior to changing the share option, since the check does need to know if they all are on the same map.
Additionally the party information does not contain any information about being married or adopted at all right now.

**Comment by feltenc** [comment]
New information: We can't share xp with both parents on the group. There can be only either the mother or the father, not both. Thats correct? Maybe someone can confirm it for us?
