### ISSUE TITLE
logmes attached player requirement

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#2268]
* **rAthena Hash**: d324cd1e255367a8ec3654167b90062e6c07c80f

* **Client Date**: Irrelevant

* **Server Mode**: Irrelevant

* **Description of Issue**: Script command `logmes` requires an attached player. For cases where NPCs are using logmes on timers (for scripts that use OnHour00 midnight resets, for example) this will throw an error. NPCs that use `logmes` to record various actions shouldn't need to have a player attached. This should be optional at the very least.

* **Modifications that may affect results**: None

**Comment by vstumpf** [comment]
The table for `logmes` has fields for the character invoking the command, like account/character ids, character name, and the current map of the character. We could ignore the ids, put the NPC name/map instead of the character, but that would make the column name meaningless. It would also require changing the length of the character name column to 50 to accommodate the NPC names.

Alternatively, you can make a new table in the logs database: however, naming it might be problematic as `npclog` is already taken.

**Comment by Lemongrass3110** [comment]
How about adding a config to allow storing "debugmes" into a table?
Debugmes can be used without any player right now.

**Comment by Akkarinage** [comment]
Either/or. If we can log debugmes to npclog I'll be a happy Akky.
