### ISSUE TITLE
20141022 Client can't receive 0xa07 to 0xa0d packets

### ISSUE THREAD

**Issue by Milchdealer** [rathena/rathena#2283]
* **rAthena Hash**: 

eda8594

* **Client Date**: 

20141022

* **Server Mode**: 

Pre-RE

* **Description of Issue**: 
  * Result: 20141022 Clients can't pick up items and miss some basic packets.
  * Expected Result: 0x0a07 to 0x0a0d are available for 20141022 clients.
  * How to Reproduce: 
  * Official Information:

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Sorry but your issue is invalid.
Everything is working as expected with 2014-10-22.
Picking up items and dropping items.

If I enable 0xa0d in this client the inventory is messed up badly.
0xa07 is a RODEX packet and was still under development back then and not even available publically.

I guess you based your info on hercules(https://github.com/HerculesWS/Hercules/blob/master/src/map/packets.h#L3180) where this is also wrong, but was probably automatically generated by @4144. Totally understandable that he cannot test each client though.

Your pull request also does not handle anything related to what you are writing here. You only adjusted some 2015 dates.

If I got something wrong please let me know.
