### ISSUE TITLE
item_db incorrect for item 1443 - Crimson_Spear

### ISSUE THREAD

**Issue by ToiletMaster** [rathena/rathena#2297]
* **rAthena Hash**: 

* **Client Date**:  2017-01-25

* **Server Mode**: Renewal

* **Description of Issue**: Item DB wrong information
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: None
  
  

Hi there, i noticed another incorrect item_db.txt configuration for this item. 

1443 - crimson spear. This spear according to iRO wiki, http://db.irowiki.org/db/item-info/1434/ is equippable by all swordman classes. However within the item_db.txt

`1443,Crimson_Spear,Crimson Spear,5,20,,900,90,,3,2,0x00004082,56,2,2,3,70,1,4,{ .@r = getrefine(); bonus bBaseAtk,((BaseLevel/10)*5)+(.@r<=15?pow(.@r,2):225); },{},{}
`
notice that the class is 56 only which allows 3rd job to do it.  Therefore the right one should be 63 instead. 

`
1443,Crimson_Spear,Crimson Spear,5,20,,900,90,,3,2,0x00004082,63,2,2,3,70,1,4,{ .@r = getrefine(); bonus bBaseAtk,((BaseLevel/10)*5)+(.@r<=15?pow(.@r,2):225); },{},{}
`

**Comment by ToiletMaster** [comment]
1 question if you don't mind me asking here, as I move along to test random monsters for their items and drops. Would it easier for the raise this as an issue? Or would it be better if I raised a PR for future edits? Sorry if this has been asked multiple times as I'm fairly new to GitHub.

**Comment by Jeybla** [comment]
It depends. If you already apply and test the changes, the best way is to provide a PR, so we can easily merge it with a click :)
Issues are really good to discuss things. As for database edits we mostly rely on the informations of https://divine-pride.net/ (preferably with another source). So it's very nice if you also link to the site/sources your edits rely on. Anyway, thanks for contributing!

Back to topic - your issue seems correct:
https://www.divine-pride.net/database/item/1443/crimson-spear-2
`Required Level: 70
Required Job: Swordman Jobs`

**Comment by ToiletMaster** [comment]
Thanks! I've been using iRO db for the time being to verify the changes, Wasn't exactly aware of the divine pride. I'll refer it from there the next time. 

I'll do a pull request next time to help out so it's easier for you guys to make the changes in. Thank you very much and keep up the great work!
