### ISSUE TITLE
@whereis missing after @reloadmobdb

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2360]
* **rAthena Hash**: 6f985080a8b071e5869679e430274a4b166971c2

* **Client Date**: 2015-11-04aRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
`@whereis` not showing spawn location after `@reloadmobdb`
  * Result: 
`@whereis` not showing spawn location after `@reloadmobdb`
  * Expected Result: 
`@reloadmobdb` should not affect shown spawn on `@whereis`
  * How to Reproduce: 
1. do command `@reloadmobdb`
2. command `@whereis` after that will show "Monster does not spawn normally' on all monster.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
[img]http://i.imgur.com/XzwQPJN.png[/img]

It's working to me...

**Comment by uddevil** [comment]
is it after `@reloadmobdb` ? and what hash did you use?

**Comment by Zellukas** [comment]
Maybe is better reverse the last changes in reloading mob db until the devs check if every thing is good.

**Comment by aleos89** [comment]
This is because the `mob_db` struct that stores the spawn information is cleared out on the reload process now. It is filled when parsing monster spawn files which doesn't happen as it's a script file. If you do `@reloadmobdb` and `@reloadscript` it should refill that information.

**Comment by keitenai** [comment]
@whereis will work again after using @reloadmobdb if you use @reloadscript

**Comment by reunite-ro** [comment]
ive encounter this issue before, after i git pull, its already fixed

**Comment by CodexRegius** [comment]
I confirm, each time we perform @reloadmobdb the command @whereis does not indicate spawn location anymore. Because of Happy Sunday (Exp x2), we have to do @reloadmobdb. Consequently we have to relaunch scripts each week because of this problem … It’s becoming really unconfortable for everyone … . Please does someone got an idea in order to solve this problem, because we tried a lot of things to solve it, but it’s still unsuccessful

I thank you in advance
