### ISSUE TITLE
Migrate login server completely to C++

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#2478]
* **rAthena Hash**: 872cb42a480b2f52731b7bc8d7ff889db00b5cc0

As most of you already know, we are currently slowly shifting into complete C++ support. Step by step we're migrating map-server parts into C++ and it's foreseeable to migrate the map-server completely to C++ soon.

But before we actually use C++ features map-server wide I'd like to do some less important tests by migrating the login-server first. I don't want us to run into complicated issues with the map server, when we're able to test it on a less important and less big project like the login server.

Things to do (test):
- [x] Convert files to C++ format. (a587b91)
- [ ] Migrate login server to C++ completely
- [ ] Refactor some code in C++ and document benefits and issues
- [ ] Leave it for a while in the repository and wait for some user issues
- [ ] Eventually write a small plugin system for testing purposes (?)

After these test, we'll have a smother and more confident switch for the main (map-server) project.

**Comment by sader1992** [comment]
plugins  ![smile](https://user-images.githubusercontent.com/5981261/31258801-117031a4-aa42-11e7-9710-ddcf303c5753.jpg)

**Comment by Jeybla** [comment]
To clarify this: We are still far away from having plugins. And we should not go for a quick and bad solution. Please don't expect plugins in near future from us.

**Comment by lighta** [comment]
@Jeybla, dunno if you already have check but I did convert all those module back then. you can found it there : https://github.com/lighta/rathena/tree/refactor/rA-cpp-linux-test
It's probably a bit outdated, altough I doubt char and login serv have change that much.

**Comment by Jeybla** [comment]
Oh great, didn't know that! Looks really good.

The current plan was to slowly convert the map-server step by step. Examples:
https://github.com/rathena/rathena/pull/2435
https://github.com/rathena/rathena/pull/2466

But we are currently not able to use C++ features project wide (for example classes in header files). I just wondered when we are actually able to do that and which issues we may encounter. That's why I wanted to simulate it on the login-server. I'm not sure if we'll get the same "simulation effect" if we're using your code.

Maybe it'd be better to convert everything in a big coding session (one weekend with 2-4 developers involved). It also may be good to train our selfs to get on a equal level in C++ before we'll do that.

One thing is sure: We should concentrate first on making rathena compile-able and (nearly) bug-free in C++, before we refactor or reimplement things. We need to work with our community, because they will already hate us for having a massive amount of merge conflicts :D

As you can see, I'm pretty unsure about how to handle the migration correctly. @secretdataz is the man with the knowledge :P 
Actually I'd like to talk about that in detail soon in the staff chat. I hope we'll see you there :)

**Comment by lighta** [comment]
Just tryed my branch on windows. seem to work fine except a little dealloc on server finish for login, but is not that critical.
Step by step map-server. fine that a good plan. This is basically what I had done. all the module was converted in a basic c++ then I was starting to refactor more deeply.
I prefer starting over login and char server as the y were less critical then mapserv and allow me to see what issue we may encounter when doing the map-serv so this one could be done faster and with less issues.
For instance we currently use DB_MAP and StringBuf wich are just std::map (or unordoned) and std::string, there no real point converting thoses or take too much time convert a code using those instead just replacing them. or typedef a struct... speaking of wich I did rename lot of struct because their definition was confusing with their typedef.
The convertion itself isn't that hard, testing is a little more since it seem we still have no tests available to ensure all is working correctly.
Right now I was starting to introduce concurency in the various server since they do not use all the thread available.

NB : I didn't get your "not able to use C++ features project wide". C++ code can use C code / library but the other way arround is not possible. Is this what you meant ?

**Comment by Jeybla** [comment]
`I didn't get your "not able to use C++ features project wide". C++ code can use C code / library but the other way arround is not possible. Is this what you meant ?`
Exactly that is what I meant

**Comment by Lemongrass3110** [comment]
All servers, mapcache and common are already C++ now.
