### ISSUE TITLE
@autoloot XX (Renewal Mode)

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2540]
* **rAthena Hash**: c7d5b61

* **Client Date**: 2017-01-25

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Item doesn't go to inventory automatically where it is supposed to work.
  * Expected Result: Item should be added in the inventory after killing mobs
  * How to Reproduce: (This is how I reproduced it - Specific Item)
1. Renewal Mode On and Enable Renewal Drop
2. Be a ranger at level 100. 
3. Use `@autoloot 30`
4. Items below 30% drop rate looted normally. (Elven Bow at 25% Drop Rate (using `@mi Gargoyle`) since Base Level is 100)
5. Be a ranger at level 140
6. Remove `@autoloot` or use `@autoloot 20`
7. Elven Bow isn't added directly to the inventory instead you will have to pick it up. (Elven Bow drop rate now at 15% due to renewal drop system)
8. Finish Simulation

  * Official Information: Official command documents
  

* **Modifications that may affect results**: None

**Comment by Jeybla** [comment]
I actually think this is more an enhancement, than a bug.
Current configuration is simply to use the database drop chance for autoloot.

Possibly other configurations:
* Include Renewal drop penalty (what this issue is about)
* Include all drop bonus/penalties

This could become quite confusing, so we should keep the current behavior as the default behavior.
