### ISSUE TITLE
Old Script Is Hackable?

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2557]
* **rAthena Hash**: 09519f3

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: we all know this script was developed eathena more than 10 years ago. arena_room.txt and arena_point.txt rathena itself was 2 years ago. is this probably outdated?

![001](https://user-images.githubusercontent.com/8316103/32178947-ac6e49ca-bdc0-11e7-936e-1a554b0e1ce7.PNG)
![002](https://user-images.githubusercontent.com/8316103/32178948-acb474d6-bdc0-11e7-8773-41fa3c4fab3b.PNG)

  * Result:  People can get old card album on prt_are_in 98 14 then the point arena is negative please check attachment.. this people get 1700 old card album with point arena negative -1700000
  * Expected Result:  people cannot get old card album on prt_are_in 98 14 prevent from negative point arena
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
This would only be possible if you set input_min_value in conf\script_athena.conf to some negative value or specify the minimum explicitly(which is not done in this script).

script_commands.txt
```
Normally you may not input a negative number with this command.
This is done to prevent exploits in badly written scripts, which would
let people, for example, put negative amounts of Zeny into a bank script and
receive free Zeny as a result.
```

Reward function from the script:
```
function	script	Func_Are_Rew	{
	.@item_id = getarg(0);
	.@amount = getarg(1);
	.@arena_point = getarg(2);

	mes "[Givu]";
	mes "Would you like to exchange your arena points with "+ getitemname(.@item_id) +"?";
	mes "You can exchange ^3131FF"+ .@arena_point +" arena points with "+ .@amount +" "+ getitemname(.@item_id) +"^000000.";
	mes "If you wish to cancel, please enter 0. If you don't, please enter how many ^3131FFtimes^000000 of arena points you wish to spend.";
	next;
	input .@reward;
	if (.@reward == 0) {
		mes "[Givu]";
		mes "You have canceled your request.";
		close;
	} else if (.@reward > 1500) {
		mes "[Givu]";
		mes "You have exceeded the maximum capacity.";
		close;
	}
	if (arena_point < .@reward * .@arena_point) {
		mes "[Givu]";
		mes "You do not have enough arena points.";
		mes "Please check the total amount of arena points you have.";
		close;
	}
	arena_point = arena_point - (.@reward * .@arena_point);
	getitem .@item_id,.@reward * .@amount;
	mes "[Givu]";
	mes "Thank you, please come again.";
	close;
}
```

**Comment by mazvi** [comment]
yes, but why this person can do that.. this person can also get free hundred oridecon exchange on payon .. i'm researching what he did.

**Comment by Lemongrass3110** [comment]
Hmm well it certainly is strange, but as you can see here:

https://github.com/rathena/rathena/blob/master/src/map/script.cpp#L6159
`set_reg(st, sd, uid, name, (void*)__64BPRTSIZE(cap_value(amount,min,max)), script_getref(st,2));`

The value should be capped and should be between min and max, even if the player inputs a negative value with opencore or something similar.

If you find anything useful let us know. Probably PM us on discord or tell it to @cydh though, since we do not know how dangerous the problem you will find will be.

**Comment by mazvi** [comment]
Okay thanks very much, i will send PM if i found something... whether to close this issue?

**Comment by Lemongrass3110** [comment]
Since you are still researching we can leave it open for now. I will add the waiting for user input label in the meantime. If you do not find anything we can close it in 14 days.

**Comment by cydh** [comment]
try debug with
```Diff
diff --git a/src/map/script.cpp b/src/map/script.cpp
index 4d5d968..ee78ac6 100644
--- a/src/map/script.cpp
+++ b/src/map/script.cpp
@@ -6157,6 +6157,7 @@ BUILDIN_FUNC(input)
 		{
 			int amount = sd->npc_amount;
 			set_reg(st, sd, uid, name, (void*)__64BPRTSIZE(cap_value(amount,min,max)), script_getref(st,2));
+			ShowDebug("input: [%s] amount:%" PRId64 " min:%" PRId64 " max:%" PRId64 " (%" PRIu32 "/%" PRIu32 ")\n", name, amount, min, max, sd->status.account_id, sd->status.char_id);
 			script_pushint(st, (amount > max ? 1 : amount < min ? -1 : 0));
 		}
 		st->state = RUN;
```

**Comment by mazvi** [comment]
okay, where will this debug log will be stored? does that also apply to other NPCs? like oridecon exchange?

**Comment by vstumpf** [comment]
it just prints it to the console, or wherever you have stdout redirected to.
It prints anytime the `input` command is used.

**Comment by mazvi** [comment]
i saw video on https://www.youtube.com/watch?v=DuGEUOm--5c the player hack donation item, using method talk to other NPC with auto NPC talk.. i think this is potential bug...

my server got this after sell kafra card, people can talk to NPC then open kafra card, i think this is potential bypass NPC script to get item...

from my screenshot player not input negative value, but the got old card album with bypass arena point, so arena point will be negative...

**Comment by rpdigos** [comment]
Abou the exploit presented in the video, probably the problem is that the script is badly written. I've seen that happening before with a donation script which use the variable @menu to index the callshop.
So, the player talks to another npc to change the value of the @menu variable bypassing the validations (actually calling other callshop instead of the correct one).

**Comment by Jeybla** [comment]
Please let's not mix everything. The video isn't really helpful without the information which NPCs he used.  
@rpdigos I don't think it's a side effect because of a char variable. If it's the rathena Platinum Skill NPC, the whole script is just like:
```C
	mes "[Platinum Skill NPC]";
	mes "I can give you the special skills available to your job.";
	mes "Would you like these skills now?";
	next;
	if (select("Yes Please:No") == 2) {
		mes "[Platinum Skill NPC]";
		mes "Have a nice day... >.>";
		close;
	}
// [...] rest is irrelevant
```
So there's no `@menu` variable (same goes for the hercules platinum NPC). It possibly is just a bug in the `callshop` script command. This needs to be tested; best with the actual `Donation NPC` from the video. (Can someone find that script?)

**But further on, please let us just focus on that issue. Just open another issue for everything else (like the youtube video).**

---

For the reward script, we should definitely add a negative check in there. Even though, it shouldn't be exploitable when the `input_min_value`config hasn't been changed:
```C
	if (.@reward <= 0) {
		mes "[Givu]";
		mes "You have canceled your request.";
		close;
// [...]
```
I'll have a look for possibly other exploits with that value. Anyway good catch @mazvi and thanks for opening the issue.

**Comment by technoken** [comment]
About that youtube video, someone mentioned it to me before and I told him to just use the rA's quest_shop without me looking on about the info. After reading this issue I tried to went back to our convo and if i'm not mistaken he was using this script https://rathena.org/board/topic/53320-%E3%80%90-emistry-%C2%A9-2015-%E3%80%91e-scripts-collection/?page=2&tab=comments#comment-70657 by @Emistry 

Looks like it was an outdated script but haven't test it out yet myself due to my very limited time, but I was thinking this might be a little help.

**Comment by secretdataz** [comment]
Can't reproduce using the same steps as @mazvi's video and the script @technoken linked.

**Comment by Jeybla** [comment]
Oh, I didn't know `@menu` is set automatically... Well, @rpdigos was right then; good catch! The script shouldn't use `@menu` when you're able to use other NPCs during the buy process.

**Comment by secretdataz** [comment]
imo the `@menu` is now an unneeded feature and should be removed.
The player's selection (select's return value) can be stored in a variable.
To discuss this we should open another issue to not sidetrack this issue.

**Comment by anacondaqq** [comment]
> imo the @menu is now an unneeded feature and should be removed.
Don't touch `@menu` and `select`.

**Comment by secretdataz** [comment]
@anacondaqq I’d love to hear your reason

**Comment by anacondaqq** [comment]
For around 12 years this very useful extension with temp char-based var was in the select command, thousands of scripts which using this var have been written, and now you came here and decide "Let's remove it". 

Is information about `select` and `@menu` present at docs? Is it used in scripts? Yes. Actively. Is the feature help to write good scripts? Yes, for many dynamic menus, and different menus. How? By minimizing tons of stupid checks for vars where is required character based var which will be flushed when a player session will end, but while he is online, the var must be used for NPC. (i don't talk yet about scope vars like `.@` and so on). 

I'm too lazy to show examples, but if will be any drama, I can show real examples of code why it the `@menu` var is important. 

And removing such useful things which exist for years, just because someone maybe was tired and did very small mistake -> not looks good at all.

Here is ~400 reasons: http://bfy.tw/Ev1c + extra 100 reasons http://bfy.tw/Ev3E,  and extra 200 reasons: http://bfy.tw/Ev3H
And around 50-60 reasons already in the code. And I do not talk about hundreds of custom scripts
Yes, you can rewrite them by using switch/case, but for what? Are these scripts work? Why is the need to touch things which just works fine? For what to make extra work, while there is tons of other more interesting things to do? Like for example fixing bugs?)

And the last and most important thing for me: - why should I prove and convince you of anything like this basic and simple stuff? Is it really not clear that you do not need to touch things that work for years irreproachably? If you want to delete something - just argue this as best as possible, and do not kill the emulator and its compatibility. If you are so trying to increase the flow of orders by rewriting the NPC - then good luck to you. I'm not worried about myself, I can restore this function that you do planning remove, I'm worried about newbies, which will not be able to use other scripts and will have millions of bugs with old scripts. And the most problematic thing, that they will not be able even to understand what was happened because `@menu` will be always 0. If it's your plan and business model, it's ok, it will explain everything for me (real motivation), if not, then it looks strange, because of one small typo, decided an action to remove functionality, and not fixing the bug in the script. 

Anyway, you can ignore my comment, and do as you wish, there is no problems or negative at all. 
Cheers ❤️

**Comment by Lemongrass3110** [comment]
Closing this since it is a user script fault.

@anacondaqq could you be so kind and repost your comment on the new issue? Thank you.
