### ISSUE TITLE
EnterSpinLock can cause deadlock with main thread

### ISSUE THREAD

**Issue by Encon21** [rathena/rathena#2591]
* **rAthena Hash**: 6decf6c

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Pretty niche use case here, but I'm working on setting up a second worker thread and came across a deadlock. EnterSpinLock() uses the thread ID to check which thread owns a lock; this is fine, except that the main thread defaults to thread ID 0. EnterSpinLock() will assume this means the lock is free, allow another thread to take ownership and increment lock->nest to 2, and when the main thread exits won't decrement the nest count (because another thread now owns the lock). After the second thread exits, nest is decremented to 1 (instead of 0), the lock isn't freed, and no other thread can enter the spin lock, causing a dead lock. I think that's the most confusing paragraph I've ever written.
  * Result: Main thread fails to take ownership of the spin lock correctly, causes a deadlock if another thread enters the spin lock before the main thread exits. 
  * Expected Result: Main thread takes ownership of the spin lock and other threads are forced to wait.
  * How to Reproduce: Start a second thread, enter spin lock on the main thread, and before the main thread exits, enter the same spin lock on the second thread. Exit from the main thread, then the second thread. The main thread will deadlock if it tries to enter the spin lock again. 
  * Official Information: N/A 
  

* **Modifications that may affect results**: 
  
  
The second worker thread is a modification of course, but if rAthena is updated to take advantage of threading in the future (for example putting log queries on a separate thread), this would likely cause issues. Figured I'd put this here so it can be resolved instead of causing possible issues/confusion later when it gets used.

To fix it, in rathread_init() change the main thread to thread ID 1, and adjust l_threads[].myID to i+1. rathread_self() needs to be adjusted as well to use the correct l_threads[] index (g_rathread_ID-1). As far as I'm aware this should be all that's necessary.

As an aside, this only happens if HAS_TLS is defined, though given the fact that attempting to compile without it causes compilation errors, I'm assuming it's never not defined.

**Comment by Jeybla** [comment]
We just talked about thread safety yesterday. Yes it's definitely a thing we could work to, but currently it would be a really big work, since not a single thing is implemented with thread safety in mind.

I think you can rename your issue in `Implement thread safety` we'll take some time to do it, but if we keep it in mind during some C++ refactorizations it could become a good feature. Thanks for mentioning it.

**Comment by Encon21** [comment]
There actually seems to be code already included in rAthena's codebase with threading in mind (thread.c, spinlock.h, etc), though unless I'm mistaken it appears to currently be unused outside of extremely old experimental defines. In my current testing the code does seem to work fine so far after fixing this bug, though.

Of course, actually taking advantage of threading would be a big move, but the main concern here was that others may see that these functions are included and try to use them, or they may be used in future development, so I thought since it's a fairly quick tweak (just incrementing the thread IDs by 1) it'd be worth fixing it now.

**Comment by lighta** [comment]
@Encon21 thanks for the notification, you could do a pull request if you want it to be integrated.

The current implementation is fine but new devellopement will mainly be in c++ so it will be easier for us to use std::recursive_mutex or boost::timed_mutex or std::atomic<> and etc... instead of reimplementing those. (spinlock is fine for short wait but not really for long one).
I think will probably keep common as a old library tough so it may worth fixing but not much code use that threading feature. currently only sql query as I remenber.

For the issue itself, HAS_TLS may not be defined by some compiler or architecture. it seem only enable by default if we compile on windows (in our code).
I should really replace __thread keyword with thread_local to be more compliant. 
But otherwise I would have replace InterlockedCompareExchange etc to compare to -1 instead changing the threadsID. (cause juging from thread.c not initialized was meant to be -1)

**Comment by Encon21** [comment]
I think configure sets HAS_TLS on other systems as well. There's a typo in the non-TLS code that would prevent it from compiling otherwise (may be other bugs in it too, I only tested a single compile attempt).

It's not a particularly urgent fix, since as mentioned threading isn't used yet, just thought it'd be good to have it noted somewhere since I wasn't sure if these functions would potentially be used later or replaced in the C++ migration.
