### ISSUE TITLE
map_server crash every quest completion  [master]

### ISSUE THREAD

**Issue by reymarbc** [rathena/rathena#2627]
* **rAthena Hash**:  
server (03da2f6854677a0266aaae8d498fa71ddf41a666)

* **Client Date**:  tested in 2015 - 2017-06-14b Ragexe, Latest kRO

* **Server Mode**:  Renewal

* **Description of Issue**:  Introduction quest causes map_server crash
  * Result: map_server out of range memory location
  * Expected Result: quest completion
  * How to Reproduce: by creating a new character, or going in any quest
  * Official Information: tried different client, but same result

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
Hi @reymarbc, such reports like you made are very bad and tell developers mostly nothing. Why are you do not follow the pre-defined template? This template developed to make fixes for issues faster and reduce tons of unnecessary things from devs. 

How must look like your report?

First of all, you must leave exact codebase hash.
Then, you need additional information are you using any customs or not? (because in 50% cases bugs provoked by old custom features).
Then, you need to try to make your best to get useful information about the error. In your case, you need to receive crash dump log. For what? In such dumps devs will see a line which provokes a map-server crash, and they can trace the problem and find real reason and fix it, but if you have customized emulator, do not forget to add lines which you will see in gdb output to the issue, to show for devs what is the reason for the crash. 

For what all of these steps above needed? First of all, these steps needed for you, not for devs, if you wish to fix the problem, you must spend some time and do some minimal amount of work to present devs the real problem. If you will not explain a problem with details, no one will investigate their own time for you, even if such problem provoke a crash.

**Comment by reymarbc** [comment]
@anacondaqq  i'm sorry, i mistook every lines as a comment,

**Comment by mazvi** [comment]
please leave hash rathena version, and your configuration

**Comment by cydh** [comment]
really for quest? maybe related to achievement that used on quest. if yes, for now, disable achievement feature. my map-server just got crashed while using `@zeny`.
fail on checking achievement that has dependents.

**Comment by reymarbc** [comment]
@mazvi  i did not configure anything except the local ip connection 

@cydh  i will try it, thank you

**Comment by Myrdin** [comment]
Probably something to do with https://github.com/rathena/rathena/pull/2607 ?
Undoing the patch will temporarily solve the issue if you want to enable the Achievement feature.

**Comment by mazvi** [comment]
@reymarbc What is your compiler? Gcc version what and what your os?

**Comment by reymarbc** [comment]
@mazvi
Visual Studio 2015, Windows 10 x64

**Comment by cydh** [comment]
try this
```diff
diff --git a/src/map/achievement.cpp b/src/map/achievement.cpp
index 8b20165..9129fc1 100644
--- a/src/map/achievement.cpp
+++ b/src/map/achievement.cpp
@@ -174,10 +174,12 @@ static bool achievement_done(struct map_session_data *sd, int achievement_id) {
 	auto &adb = achievements[achievement_id];
 	struct achievement *ach_data = sd->achievement_data.achievements;
 
-	return (std::find_if(adb->dependent_ids.begin(), adb->dependent_ids.end(), [&achievement_id, &ach_data]
-	(const int &d) {
-		return (ach_data[d].achievement_id == achievement_id && ach_data[d].completed > 0);
-	}) != adb->dependent_ids.end());
+	for (int i = 0; i < sd->achievement_data.count; i++) {
+		if ((&ach_data[i]) != NULL && ach_data[i].achievement_id == achievement_id && ach_data[i].completed > 0)
+			return true;
+	}
+
+	return false;
 }
 
 /**
```

**Comment by Myrdin** [comment]
@cydh yes that should resolve the issue. No more crashing.

**Comment by sikiro** [comment]
i would push this to master the issue is present on 20171018 client as well.

**Comment by reymarbc** [comment]
@sikiro

Can you please tell me how are you able to use the latest client version to connect in rAthena? I already did search, but no answer.

**Comment by reymarbc** [comment]
@cydh
Thank you for the fix

**Comment by hendra814** [comment]
me too, got crash and map server restart it want change into trans job
