### ISSUE TITLE
Server Freeze w/o Map Crash

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2648]
* **rAthena Hash**: cfb8b42

* **Client Date**: 20170125

* **Server Mode**: Renewal

* **Description of Issue**: Random Server Freeze w/o the Map Crashing
  * Result: The server just freeze server-wide without crashing the map. Turns mob into steady state (Not moving even aggressive) Also players are not able to move.
  * Expected Result: Should not freeze
  * How to Reproduce: Weird part on how to reproduce is I don't know since the map-server isn't crashing and I can't get any logs. (If there is a way, I would appreciate it)
  * Official Information: None
  

* **Modifications that may affect results**:  SRC Modification such as PR Cleanup/Renewal_ASPD & Refine UI also "go" command changing some city coordinates.
  
  

Additional Information: So when the freeze started I have nothing else to do than to restart the server via stop and start.
For one instance, I noticed that there were some memory leaks (Please see below)
![freeze1](https://user-images.githubusercontent.com/5693492/33245939-c4387f78-d349-11e7-9072-4730ea6e9524.JPG)
After I restarted the server, map-server is okay again.

Seeing from the picture above, leaks come from instance.cpp and mob.cpp. The modification done for that part are none.

Regards

**Comment by Playtester** [comment]
Sounds like an endless loop. I think you could run the map-server in debug mode and then when it freezes you could switch to debug (not too familiar with that but there's probably some "pause" button to stop at the current code line) and go through it line by line until you see where it loops.

**Comment by ecdarreola** [comment]
@playtester so its script based or src based?

**Comment by anacondaqq** [comment]
@ecdarreola it can be a MySQL issue too. Nobody knows until you will start to use [Visual Studio Debugger](https://www.youtube.com/watch?v=7ab4z9u7Q_I) to identify what is that. If your map-server crash, and you will run it under visual studio debugger (right click on map-server solution, and select to run it in debug mod, rest servers you can run normally by executing exes). And if the map-server will crash, debugger will stops and will produce debug trace with the steps when it was crashed. What about MySQL Issue, it can be corrupted tables too, just check and [repair mysql first](https://stackoverflow.com/questions/4582832/repair-all-tables-in-one-go), for making sure that its not a mysql bug, then start to use Visual Studio and run your server in debug mode.

**Comment by ecdarreola** [comment]
@anacondaqq not using windows though. But will check on mysql. Im using the mariadb and sql from the installation guide. 

Is there a guide for linux centos7?

**Comment by Jeybla** [comment]
https://github.com/rathena/rathena/wiki/Install-on-Centos

If you have further suggestions for this page, please message me via forum/discord. Thanks

**Comment by ecdarreola** [comment]
@jeybla I've read the guide for installation and followed it but no guide for troubleshooting if I didnt miss anything. Hehe.

I have message you on discord. I will try to fix sql first then check scripts.

**Comment by lighta** [comment]
I'm sorry but as current state I feel this belong more as a support ticket then issue. (There is too much external element that could impact to be an issue imo).
Once this is really pinpoint to some component it could be an issue.

**Comment by rpdigos** [comment]
As the @Playtester said, when the map-server freezes you could use the gdb to attach to the map-server process and check what function is freezing.
With the process attached in the gdb, you could also run it step-by-step, print backtrace, and much more.
[https://stackoverflow.com/questions/14370972/how-to-attach-a-process-in-gdb](url)
[http://dirac.org/linux/gdb/06-Debugging_A_Running_Process.php](url)

**Comment by ecdarreola** [comment]
@rpdigos : Link provided not working

@lighta : I cannot agree more. I could not pin point an issue that's why I dont know how to continue the report but somehow its occurring 4x today so I don't know where to start. I used gdb and print backtrace didn't find anything.

**Comment by ecdarreola** [comment]
I tried gdb again somehow, I got something,

![image](https://user-images.githubusercontent.com/5693492/33471878-52bc35d8-d6aa-11e7-88e1-252ee5ab7d13.png)

I'm using devtoolset-7, what seems to be lacking on this part?

**Comment by rpdigos** [comment]
@ecdarreola 
Try to compile the server with debug symbols `./configure --enable-debug=yes` and then `make clean && make`
Also, when you got a crash, type `bt full` in the gdb to print the complete backtrace

**Comment by lighta** [comment]
@ecdarreola "sudo dnf debuginfo-install ......" just copy paste the line the debuger gave you. Those package contain the symbole of the linked libraries.

**Comment by aleos89** [comment]
Are you able to provide any more information on this?

**Comment by ecdarreola** [comment]
@aleos89 : the bug is still appearing but not able to get some data because when I use gdb it doesn't show anything. The map server doesn't crash. So yeah it still needs input on me will provide feedback once I got something useful.

**Comment by technoken** [comment]
Happened to me before and the issue was with the logs database tables. I can't figure out what caused it and since I can't repair it with repair table, I did drop my logs database and import a fresh new log database from sql/log.sql. And viola the freezing is gone.

Make sure to backup first your previous database before deleting it. Just giving my cents since i think it's the same with mine.

**Comment by ecdarreola** [comment]
@technoken I already fixed my sql database and it still happens. or repaired sql still the same.

**Comment by technoken** [comment]
@ecdarreola have you tried deleting the logs database and importing a fresh one without entries?

**Comment by ecdarreola** [comment]
@technoken yes sir still the same.

**Comment by lighta** [comment]
When this happening try to do.
free -m
ps aux
This will tell use if you had some ram left. (maybe you are swaping). It willalso tell cpu consomption maybe another process is taking all the cputime.
Beside this, you need to found a lead else we can't do anything. So:
1) Does this happen frequently ? yes at which time ? No it's sporadic ? then it's probably from an event or combinaison of event. (the more it's a combinaison the more it's hard to found but it should also happen less frequently since the chance to have that combinaison decrease..)
2) Does this happen when I have more people on my server ? Or does my server share his ressource ?
Is there some other process running that might stall all ? Does my vps is shared with something else and it's actually my server provider fault ?

@Playtester suggestion is also good, what he meant is do https://sourceware.org/gdb/onlinedocs/gdb/Attach.html once you get the freeze. That mean you have the console ready and do the attach process. (you could also launch the map-server with gdb but that will slow it down a bit).
Once it's attach (and we are in a freezing) pause the process. (ctrl+c)
dump the backtrace.

e.g it could look like this:
`
./athena-start start
#.... time pass waiting for freeze
#freeze occur attach process to gdb will auto pause it 
gdb 
(gdb) attach 21872
(gdb) bt
#0  0x00007f1c05a467a7 in select () from /lib64/libc.so.6
#1  0x00000000007a548e in do_sockets ()
#2  0x0000000000799370 in main ()
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x00007f1c05a467a7 in select () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f1c05a467a7 in select () from /lib64/libc.so.6
#1  0x00000000007a548e in do_sockets ()
#2  0x0000000000799370 in main ()
`
Here I did attached the process did a backtrace then allow the process to continue with "c" then did "ctrl+c" to repause it and displayed backtrace again. (now my backtrace is not a good exemple cause the server was doing nothing but hopefully we will see something for you).

**Comment by ecdarreola** [comment]
@lighta @technoken @Playtester I managed to solve it by changing max file size of the system and ulimit. I'm on the 3rd day stable.

**Comment by lighta** [comment]
What was the old value and new value ?

**Comment by ecdarreola** [comment]
@lighta As for the file-max = 512356 changed it to 999999 as for the

limits.conf soft no file 1024 while hard no file 999999

It worked for me
