### ISSUE TITLE
Can't login to longin server

### ISSUE THREAD

**Issue by hotspicy945** [rathena/rathena#2654]
* **Client Date**: 
 20160203

* **Server Mode**: 
 Renewal 

Now my server through path
Public IP => application Gateway => my VM
I used application Gateway because I'm under attack.
Technical service staff help me set a application gateway to protection server. 

![image002](https://user-images.githubusercontent.com/27738134/33417060-b90bbba4-d5da-11e7-982a-ff7b589ece4f.png)

The red circle was my problem

I tried to config

1.login_athena.conf

bind_ip: 10.0.0.4 or 127.0.0.1
login_port: 6900

2.char_athena.conf

login_ip: 10.0.0.4 or 127.0.0.1
login_port: 6900
char_ip: Public IP
char_port: 6121

3.map_athena.conf

char_ip: 10.0.0.4 or 127.0.0.1
char_port: 6121
map_ip: Public IP
map_port: 5121

But user still can't login loginserver.
Even I tried to insert "wrong password", the client only show "server disconnect".

Can my login server listen to Public IP?
Or what's wrong with me?

Thank you!

**Comment by Lemongrass3110** [comment]
From your image i'd say whatever you set up here is only compatible with HTTP.
Since the server and the client doesnt communicate via HTTP you get instantly disconnected, even if the traffic is correctly forwarded.
Beside that your setup would not work after the login server anyway, since the client directly communicates with all 3 servers in each step(login, char select, map). So char and map need a public IP as well.

**Comment by Lemongrass3110** [comment]
Beside all that, this is not an issue, but a support request and it would be nice if you had used the forum for this.
