### ISSUE TITLE
When can the ZERO version be supported?

### ISSUE THREAD

**Issue by idamonli** [rathena/rathena#2730]
@4144 has submitted ZERO related updates in HERC
https://github.com/4144/Hercules/commit/f385274cb59e251bc5aa3dc2fc918697523f7312

**Comment by sikiro** [comment]
I don't expect this to be supported anytime soon. I don't think we should support it at all to be honest, splitting support once again will halt renewal development, the emulator is missing quite a bit and this will only add more things to do and delay other features that would benefit the emulator more.

**Comment by Akkarinage** [comment]
We have no intention of adding support for ZERO at this time.

**Comment by Lemongrass3110** [comment]
Just to clear things up:
We will not add support for the zero client since in the past features that were good enough for sakray or main were merged to the respective client anyway. Adding support for in development features that are more or less in a field test state does not make any sense to us and will only waste our time if it gets overhauled again.
