### ISSUE TITLE
Drop from monster ID:2248 Golden Poring

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2774]
drop changes https://www.divine-pride.net/database/monster/2248/golden-poring
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
This mob is intended to be an event mob and its drops varies depending on the current event of kRO.
I don't think we need to update its drop since it can be incorrect when compared to official the next day.

I mean DP's drop and kRO's official DB doesn't even match.
https://www.divine-pride.net/database/monster/2248/golden-poring
ro.gnjoy.com/guide/runemidgarts/popup/monsterview.asp?monsterID=GOLDPORING
