### ISSUE TITLE
Monsters have items with 0% drop rate

### ISSUE THREAD

**Issue by vstumpf** [rathena/rathena#2842]
* **rAthena Hash**:  de9b4ef

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**:
The following monsters have items with 0% drop rate. should be at least .01%.
1876 Lord of the Dead E_LORD_OF_DEATH
2011 Tenacious Ghoul E_GHOUL
2012 Tenacious Zombie E_ZOMBIE
2066 Anopheles E_ANOPHELES
2098 Doppelganger E_DOPPELGANGER

* **Modifications that may affect results**: None
Having these items droppable only with `drop_rate0item = true` in your configuration seems like an oversight.

**Comment by mrjnumber1** [comment]
pretty sure these are all event mobs only anyways, but i feel like it should have a warning on the console if there's an item with a droprate of 0

**Comment by Playtester** [comment]
0% drop items used to drop on Aegis, including the placeholder apples. But the emulators never decided to implement this by default (it doesn't really matter since hardly any server is 1x drop rate anyway).

I think with the renewal update these placeholder items stopped dropping, but I'm not 100% sure as I haven't played on official renewal myself.

**Comment by MrAntares** [comment]
@Playtester "(it doesn't really matter since hardly any server is 1x drop rate anyway)"
I does matter to me and my ghost server :(

**Comment by Lemongrass3110** [comment]
As others stated already this is official data, whether we like it or not.
That's what that setting is for.
