### ISSUE TITLE
GS_DISARM, RG_STEALCOIN formula

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#2889]
* **Description of Issue**: 
  * Result: presently, even the src acknowledges that many skills such as GS_DISARM is using an unofficial formula!

  * Official Information:
extracted from 10.2, 14.1, and 15.2 zone, it's the same across all.
GS_DISARM strip chance
```
    baseRate= casterDEX / (4 * (7 - skLevel)) + casterLUK / (4 * (6 - skLevel));
    rate = baseRate + casterLevel - (tarAGI*baseRate/100)- tarLUK - tarLevel;
    if (GetServerRandom(0, 20000)%100 < rate)
        (strip weapon for 30 seconds or do -25% atk on mobs) 
```
(rate being per 100)

RG_STEALCOIN steal chance
```rate = (casterDEX/2 + 2 * (casterLevel - tarLevel) + (10*skill_lv) + casterLUK / 2);```
(rate is per 1000)
RG_STEALCOIN zeny amount
```amount = GetServerRandom(8*tarLevel, 10*tarLevel)```

if there are any more custom values like this that you need pulled from the zone, i can try to look into them. thank you. :)

**Comment by Playtester** [comment]
Reopening. 

The Zeny amount is missing a component. It adds `(tarLevel*skill_lv)/10` to the Zeny amount stolen.

For example on level 1-9 when stealing from a poring you steal 8-10 Zeny. However on level 10, you steal 9-11 Zeny instead.

**Comment by Playtester** [comment]
Some additional findings:
- Freeze / Stone etc. don't block Mug; instead, Mug actually destroys Freeze / Stone as it counts as a 0 damage skill (also counts as Exp tap)
- Only fails on non-monsters, bosses and already stolen monsters (there's no special check for treasure chests, but they are boss type in pre-renewal at least which makes it fail)
- If skill fails due to invalid target, it doesn't consume SP and doesn't set any cast delay, but there's a 500ms cast delay
- If skill fails because chance fails, SP is consumed and delay is set
