### ISSUE TITLE
Nydhorgg's Shadow Garb

### ISSUE THREAD

**Issue by hederod** [rathena/rathena#2919]
bonus3 bSPDrainRate,10,1,0; change it for bonus2 bSPDrainRate,10,1;

for server stop show warning error bonus...

item id 2554

**Comment by secretdataz** [comment]
There is no bonus3 variant for bSPDrainRate

**Comment by hederod** [comment]
if it does not exist because it is in the db of the server?

**Comment by hederod** [comment]
fix and say invalid.. so nice

**Comment by Lemongrass3110** [comment]
Not following the issue template and not providing any good info is not nice either.

**Comment by secretdataz** [comment]
I don’t have a crystal ball. Should you have followed the issue template and provided enough info, I wouldn’t have closed the issue.

**Comment by hederod** [comment]
What does your silly comment have to do with crystal balls?

**Comment by hederod** [comment]
I told you the bonus was wrong and you simply repeated what I reported. I know that There is no bonus3 variant for bSPDrainRate.
If it was corrected before you read the problem, it's not mine.
the problem has already been fixed and that's what matters.

**Comment by secretdataz** [comment]
I feel like I'm obligated to write some explainations.
First, the OP did not follow the issue template and wrote the issue in a hardly-understandable manner.
If this
```
bonus3 bSPDrainRate,10,1,0; change it for bonus2 bSPDrainRate,10,1;

for server stop show warning error bonus...

item id 2554
```
was replaced by
```
* **rAthena Hash**: fdb7aef
* **Client Date**: Irrelevant
* **Server Mode**: Pre-Re/Re/Both
* **Description of Issue**: Item script for Nydhorgg's Shadow Garb (2554) is incorrect.
  * Result: The server outputs a warning because the bonus script blablablah
  * Expected Result: No warning/error. The script should instead be `bonus blablablah;`
  * How to Reproduce: Starts the map server
  * Official Information: None
* **Modifications that may affect results**: I have this and that modification in my item db.

```
I would have understood it better and act accordingly. Otherwise I would need a [crystal ball](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBEiX0emhFOg2-vnqLuDHs045HkwvRXBiosjFo8KK0mUZ2s_tSyA).

Second, I didn't fix the issue and flag this issue as invalid. In fact, the item has not been touched for 3 years. The last commit is authored by Cydh as seen [here](https://github.com/rathena/rathena/blame/fdb7aefdd8641420dc0b14cfe18b41b2cf9964f1/db/pre-re/item_db.txt#L1421). The same can be seen in the renewal DB's [commit history](https://github.com/rathena/rathena/commits/master/db/re/item_db.txt).

To conclude, this issue is **invalid** and has been tagged correctly. It hasn't been fixed and wrongly tagged as invalid.

To continue this discussion, please reach me out on rAthena's Discord server or mail me at secret[at]rathena.org.
