### ISSUE TITLE
[ BUG ] SA_LANDPROTECTOR,Magnetic Earth

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3101]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/7f8b9c43c55119e7d76b3a8e24fb87f6bae38043
* **Client Date**: 2017-07-06
* **Server Mode**: RE
* **Description of Issue**: This ability is not working properly, some abilities when cast outside the protection area are reaching targets.

If you cast any ability with area of effect large enough to reach players within the Magnetic Earth effect, the player will be hit. An example is the Jack Frost skill, which can be cast in any area on the screen and reach players within the protection area.
  * How to Reproduce: Use: Magnetic Earth in any location, stay in any area within, cast any area skill that has hit area large enough to hit inside and you will get it.

With Jack Frost you can cast anywhere on the screen.

* **Prints:**: 
![1](https://user-images.githubusercontent.com/6227618/39668664-f73d9204-50a9-11e8-8f71-aa5d7146231f.png)

![2](https://user-images.githubusercontent.com/6227618/39668665-003ba2d8-50aa-11e8-8ae3-d95716b38210.png)

![3](https://user-images.githubusercontent.com/6227618/39668667-06f521f8-50aa-11e8-9c09-179b998dc39c.png)

**Comment by vstumpf** [comment]
This is due to the range of the unit.
Take Storm Gust for example. The way stormgust works is it creates a bunch of skill_units in a square, each with a range of 1 (3x3). So if you're on the edge of a land protector, and someone casts stormgust, land protector will block the units from being placed on itself. But the units outside can splash on the inside.

You can see this easier with Meteor Storm. Each meteor is 1 unit with a range of 3 (7x7). If a meteor lands outside of the LP, and if a character is within a 7x7 square around the meteor, the character will be hit.

I'm not familiar with renewal skills, so I can't confirm if these skills need changes.

**Comment by secretdataz** [comment]
This is official behavior. LP doesn’t prevent AOEs from splashing in, but prevent skill units from being placed on it.
I’ve tested the behavior on Aegis myself.
