### ISSUE TITLE
Battleground's clan chat bugs when writing symbols

### ISSUE THREAD

**Issue by Rolfxx** [rathena/rathena#3104]
* **rAthena Hash**: c5ceda03f

* **Client Date**:  2016-02-03, 2016-12-28, 2017-05-17 

* **Server Mode**: Renewal

* **Description of Issue**:  when you enter a battleground, in this case KvM from current rA system, and you write any symbol **in the clan chat** like ,:>;']{ or capital letters with symbols :D _D <3 
random symbols will appear. general chat works normally, tho
![screentest008](https://user-images.githubusercontent.com/33087653/39728577-fae09eba-5257-11e8-8461-eeb8bcf18359.jpg)
![screentest009](https://user-images.githubusercontent.com/33087653/39728579-fb02c602-5257-11e8-9165-792dc813b584.jpg)

  * Result: after a while, the bug accumulates. if you keep typing symbols and capital letters it will send more and longer rubish talk
  * Expected Result:  it should work as any other chat
  * How to Reproduce:  play any battleground from the current system using any of the clients i said (diffing with the last NEMO) and start typing symbols and capital letters, in other words, spamming the chat
  * Official Information: none
  

* **Modifications that may affect results**: 
things i've tried:
- changed langtypes to 10 11 12 and currently 1
- changed exes, and tried diffs like Enable Custom Official Fonts and Disable Swear Filter

I'm a bit confused about the source of this bug. idk if it is client side or servers. 

thank you very much!

**Comment by sader1992** [comment]
did you check if the client send it to the server or the server generated it ?

**Comment by vstumpf** [comment]
It has nothing to do with adding symbols, code pages, langtypes, etc.

This is because when the client receives the message, it assumes it is null terminated, but the server did not send a null terminated string.

It was working on older clients, and I don't know which clientdate changed it. 

As a quick fix, you can do the following:

- Add 1 byte to buf
- memset buf to 0 (or calloc it instead of malloc)
- add 1 byte to the size of the packet

**Comment by Rolfxx** [comment]
@vstumpf how to do this? where? is this from packets?

thank you for response
