### ISSUE TITLE
Super Novice Chant on max lvl (99 & 160)

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#3148]
RENEWAL
Version: https://github.com/rathena/rathena/commit/82025555146130194f5ae20adaea46d5f8b46cdc

Many sources say, that upon achieving maximum level, and max exp, one should be able to use the SN Chant indefinitely, but when I try to use the chant, the following message appears in red:

[Protector of Guardian Angel] You can't use it when you reach the highest level

This source states the opposite:
https://irowiki.org/wiki/Super_Novice#Life_After_Level_99
"Upon attaining 99,999,999 EXP (as shown on the character Select screen), you will be able to use both the novice chant Fury and Mental Strength upon 0 HP."

If this is a kRO vs iRO thing, would it be possible to make this behavior configurable?

**Comment by aleos89** [comment]
According to the source (I haven't tested the skill myself):
```cpp
#define MAX_LEVEL_BASE_EXP 99999999 ///< Max Base EXP for player on Max Base Level
```
You should be able to summon the spirit just fine as that's the value returned on the player's base level check when maxed.

**Comment by aleos89** [comment]
Ok so upon further testing on Aegis, I was able to trigger the Fury mode while level 98 or less with a 10%-valued experience. Once I hit 99 I was unable to trigger the state no matter how many times I tried (upon the point of silencing myself).

Must be an iRO thing to trigger at 99. Could be just worth while to make it into a config for this part since many people are use to it.

**Comment by Daegaladh** [comment]
Apparently this was an aegis bug, as stated in warpportal forums. The client doesn't even send the packet anymore, but shows the red message instead, so there's nothing we can do about.
