### ISSUE TITLE
Earthquake don't make any damage

### ISSUE THREAD

**Issue by poporing** [rathena/rathena#3176]
* **rAthena Hash**:  c68da31f67b205854ead7d10e5efb4d6c8bac19d

* **Client Date**: 20170614

* **Server Mode**: pre-renewal

* **Description of Issue**: lot of the time mvp that cast Earthquake make no damage
  * Result: when mvps ex: ifrit, rsx ect... cast earthquake player didn't get any damage
  * Expected Result: should make high damage
  * How to Reproduce: Just let a mvp cast earthquake on you
  * Official Information: I know that earthquake should do high damage.
  

* **Modifications that may affect results**: 
 I test it in a 100% clean rathena git

**Comment by poporing** [comment]
I'm the only one with this issue?

**Comment by poporing** [comment]
[Error]: 0 enemies targeted by 653:NPC_EARTHQUAKE, divide per 0 avoided!

**Comment by KrokusPokus** [comment]
Your error message basically seems to originate from the lines
```
if (nk&NK_SPLASHSPLIT) { // Divide MATK in case of multiple targets skill
	if (mflag>0)
		ad.damage /= mflag;
	else
		ShowError("0 enemies targeted by %d:%s, divide per 0 avoided!\n", skill_id, skill_get_name(skill_id));
}
```
in battle_calc_magic_attack(). I don't know what situation would cause a mflag == 0, exactly.

There is a general problem with too low damage in rAthena's Earthquake calculation, though. From what I can tell, rAthena has no special handling for the damage of Earthquake, which is a magical attack, being based on a mob's physical atk instead of its matk (sources: https://irowiki.org/wiki/NPC_EARTHQUAKE and https://irowiki.org/wiki/NPC_EARTHQUAKE state "Neutral element magical damage based on the monsters physical attack power"). This could properly be fixed like this:

```
--- E:/Temp2/battle.cpp	Mon Jun 11 11:41:56 2018
+++ E:/Temp2/battle_new.cpp	Mon Jun 11 11:44:00 2018
@@ -5826,10 +5826,19 @@
 				ad.damage = status_get_lv(src) * 10 + sstatus->int_;
 				break;
 			default: {
-				if (sstatus->matk_max > sstatus->matk_min) {
-					MATK_ADD(sstatus->matk_min+rnd()%(sstatus->matk_max-sstatus->matk_min));
-				} else {
-					MATK_ADD(sstatus->matk_min);
+				if (skill_id == NPC_EARTHQUAKE) {
+					if (sstatus->rhw.atk2 > sstatus->rhw.atk) {
+						MATK_ADD(sstatus->rhw.atk + rnd()%(sstatus->rhw.atk2-sstatus->rhw.atk));
+					} else {
+						MATK_ADD(sstatus->rhw.atk);
+					}
+				}
+				else {
+					if (sstatus->matk_max > sstatus->matk_min) {
+						MATK_ADD(sstatus->matk_min+rnd()%(sstatus->matk_max-sstatus->matk_min));
+					} else {
+						MATK_ADD(sstatus->matk_min);
+					}
 				}
 
 				if (nk&NK_SPLASHSPLIT) { // Divide MATK in case of multiple targets skill
```

**Comment by danielbernard** [comment]
That doesn't quite add up though - since the division with mflag is only done if mflag is greater than (and not equal to) zero.

**Comment by KrokusPokus** [comment]
Oh, I didn't mean that the two things are identical. The generally too low damage of Earthquake on rAthena from using matk instead of atk as basis might have caused op's looking into things, and one of the things he found was the mflag == 0 case indicated by the debug message. I don't know if he really meant no damage or rather negligible damage that might look like no damage. Only if it's the latter, the above diff might fix it and get damage to official levels.

**Comment by Badarosk0** [comment]
Really this damage is very low on rAthena.
