### ISSUE TITLE
Level cap is now 200/70

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#3342]
* **rAthena Hash**: 9313922
* **Client Date**: Irrelevant
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: We are still on 175/60 cap.
  * Expected Result: kRO has expanded level cap to 200/70. Several skills also have their max level and formula adjusted.
  * How to Reproduce: As a 3rd job char, use `@lvup 999`.
  * Official Information: http://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=3890090&curpage=1
http://ro.gnjoy.com/news/update/View.asp?seq=242 (thanks @flamefury)

**Comment by flamefury** [comment]
2 skills from each of the main 3rd jobs have also had changes, some of them fundamental. Should those be attached to this issue or made into their own?

As with #3324 , this is still reserved to Sakray only for the time being and should probably wait for the merge to live.

**Comment by flamefury** [comment]
That it has, and with it an adjustment to the experience levels of 1-175. The new level up tables haven't yet been reflected in the website, but hopefully Gravity will update it soon. Keep an eye on this page:
http://ro.gnjoy.com/guide/ragstart/play3.asp

**Comment by hederod** [comment]
new rebirth sistem...
can be implemented, the choice to use or not, put in npc jobmaster.

**Comment by flamefury** [comment]
Hasn't happened anywhere yet, but kRO dev notes announced another increase to 200/70 (200/60 for Doram):
http://ro.gnjoy.com/news/devnote/View.asp?seq=3956818

Scheduled for an August release. Just noting down here to keep track.

**Comment by flamefury** [comment]
200/70 (200/60 for Doram) update is now on live kRO. The page I linked to before with the EXP tables have not been updated yet, however, the new EXP tables are reflected on the events page:
http://ro.gnjoy.com/news/update/View.asp?seq=242

This page also includes the new job stat bonuses at JobLv70 (JobLv60 Doram). Click the leftmost bottom button to get the EXP table, and the middle button for the job bonuses.

Since 185/65 is no longer being used on any official (as nothing other than kRO ever received it), I think it'd be prudent to just skip that and go straight for the 200/70 update at this point.

**Comment by aleos89** [comment]
Fixed in 1658f27.
