### ISSUE TITLE
Autosave prevent vending when save happen while setting up shop

### ISSUE THREAD

**Issue by SnotraRM** [rathena/rathena#3408]
* **rAthena Hash**: 3fc88fe6c

* **Client Date**: 20151104 / 20180530

* **Server Mode**: Pre-RE

* **Description of Issue**: 
  * Result: When an autosave happen when setting up a shop, you won't be able to complete it (video of the issue: https://mega.nz/#!hJ8ixYxL!RNV1nqkosGYajQJyb7Qs2vPI0oDWRSJExrx1IQL312U)
Meaning that when you set autosave_time is too low, players will be unable to setup shops, or even if the value is high, if you have back luck, autosave will happen as soon as you start making the shop and you won't be able to complete it.
  * Expected Result: You should be able to setup you shop even if you take time to do it
  * How to Reproduce: 
-Start opening a shop
-Wait for an autosave
-Try to confirm shop creation, you won't be able to
  * Official Information:/
* **Modifications that may affect results**: 
the lower the autosave_time is, the lower the chance of the issue happening

**Comment by jchcc** [comment]
When setting up a shop(prevending) and an autosave happen, server send ZC_OPENSTORE(0x012D) packet to client again, then client won't able to complete vending.

See intif.cpp
Is necessary to clif_openvendingreq while in state.prevend?

**Comment by gustavobrigo** [comment]
I can confirm that. Pre-RE hexed 2015

**Comment by lukyrys** [comment]
confirm on pre-re 2018-06-21aRagexeRE

**Comment by RannaAI** [comment]
> When setting up a shop(prevending) and an autosave happen, server send ZC_OPENSTORE(0x012D) packet to client again, then client won't able to complete vending.
> 
> See intif.cpp
> Is necessary to clif_openvendingreq while in state.prevend?

Why is that line even needed there ? 
And yea this issue has been around since 2018 and making vending frustrating for all players

**Comment by Indigo000** [comment]
Okay, I can absolutely confirm this as well.

The solution is to comment out `clif_openvendingreq(sd, sd->vend_skill_lv+2);` in `intif_parse_StorageReceived`. After I did that, I could keep the vending window up for a significant amount of time and it would still let me set up shop. When leaving it uncommented, it would become impossible to vend after a couple of minutes.

**Comment by Indigo000** [comment]
https://github.com/rathena/rathena/commit/17946ea28665709465a3855c59d310bee9c4b7a1
https://github.com/rathena/rathena/commit/800714abfe7b6e665d6997c314fc26a0ae519a7f

These commits seem to have messed things up, just for reference.

**Comment by Indigo000** [comment]
So, the main problem here is that `intif_storage_save(sd,&sd->cart);` is used by both `chrif_save` AND by the vending skill MC_VENDING. 17946ea28665709465a3855c59d310bee9c4b7a1 made a special case for when a player actually used the skill, which was `TABLE_CART_` so that a `chrif_save` would not try to open the vending store again when it shouldn't, which is what the problem is right now. 800714abfe7b6e665d6997c314fc26a0ae519a7f reverted this change, which messed this up.

Then in 46b1de7d5074dc1dc80e17214e23acae656161a9 they did away with the `type` parameter of `intif_storage_save` and simply started adding `sd->cart`, which means you can no longer make a distinction between two potential cart types.

What we need really is to be able to tell `intif_storage_save` whether it was called by the server doing a save OR when the Vending skill was used. Right now it's one and the same.
