### ISSUE TITLE
%Hp drain

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#344]
I noticed that %hp drain skills use more hp than their formula says, for example the monster skill Dark Breath on lvl 5 should damage 50% hp, but in reality it is around 60%. Same with sura skills like Tiger Cannon. It should consume 30% hp on max level, so in theory I should be able to use it 3 times from 100% hp, but after 2 casts I'm under 25% (red), so it consumes much more.

**Comment by reigneil** [comment]
i cant reproduce it using Tiger Cannon in Dummy Monster in Prontera... in my theory maybe because you drained your HP from external source like receiving enough damage to left you below 30%. that is because If you use 3 Tiger Cannon your remaining HP would be 10% meaning this10% is your HP to keep in order you to cast 3 TC
