### ISSUE TITLE
Confirm 4679 and 4689 combo

### ISSUE THREAD

**Issue by BrOgBr** [rathena/rathena#3492]
* **rAthena Hash**: indifferent

* **Client Date**: indifferent

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: It's transforming in the monster 3225, literally, it isn't visual only.
  * Expected Result: I haven't certain but I think that it should be visual only.
  * How to Reproduce: Card Combos 4679 and 4689 with a Rune Knight
  * Official Information: Needs confirm, I can't do it.
  

* **Modifications that may affect results**: 
  
  

Do it so the transformation is only visual:
_(not altering the player stats to 0 as it is right now)_

``4679:4689,{ autobonus "{ bonus bAtk,100; }",30,6000,BF_WEAPON,"{ active_transform 3225,6000; }"; }``

Same happens with the other combos from Lhz_dun05.

**Comment by Atemo** [comment]
Unable to reproduce on 18f9574a526a9ce8c0df5d1d3b64d3a3bd459aca

**Comment by aleos89** [comment]
Can you explain a little more into what you mean? There are no methods of player's "becoming" monsters other than visually. We aren't able to reproduce any issues with these items.

**Comment by mrjnumber1** [comment]
i can explain. it seems like my base stats are completely destroyed when transforming. do allstats 100 at max job level and use stat foods and buffs and look at how they're affected by it. perhaps that's what they mean...?

**Comment by BrOgBr** [comment]
@mrjnumber1 is right!
For me the correct should be as I said for example:

`4679:4689,{ autobonus "{ bonus bAtk,100; }",30,6000,BF_WEAPON,"{ active_transform 3225,6000; }"; }
`

The active transform at left, only visual as all other items that do the samething.

**Comment by Everade** [comment]
@aleos89 
**For testing purposes / reproducing:**

Set all stats to maximum and attack a monster.
Once you are being transformed, your stats become extremely weak, thus it means that you're most likely taking over the actual mob stats, rather than representing your own.

This is especially noticable on high rate servers were players hold higher stats than official, such as 200 or more.


So the question here is, is that the official way how it works?
Should the transformation give you some buffs, rather than messing with your actual stats and strength instead?

**Comment by aleos89** [comment]
Thanks for the feedback. I'll look into this again.
