### ISSUE TITLE
NPC_POWERUP skill effect on monster physical damage

### ISSUE THREAD

**Issue by slyx88** [rathena/rathena#3538]
* **rAthena Hash**: 

* **Client Date**: x

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: NPC_POWERUP skill should triple monsters physical damage and hit but does not affect their skills damage and magic damage. Currently in rAthena the hit bonus works perfectly but not the physical damage bonus.
  * Expected Result:  This skill should increase the physical damage of monsters as well
  * How to Reproduce:  Spawn biolab monster (seyren or harword) and check the damage different before and after they use NPC_POWERUP skill.
  * Official Information:https://www.youtube.com/watch?v=UKFt58_sGPc&list=LL-iKjLO3OiG5Nrt_nfbSbig&index=3&t=0s

kRO Rune knight in ET

At 1.50 min : Before powerup skill, ifrit did damage around 4k+ to  5k+ normal physical damage while the fire breath damage was 14k+
At 3.25 min: After powerup skill, ifrit did damage around 12k+ to  15k+ normal physical damage while the fire breath damage was maintained 14k+
  

* **Modifications that may affect results**: 
  
  
under battle.cpp, section Check damage through status, look for:
//SC effects from caster side.
	sc = status_get_sc(src);
	if (sc && sc->count) {

and add this line
```if (src->type == BL_MOB ) {```
	```if (sc->data[SC_INCATKRATE] && !skill_id) {```
		```damage += damage * 2;```
		```}```
	```}```

**Comment by MathReaper** [comment]
Probably this issue is related to all environment `damage` calculation, because they don't have one handed weapons or two handed weapons, for example.

**Comment by slyx88** [comment]
yeah..applying sc data would be proper =)

**Comment by Playtester** [comment]
Most of this should be fixed with the implement of ATKpercent:
https://github.com/rathena/rathena/commit/4247bc50c52a605397508a6b6a3e9bb3a659f591

Though the info above implies that Fire Breath should be on the list of skills not impacted by ATKpercent. That is still TODO.

**Comment by Playtester** [comment]
NPC_CRITICALSLASH
Dullahan - 1065 damage
Kraben - 765 damage

NPC_PIERCINGATT (vs. 8 DEF 60 VIT)
Archdam Normal - 500-592
Archdam - 548-647
5 Archdam vs 110 VIT - 494-573

**Comment by Playtester** [comment]
Fixing skills that were "weapon" type even though they shouldn't be:

NPC_MAGICALATTACK - Just need to change type to magic and maybe remove the hardcoded BF_MAGIC flag.
NPC_KEEPING - Duration should be 30s (it only has 1 level).
NPC_DEFENDER - Should reduces ranged damage by 87.5% and halves movement speed.
NPC_POWERUP - Still need to check but pretty sure we can just remove the skill type here and it works. (Though it should only have 5 levels, not 10. But if I fix that one I should fix it for NPC_AGIUP too.)

Also results from tests above:
NPC_CRITICALSLASH - Just deals a critical hit, we just need to apply the renewal code for it then this skill works again.
NPC_PIERCINGATT - 100% damage, ignored hard DEF, but is reduced by VIT_DEF. Need to write function that returns VIT_DEF for it. Also the hit rate probably should increase by 10% per level (see https://ro.kokotewa.com/db/skl_info?id=NPC_PIERCINGATT).

Since my tests showed that status and property attacks are affected by ATKpercent after all, we cannot exclude them. But for some newer skills like FIREBREATH we have the data what damage type they are and indeed the *BREATH skills and also VAMPIRE_GIFT are not defined as weapon skills, so I think it's fair to exclude them.

I find MVPs way too chaotic to really tell for sure by testing. Even on the video linked above I'm not sure what damage comes from what.

**Comment by Playtester** [comment]
I'll move the PIERCINGATT update to a separate issue as it requires some code refactoring.

**Comment by Playtester** [comment]
NPC_KEEPING also increases MDEF:

14 INT vs. Beetle King
Holy Light - 14
Holy Light after Keeping - 11

**Comment by Playtester** [comment]
NPC_KEEPING made me realize that we need to rework our DEF/MDEF code a lot, so I created a separate issue on that: https://github.com/rathena/rathena/issues/8236

**Comment by Playtester** [comment]
Reopening this.

I got the opportunity to test a bit more myself rather than just listen to reports.
NPC_VAMPIRE_GIFT was tripled by NPC_POWERUP. Also affected by Curse and Frenzy when used by players (Death Guidance)!
Even NPC_FIREBREATH's damage reported here was tripled by it.

I think what we see above it the effect of Renewal. IFRIT is using level 10 of NPC_FIREBREATH which already does 1000% damage.
In pre-renewal NPC_POWERUP makes that 3000%, but in Renewal it makes it 1200%, so you see much lower increase in damage in Renewal.

Also one more thing: When monsters use LK_SPIRALPIERCE, ATKpercent actually affects it.

I assume that for monsters ATKpercent is directly applied to their ATK, so any skill that's somehow based on ATK is affected even if they are not of "calculated damage" type.

NPC_DRAGONBREATH would be the only outlier left, but I only took that from existing code, I can't test it as that's a renewal skill, so I'll leave it untouched.
