### ISSUE TITLE
Alchemist class base SP

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#358]
I checked the SP of Genetic/Alchemist/Creator and they seems to be about the half what they are supposed be (compared to iw stat calc)

**Comment by Playtester** [comment]
Hmmm according to the currently available sources Alchemist SP is 10+4*LEVEL, which is already correct. Creators get the normal 25% bonus. Genetics however seems to have 10+9*LEVEL, currently it's only 10+4*LEVEL.

**Comment by MrAntares** [comment]
So can we fix this?

**Comment by Playtester** [comment]
I found a lot more mistakes in the HP/SP values, many things used to be correct but seem to have gotten "unfixed" for some reason, I don't know.

Basically should just use the hp/sp table but that one is incomplete. I could probably hardcode it too, but currently can't even run rAthena because I keep getting unknown packet errors. ^^;

**Comment by MrAntares** [comment]
Alchemist tree SP is still not good :(

**Comment by Playtester** [comment]
I know, I started with pre-renewal code. Still need to do pre-renewal tables and renewal code and tables. It's a lot of typing work.

If you just want to fix genetic class SP you can easily do it yourself, just find the re/job_db1.txt and then find all rows that are commented with "Genetic" and change:
4071,	32000,90   ,500  ,400   [...]
to:
4071,	32000,90   ,500  ,900   [...]
