### ISSUE TITLE
Devotion out of range have effect

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#370]
https://www.youtube.com/watch?v=0558jx2a8nk&feature=youtu.be

svn 13030.

I need help.

**Comment by davidtamayo177** [comment]
Hello! Maybe because the window for the GM (devo provider) has not yet been updated with the location of the monk since you are using three windows. Have you tried checking if the monk has already moved in the GM's window? There are cases when using double+ login when one of the windows only get updated by other char's location when window focus is returned to it.

Thanks
