### ISSUE TITLE
 mapserv crashing every time

### ISSUE THREAD

**Issue by IsabelaFernandez** [rathena/rathena#3741]
* **rAthena Hash**: 

* **Client Date**: 
270517

* **Server Mode**: 

Renewal
* **Description of Issue**: 
Hello community, I would like a solution to the mapserv problem that is crashing every time I invoke some mob or come close ... I do not know the reason for that.
any tips?
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
Hi, without information about the crash (crash-dump) your issue is useless. 
Depends on what are you running your server (on windows or linux) you must follow rathena guides about getting crash dump info and publishing it here with providing exact line which provokes a crash.

https://github.com/rathena/rathena/wiki/GDB

**Comment by Lemongrass3110** [comment]
No input for 7 days. Closing this.
