### ISSUE TITLE
Devotion Inherits Status

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#4066]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ac558d7c1e58c817744968f70f487c3d3d16aac2
* **Client Date**: 20180621
* **Server Mode**: RE
* **Description of Issue**: The effect of SC_DEFENDER is being added twice when inherited from Devotion.
  * Result: Double damage reduction.
  * How to Reproduce: Activate SC_DEFENDER, use Devotion on a party member, now disable SC_DEFENDER and re-enable it, that's it, you'll be double the dev status against long-range attacks.
  * Prints:
Enabled SC_DEFENDER first time:

![a2](https://user-images.githubusercontent.com/6227618/55296312-d0fb5e80-53ed-11e9-8cb4-44e82ddfcea3.png)

DMG: 2300

Second time with SC_DEFENDER enabled:
![a3](https://user-images.githubusercontent.com/6227618/55296315-dc4e8a00-53ed-11e9-96d3-020327ceeee2.png)

DMG: 460

The problem can only be reproduced if you enable SC_DEFENDER before using Devotion, then deactivate and activate SC_DEFENDER again.

**Comment by cydh** [comment]
**Defender -> Devotion -> Attacked**
The damage received by target must be the real damage taken, but in current rAthena "if target is devoted and the RG has Defender, the damage will reduced". This is wrong, the Defender must not be active for the 'just' Devoted player, RG must recast Defender again. So, in your first picture because of this behavior.
Remove the lines above should fix issue.
https://github.com/rathena/rathena/blob/e172c4365d4680fbc7c797a4a7fdb9bd88105d3c/src/map/battle.cpp#L1304-L1318

**~~Defender~~ -> Devotion -> Defender -> Attacked**
This is the real effect, the attacked target will have Defender damage reduction bonus, but because of the behavior above, the reduction is taking twice.
https://github.com/rathena/rathena/blob/e172c4365d4680fbc7c797a4a7fdb9bd88105d3c/src/map/battle.cpp#L1331-L1348

**Comment by admkakaroto** [comment]
Thanks master cydh.
