### ISSUE TITLE
@changegm during WoE

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#410]
I think @changegm should be disable during WoE, but my players can @changegm during WoE. is it actually available ? Because some of my players said that it can make map server crash
*sorry no log for this issue.

**Comment by aleos89** [comment]
This would be more of a suggestion rather than a bug. It's a custom command and usually isn't available to players. The easiest thing to do is to make the checks yourself to disable the command during WoE in the source.

If it's actually making the server crash then this would be valid, but it would be nice to have a core dump or something.
