### ISSUE TITLE
Pet Return to egg shell (Does not work)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4116]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3057af757dc005baaa8f95a42bac194c47129dc6

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: The Pet is not returning to the egg. Clicking on the option nothing happens.
NOTE: The SQL update of this issue has already been applied and did not solve:
https://github.com/rathena/rathena/issues/4075
https://github.com/rathena/rathena/commit/7f19772ed14222b46d661a110c9ff8c818087b8b

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Badarosk0** [comment]
I let the pet die and then it started working. It's OK.

**Comment by Badarosk0** [comment]
https://github.com/rathena/rathena/issues/4178

**Comment by Indigo000** [comment]
Has any progress been made on this by any chance? People seem to be breaking their pets all over the place on our server, too.

**Comment by sader1992** [comment]
@Indigo000 
this maybe related, you can test it and give feedback if you had
https://github.com/rathena/rathena/pull/4179

**Comment by Indigo000** [comment]
Alright, I think we found out what's causing this. At least in our case, it only seems to apply to pets that were **already incubated** prior to the revamp that came with the Pet Evolution commit.

Previously, rAthena deletes the pet egg from the player's inventory when a player spawns a pet. When you do Return to Egg, it simply loads the data of your current pet and creates a -new- Egg in your inventory.

The new approach does it differently. When you incubate an egg, it doesn't delete the egg. Instead it sets the "attribute" to 1 which basically hides the egg from your inventory. The egg is technically still there. Now, when you use Return to Egg, it searches your inventory for items with your Pet ID and unhides it.

Now, the problem is that if you had a pet already incubated -prior- to this change, there is no egg in the inventory, because of the different approach. Now with the new approach, it cannot find a hidden pet egg in your inventory and thus fails to put the egg back.

**Comment by luffydmkey** [comment]
occurs when item resetting the inventory or deleting the egg, when the pet is out. usually petegg takes a slot in the inventory even if hatched. This also removes the option autofeeding and evolution of the pet from the client. System/PetEvolutionCln.lub or PetEvolutionCln_true.lub
