### ISSUE TITLE
Item bonus stacking 'bHPRegenRate' and 'bSPRegenRate'

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#4279]
* **rAthena Hash**: 90d603d14

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Bonus 'bHPRegenRate' and 'bSPRegenRate' cannot be stacking.
  * Expected Result: Bonus 'bHPRegenRate' and 'bSPRegenRate' can be stacking.
  * How to Reproduce: Use 2+ item bonus
  * Official Information: -

* **Modifications that may affect results**: 
pc.cpp line 3770
`
sd->hp_regen.value = type2;
sd->hp_regen.rate = val;
`
to
`
sd->hp_regen.value += type2;
sd->hp_regen.rate += val;
`

pc.cpp line 3862
`
sd->sp_regen.value = type2;
sd->sp_regen.rate = val;
`
to
`
sd->sp_regen.value += type2;
sd->sp_regen.rate += val;
`

**Comment by aleos89** [comment]
Considering this has been the behavior since it was implemented in 2007 (88e0559d2c5b27d4f146538d309bfafb93a1a9c3) it's hard to say without testing on kRO. It would seem logical that the bonuses do stack though.

**Comment by SeravySensei** [comment]
+= is incorrect? Gaining 2 hp every 3 seconds and 1 hp every 6 seconds gains 5 hp every 6 seconds instead of 3 hp every 9 seconds (which btw is less than what you get if you only have one kind of bonus so stacking with += here is even worse than not stacking at all). (I'm assuming type2 and val refer to n and t from the documentation)
Correct way of stacking is to use an array to store each different time interval separately.
Which, by the way, seems to be already a bug for bonus2 bHPDrainRate,x,n and bonus2 bSPDrainRate,x,n both of which use +=. Likewise, 10% chance to drain 5% hp twice is 20% chance to drain 5% hp, not 20% chance to drain 10% hp (which is four times as powerful instead of twice). Same issue for bonus2 bAddGetZenyNum,x,n?  These things need to use an array if they stack. There might be more I only looked at a few of them. But many things do use an array as expected.
Of course it's possible the official behavior has this kind of bug making it "correct" that way but even then an option to disable the official bug would be nice.
