### ISSUE TITLE
3rd Job 255 lvl max no aura shown

### ISSUE THREAD

**Issue by toysin666** [rathena/rathena#4315]
* **rAthena Hash**: Latest

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: The aura literally not showing upon 3rd job change - max base lvl 255. Only 3rd job is set 255 max base level, the rest is by rAthena default.

  * Result: Aura is perfectly working on default base level = 99 max normal-2nd classes. 
It simply disappears upon 3rd jobs change, 255 lvl base. 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:   
  

* **Modifications that may affect results**:  Tried plenty of tweaks on both server and client-side including /data/ .grf modification of _ExternalSettings_kr.lub_ & _External_kr_sak.lub_ but no luck of any aura showing.

ExternalSettings_kr_sak.lub
```
MaxLevelTable = {
	BaseLevel = 255,
```

/map.h
`#define MAX_LEVEL 255
`
/client.conf
```
max_lv: 255

aura_lv: 255
```

/battle.cpp
```
"max_lv",   255,     0,      MAX_LEVEL,
"aura_lv",  255,     0,      INT_MAX,  
```

**Notes: Client diff _(Use Custom Aura Limits)_ with NEMO, resulting client crashed/not responding after char select, unsuccessful login.

**Comment by bgamez23** [comment]
this is not server side issue. this issue is on client side. btw the aura works fine if you set the max level aura on your client.

![image](https://user-images.githubusercontent.com/1854368/64977590-45678280-d8e6-11e9-88b9-939418a6e524.png)

![image](https://user-images.githubusercontent.com/1854368/64977605-4d272700-d8e6-11e9-9863-ec31cb70dbd5.png)

**Comment by aleos89** [comment]
This is a configuration/client issue.
