### ISSUE TITLE
[Error]: intif_parse_Mail_delete: char not found

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4322]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: If a character has been deleted and the email is deleted then this error message occurs in the console.

Example:
[Error]: intif_parse_Mail_delete: char not found 161096
[Error]: intif_parse_Mail_delete: char not found 161096

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
```cpp
	// Only if the request came from a map-server and was not timer triggered for an offline character
	if( fd <= 0 ){
		return;
	}
```
This check should prevent that packet from being sent back to the map-server.

**Comment by Lemongrass3110** [comment]
I have discussed this with @Badarosk0 on Discord. It is probably related to high latency between char<>map server.

Nothing to worry about though, since it is just a notification that a mail has been deleted, that will not be forwarded to the player. It was already saved by the char server, so everything is fine.
