### ISSUE TITLE
Bug Reflect Damage (Item bonus+Skill Reflect)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4343]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: When using any item that adds melee reflect damage the reflect to the target occurs only up to the HP size of the player who received the damage. 
The problem also occurs with skill Reflect.

  * Result: 
It is only reflecting up to the size of the HP from who received the damage, who had a reflect bonus. Example who has the card Orc Lord.
  * Expected Result:
 It should reflect the full percentage of the item used and not the size of the HP.
  * How to Reproduce: 
Equip an Orc Lord card. Take a Sura and Azura strike the target. The reflected damage will be the target's HP value.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Most likely because of this define: `int max_damage = status_get_max_hp(bl);` add here: ad11dd6.

Although, does it matter? The maximum possible damage you could do is the target's HP. It would be nice to see the initial bug report from the old tracker. Guess we need to see if Aegis is capping it as well.

**Comment by aleos89** [comment]
Fixed in [33a99b5](https://github.com/rathena/rathena/commit/33a99b59931346097c684c305c58a4eae97088e7).
