### ISSUE TITLE
Self-cursing item problem and possible bAddEff2 problem

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4371]
Some items, like https://www.divine-pride.net/database/item/2652/goddess-of-fortunes-cursed-brooch curses the owner at a chance.
Resistance to curse is applied to this self-inflicted effect, however formula is
sc_def2 = status->luk*10 - status_get_lv(src)*10;
Resulting in a fairly large negative number.
This is then added to the success chance at
rate -= sc_def2;

Edit : reading the scr again I now understand that sc_def is the percentage and sc_def2 is the additive resistance so considering both are implemented separately I'm sure the status resistance implementation is correct.
However the question remains : Is bAddEff(2) supposed to have a 100% chance to cause a status effect with x% base success rate, or is it supposed to have an x% chance to causes a status effect with a 100% base success rate?
Due to the existence of additive resistance these two are not interchangeable and the current implementation causes unexpected and counter-intuitive behavior on at least the effects like Curse where self-inflicting the status comes with a large addition to the rate causing rates below 1% chance to grow to well over 10% without an apparent reason.

**Comment by Walneiros** [comment]
I am trying to play a Knight with Muramana, and the curse happens every 10 attacks or so, instead of the very low 0.1% chance.
I do believe this is a bug coming from bAddEff2, but maybe is it like this on official servers ?
I don't recall that the curse what that frequent.

**Comment by Playtester** [comment]
This is official behavior. Each level of the target increases the final chance by 0.1%. That include cursing yourself through effects like Murasmasa / Cursed Brooch.

That's the reason why official Muramasa guides say you need one more Luk than your level (because each Luk reduces the final chance by 0.1%).

At level 99, that would be 10% extra chance to be cursed, assuming you had 0 Luk. If you have say 30 Luk that would be 7%, and 4% chance if you are under the effect of Gloria.

If you need more information about pre-renewal status changes you can check my guide on RMS: https://forum.ratemyserver.net/guides/guide-official-status-resistance-formulas-(pre-renewal)/
