### ISSUE TITLE
Waring every start server in CentOS

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#442]
![ra](https://cloud.githubusercontent.com/assets/9112684/7687458/a89b6e42-fdc7-11e4-84d6-46c85d78b2e8.jpg)

[Warning]: socket_init: failed to set socket limit to 1024, setting to maximum allowed (original limit=100, current limit=100, maximum allowed=100, error 1: Operation not permitted).

**Comment by hnomkeng** [comment]
I have root user, need change 1024 to limit.

**Comment by Akkarinage** [comment]
This isn't alot of info..
Git Hash:
Src Edits:
Max Connections Config Setting:

I assume i know the answer, but for the purposes of writing effective bug reports, can you also state on which console this is, including what you changed in order to receive the error.

This also isn't really a bug report, it's user error.

**Comment by hnomkeng** [comment]
i need set Server support over 2048 default 1024

ex. https://rathena.org/board/topic/87242-how-can-i-set-centos-to-support-over-1024-concurrent-connection/

**Comment by nanakiwurtz** [comment]
Check your /etc/security/limits.conf

**Comment by hnomkeng** [comment]
![3333](https://cloud.githubusercontent.com/assets/9112684/7701437/4eee72b0-fe51-11e4-9780-dea5860d01fe.JPG)

**Comment by Akkarinage** [comment]
This is not an rA bug. Closing issue.
