### ISSUE TITLE
Leech End + Sit (windmill, moon slasher, etc)

### ISSUE THREAD

**Issue by firecroll** [rathena/rathena#448]
When someone puts Leech End on you, be Guillotine Cross or Chaser infected with leech end + deadly infect, if someone sits you with any skill like windmill or moon slasher (chaser can do both infect + sit you, so they tend to get advantage of this), leech end will "stand you up" but you will still be sit down. Therefore, every time you want to stand up the char will sit down again not taking off the sit buff and the only way to do it correctly is doble pressing as fast as you can the ins boton between dots of leech end and pray you could stand up XD. Leech end damages you, so it should stand you up the moment you get hit by it but it really doesnt. If you need SS just tell me and ill edit this, but its easy to test yourself and easier to undertand if you do it.

**Comment by cydh** [comment]
something tricky exploit. I'll ask @aleos89 to test later. xD

**Comment by firecroll** [comment]
Easier to test, Just frost someone and put leech end, it wont break the freeze.

**Comment by MrAntares** [comment]
A stupid question: Shouldn't ANY damage cancel sit?

**Comment by firecroll** [comment]
Still cant confirm this? If you need more info in some way i can retest things and record it or anything you want.

**Comment by raynra** [comment]
I just tested this on latest GIT, and issue appears to still exist.

My test:
- have player infected with Leech End
- they will bleed and take damage every second
- sit (either from skill, or INS or /sit)
- leech end will take damage the following second, and player will appear to be standing up after damage, but sit status icon still shows, player cannot move
- successfully pressing INS or /sit does not stand the player
- player must INS or /sit twice within a second after taking damage, but before next damage, in order to sit+stand quickly to get rid of the sit status

**Comment by Playtester** [comment]
Problem here is that the pc_damage will not execute fully if the damage source is "self", but my tests on official servers showed that it should execute. Self damage makes you stand up server-sided and even prevents you from logging out.

This is in contrast to "NULL" damage (all damage that does not display, like from poison), which neither makes you stand up, nor prevents you from logging out.

As I'll remove the self requirement in my next big update, I'll assign this one to myself.

**Comment by stealth62** [comment]
:+1:
