### ISSUE TITLE
This expandinventory script command is hoped to be added in rathena!

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#4513]
There is this script instruction in Hercules, hope to be implemented in rathena, Thanks!!

*expandinventory(<value>)
Adjust player inventory to given value.
Maximum inventory size is MAX_INVENTORY.
Minimum inventory size is FIXED_INVENTORY_SIZE.
For supported clients it send inventory change packet. For old clients,
this change is silent.
Current max inventory size can be read by function getInventorySize().

**Comment by Lemongrass3110** [comment]
Follow the issue template

**Comment by dimasshotta** [comment]
![screenrAthena193](https://user-images.githubusercontent.com/74591268/117918924-40a2de00-b316-11eb-998e-9795a9d6f88a.jpg)
![screenrAthena194](https://user-images.githubusercontent.com/74591268/117918969-5adcbc00-b316-11eb-9b48-21ddad6e9324.jpg)
i wish someone help with the packet.. the issue is only in the packet.. i guess i manage to implement expandinventory and getinventorysize
