### ISSUE TITLE
Missing Waiting Room Chatroom on Assassin and Knight Job Quest NPC

### ISSUE THREAD

**Issue by yashimwong** [rathena/rathena#4588]
* **rAthena Hash**: Latest

* **Client Date**: 
Irrelevant

* **Server Mode**: 
Both

* **Description of Issue**: 
  * Result: Test Waiting Room Chatroom in job change quest knight.txt and assassin.txt missing
  * Expected Result: Test Waiting Room Chatroom must be there during jobchange
  * How to Reproduce: Start server and perform job change quest for either knight or assassin.

* **Modifications that may affect results**: None

* **Additional Info**:
```
job_knt,89,106,4	script	Windsor Benedict#knt	733,{
	end;

OnInit:
	//disablenpc "Windsor Benedict#knt";
	waitingroom "Waiting Room",20,"Windsor Benedict#knt::OnStartArena",1;
	enablewaitingroomevent;
	end;
```

```
in_moc_16,21,165,2	script	Standby Room#ASNTEST	725,{
	end;

OnInit:
	//disablenpc "Standby Room#ASNTEST";
	waitingroom "Standby Room",10,"Standby Room#ASNTEST::OnStartArena",1;
	enablewaitingroomevent;
	end;
```

Upon disabling the disablenpc line for both job quest, the issue is somehow solved and no unwanted behaviour occured.

**Comment by Daegaladh** [comment]
I don't understand what do you mean, the chatrooms are always there, that disablenpc just disables interaction with the NPC that produces the chatrooms, because there's another NPCs in the same coordinates (the ones you can see) and that avoids overlapping.

I've tested both on the lastest rathena and they work as intended.
