### ISSUE TITLE
VARETYR SPEAR

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#4622]
* **rAthena Hash**: LATEST

* **Client Date**: DEFAULT RATHENA

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: wrong cast range when using level 6 to 10 varetyr spear
  * Expected Result: 
  * How to Reproduce: cast lvl 6 to 10 varetyr spear to a player or monster.
  * Official Information:not sure how many cells when casting a sorcerer spell
  

* **Modifications that may affect results**: NONE

**Comment by secretdataz** [comment]
Not related to rAthena.
You need to adjust the client-side attack range in the lua file.

**Comment by Miraakol** [comment]
im sorry but where can i get updated lua files for that issue? thanks in advance!

**Comment by secretdataz** [comment]
Update your installation to latest kRO patch with RSU patcher then grab it from your data.grf.
Please direct other questions to our forums or our Discord server as this is not a development issue.

**Comment by OptimusM** [comment]
> Update your installation to latest kRO patch with RSU patcher then grab it from your data.grf.
> Please direct other questions to our forums or our Discord server as this is not a development issue.

@Miraakol Do it carefully and just take what Secret said, because if u just grab it all the rdata or data content, it will crash your client whit the map format, some old monsters new format, some skills and so on, so, try to use an old GRF, maybe before than november 2018 or u will have countless Exe/GRF problems.
