### ISSUE TITLE
Earth Drive AoE

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4859]
* **rAthena Hash**: 05ebde0

* **Client Date**: 20180620RE

* **Server Mode**: RENEWAL

* **Description of Issue**: skill does not match the description of the kRO Earth Drive LV1 same as Earth Drive LV5
  * Result:  ED LV1
![screenRENEWAL1152](https://user-images.githubusercontent.com/8316103/80556609-517bfc80-89fe-11ea-9218-7b98739ab629.jpg)

  * Result:  ED LV5 is like only 3x3
![screenRENEWAL1154](https://user-images.githubusercontent.com/8316103/80556858-3067db80-89ff-11ea-81dd-32be7e3aabd3.jpg)

  * Expected Result: 
	[SKID.LG_EARTHDRIVE] = {
		"Earth Drive",
		"Max Level: 5",
		"^CC3399Requirement: Reflect Damage 3^000000",
		"Skill Form: ^FF0000Offensive^000000",
		"Description: ^777777Brandishes your shield to",
		"attack all targets in an area to receive",
		"Earth elemental damage. Targets hits",
		"by this skill will have their defense",
		"and attack speed reduced by 25%.",
		"The weight of your shield affects the",
		"damage dealt.^000000",
		"[Lv 1]: ^7777773x3 AoE, 3 second duration^000000",
		"[Lv 2]: ^7777773x3 AoE, 6 second duration^000000",
		"[Lv 3]: ^7777775x5 AoE, 9 second duration^000000",
		"[Lv 4]: ^7777775x5 AoE, 12 second duration^000000",
		"[Lv 5]: ^7777777x7 AoE, 15 second duration^000000"
	},
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by LordWhiplash** [comment]
Check your skill_db.yml, mine is like this:

![image](https://user-images.githubusercontent.com/62680611/80558595-4e0e5400-89b1-11ea-8847-3e60e4ce492e.png)

and the area is 7x7 (3 cells for each side of the character)

![image](https://user-images.githubusercontent.com/62680611/80558539-1bfcf200-89b1-11ea-8e2a-6053a99445cb.png)
(Level 5 Earth Drive)

![image](https://user-images.githubusercontent.com/62680611/80558656-8ada4b00-89b1-11ea-9537-1714486b74c6.png)
(Level 1 Earth Drive, don't aply damage since it is 3x3 and i'm 3 cells away)

Be sure about the distance damage is applying testing in an imobile monster, not just looking at the animation.

**Comment by mazvi** [comment]
Okay thanks for your reply.. i miss understand about cell.. but now i understand :)
