### ISSUE TITLE
SJ_STARSTANCE, SJ_LUNARSTANCE doesnt give bonus status

### ISSUE THREAD

**Issue by qwerty7vp** [rathena/rathena#4875]
* **rAthena Hash**: 4829f3775

* **Client Date**: 20180919Ragexe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Both Stances dont give bonus status
  * Expected Result: Should give bonus status correctly
  * How to Reproduce: Create Star Emperor and use those stances
  * Official Information:
  

Lunar Stance
![image](https://user-images.githubusercontent.com/64515036/80779206-1fe96980-8b95-11ea-98b9-345834e0cf75.png)

Star Stance
![image](https://user-images.githubusercontent.com/64515036/80779282-650d9b80-8b95-11ea-9551-abd09a1ce4e4.png)

* **Modifications that may affect results**: Nothing
`

**Comment by LordWhiplash** [comment]
I've looked at this yesterday, and noticed that too, thanks for reporting.
Not sure, but i think the problem of this stances are in status.cpp

![Screenshot_20200502-025005](https://user-images.githubusercontent.com/62680611/80856549-79977580-8c21-11ea-8133-a9185c364c67.png)
(Star Stance is in a section about preRE aspd, and i dont know if it is really suposed to be "-=" instead of "+=")



![Screenshot_20200502-024856](https://user-images.githubusercontent.com/62680611/80856541-4c4ac780-8c21-11ea-9435-bfb580f43655.png)
(I think it need to be here)

About the lunar stance, seems that the defined val2 is divided for 100, i mean, when lunar stance is level 3, val2 = 5, and divided by 100, becoming 0,05% of your Max hp, that would increase your HP in 8 if your MaxHP in the screenshot is clean 16723 (strange, since it did not increase at all)

![Screenshot_20200502-025518](https://user-images.githubusercontent.com/62680611/80856949-ac8f3880-8c24-11ea-98b5-b2734cb0b279.png)
(Val2 definition)


![Screenshot_20200502-025452](https://user-images.githubusercontent.com/62680611/80857042-553d9800-8c25-11ea-9b17-11ba91a1c815.png)
(Bonus HP definition)

**Comment by Latiosu** [comment]
@LordWhiplash You were on the right track.
SJ_STARSTANCE wasn't applying attack speed effect in renewal since there wasn't a condition for it in `status_calc_aspd`.
Max HP calculations are casted to integers so a value of 0.05% would become 0% but removing the division by 100 is the correct fix for SJ_LUNARSTANCE.

**Comment by LordWhiplash** [comment]
Oh, good to know about it, thank you for fixing it!

**Comment by Latiosu** [comment]
Official Information from kRO (Divine-Pride):
http://www.divine-pride.net/database/skill/2575/sj-lunarstance
![image](https://user-images.githubusercontent.com/7020503/80899244-47853100-8d51-11ea-8281-d1576cc2be07.png)

http://www.divine-pride.net/database/skill/2578/
![image](https://user-images.githubusercontent.com/7020503/80899249-6388d280-8d51-11ea-8788-747f5114d37a.png)

**Comment by aleos89** [comment]
Fixed in 24ea092.
