### ISSUE TITLE
Client 2014-10-22[Show Mob HP]

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#490]
Hi.
// Display some mob info next to their name? (add as needed)
// (does not works on guardian or Emperium)
// 1: Display mob HP (Hp/MaxHp format)
// 2: Display mob HP (Percent of full life format)
// 4: Display mob's level
show_mob_info: 

Doesn't seem to take any effect to the new client.

Any idea why?

**Comment by samurairukasu** [comment]
Its not a bug, is a config set and a command (/showname) that u need to take in consideration in game.

For example: 
(server side)
show_mob_info: 1 // this only will show mob HP with full bar
show_mob_info: 2 // this only will show mob HP in % number
show_mob_info: 4 // this only will show mob level

show_mob_info: 6 // this will show mob HP in % Number and mob level - (option 2 + option 4) = 6

Client side:
U must use command /showname in game or it will not show u the mob HP % and level for option 6. This is because the client is set to use showname language Type 1 by default, and the mob HP/Level need Type 2 to be show in screen.

Only set show_mob_info to the value u want and use command /showname in game.

**Comment by aleos89** [comment]
As @samurairukasu said, it's not a bug, but just that you need to enabled /showname to get the detailed info.
