### ISSUE TITLE
Old Glast Heim instance update

### ISSUE THREAD

**Issue by XDXDMAN** [rathena/rathena#493]
http://herc.ws/board/topic/9940-complete-old-glast-hein-instance/

https://code.google.com/p/idathena/source/browse/trunk/npc/re/instances/OldGlastHeim.txt

Old Glast Heim instance script update from Hercules(topic) and idathena(script).
This script add some Rathena have yet to npc.

**Comment by cydh** [comment]
I ever talked about this with @aleos89 and the case is, every changes entitle 'official' from idAthena are questionable "from where the source? is it reliable?" since idAthena almost never put any source on they/he made (except from merge).
I leave this for @Atemo @euphyy if maybe they have info related this

````
//= 1.2 Add NPC Hugin's Follower [exneval]
//=     NPC that give access to Glast Heim Nightmare Mode.
//= 1.3 Add some NPCs placeholder. [exneval]
//= 1.4 Update to its official text. [exneval]
````

**Comment by XDXDMAN** [comment]
OK

**Comment by zackdreaver** [comment]
I wonder if there any info about the "Nightmare Glastheim" ?
It just a "normal" map with high level mob, you need an NPC (Hugin's follower?) to teleport you there.

http://www.divine-pride.net/database/map/gl_chyard_
http://www.divine-pride.net/database/map/gl_cas02_

iRO has implemented this i believe.
