### ISSUE TITLE
Looter Mobs paralyzed

### ISSUE THREAD

**Issue by iraciz** [rathena/rathena#4941]
* **rAthena Hash**: last

* **Client Date**: 20180620 RagexeRe

* **Server Mode**: pre-renewal

* **Description of Issue**: Looter monsters freezes when trying to pick items
  * Result: Monsters stay steady in their cells, not move when trying to pick up certain items
  * Expected Result: They should move, walk and get items before and after an attempt, not stay steady.
  * How to Reproduce:  First drop at least 5 or more items, Second step, summon 3 or 4 or 5 Porings, Poporings, Drops, or any looter monster even tatachos, and there you go, the mobs at certain point will never move again. They will end stuck in the eternal journey of picking an item even if it dissapear, even if you try to lure them dropping another one, Agressive will not go after you and that can be exploited. 
  * Official Information: This only happens here.
  

* **Modifications that may affect results**: No moods, I tested this today! in a clean recent downloaded head revision emulator from rahena branch, everyting is default.
  
  
Got the client exe from user @MathReaper : 
https://rathena.org/board/topic/117168-packetver-20180620-client-release-2018-06-20eragexere/ 
Only recommended diffs were applied, and note that  most of the 90% of the rAthena users are using the same client.

**Comment by iraciz** [comment]
Here's the video
https://www.youtube.com/watch?v=MwAfNFswWK0&feature=youtu.be

If you are unable to reproduce this, please share your client and diff, I'm tired of this problem...

**Comment by iraciz** [comment]
This is related to #4853 and is a client side problem not sending the packets, 
Nothing to do here.

**Comment by SeravySensei** [comment]
I tested a little and it only happens when two looter mobs reach the same loot at the same time.
I think it's a server issue, should be reopened.
In particular, the stuck poring has a target_id. But there is this line : `if(md->ud.walktimer != INVALID_TIMER && (!can_move || md->ud.walkpath.path_pos <= battle_config.mob_chase_refresh)
				&& (tbl || md->ud.walkpath.path_pos == 0))
				return true; //Walk at least "mob_chase_refresh" cells before dropping the target unless target is non-existent
`
In particular in my test case md->ud.walkpath.path_pos == 0 was true which caused the tbl condition to have no effect. So the Poring is eternally stuck waiting to move before dropping the invalid target (the item already looted probably by the other poring). The "path" was a single tile length path containing only a step to "center". 
Here is the debug :
[https://drive.google.com/file/d/1j3Mg3S8OpiBuA0QBK0whcaDe9f9GvB-A/view?usp=sharing]
Removing the walkpath position check fixed the problem but also makes all porings stop instantly so it probably isn't the correct solution.

**Comment by iraciz** [comment]
Edit : changing the line to
&& (tbl || ((md->ud.walkpath.path_pos == 0) && !(md->ud.walkpath.path[0]==DIR_CENTER))))
fixes the bug without making the mobs stop early.

Awesome, this solves this issue, I'm not experiencing this anymore.

**Comment by qwerty7vp** [comment]
> Awesome, this solves this issue, I'm not experiencing this anymore.

since you tell that This problem is related to #4853 
the changing from Seravy solved that too ?

**Comment by iraciz** [comment]
> > Awesome, this solves this issue, I'm not experiencing this anymore.
> 
> since you tell that This problem is related to #4853
> the changing from Seravy solved that too ?

The answer is no, @SeravySensei   fixed mob.pp line #1727  only the mob looting behavior, not the player involved movement, I'm not sure, but it could be that the key is in the lines of player.c or pc.c

**Comment by aleos89** [comment]
This goes back to b6b6b13. Assuming from @Playtester's comment, the mobs should stop if they lose sight of their target (the item). So dropping the path_pos should be enough.
