### ISSUE TITLE
Doram - Hiding Skill strips gear

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#4953]
* **rAthena Hash**: 9389b7d

* **Client Date**: 2018-02-21bRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Getting warped takes off your entire gear.
  * Expected Result: Not stripping of anything at all.
  * How to Reproduce:
1. Use a doram/summer, while wearing a full set of gear.
2. Use summoner Hiding skill
3. Now use any kind of warping command or being forcefuly warped by a script to change the map. (getting warped out of battlegrounds, use ``` `@go` ```, ``` `@warp` ``` and so on...)
4. Your entire gear has been taken off: ![image](https://user-images.githubusercontent.com/12261601/81935576-23e3a580-95f1-11ea-9621-1880c7946245.png)

  * Official Information: Official behavior is unknown to me.

* **Modifications that may affect results**: 
  None

**Comment by aleos89** [comment]
```cpp
		if(item->equip && (sd->sc.data[SC_KYOUGAKU] || sd->sc.data[SC_SUHIDE]))
			return ITEM_EQUIP_ACK_FAIL;
```
It is because of this line. You are unable to switch equipment while hiding, so on a map change it's re-calculating your equipment and because of this status it's returning failures which is unequipping your items.

There's no real way to replicate this on kRO without GM commands to move maps. The easiest solution is to just end the status when changing maps before the equip check.
