### ISSUE TITLE
Glast heim challenge mode items

### ISSUE THREAD

**Issue by haurenburu** [rathena/rathena#5049]
- **rAthena Hash:** 444ad78

- **Client Date:** 2020-04-01bRagexe

- **Server mode:** Renewal

- **Description of Issue:**
missing items from oghcm update: https://www.divine-pride.net/forum/index.php?/topic/3879-kro-glast-heim-challenge-mode-enchant/

**Comment by tumemmac** [comment]
Do you have instance OGH Challenge Mode Script?

**Comment by OptimusM** [comment]
@tumemmac 
I dont think rA will implemented that atm because not even in kRO people are able to finish the last phase of the instance, so, no one can extract information or behavior of the complete instance behavior.

I mean, could be made, but it will be obviously a custom implementation.
Beside of that, rA are actually missing alot of new skills and mvp behavior, so, it will be good if that could be done first.

**Comment by haurenburu** [comment]
rathena already has a bunch of items from unreleased content i think thats not a problem at all

**Comment by Atemo** [comment]
The items have been implemented in https://github.com/rathena/rathena/commit/3dcfcf9f1125378f714508d231941b8e0d30c2f2 after the item txt to yml. Thanks!

**Comment by rainer8989** [comment]
Can someone add to pull maybe beta script of glast heim challenge mode?
