### ISSUE TITLE
Some skills in Renewal Servers

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#507]
Some skills are disturbing the players. They note that the following skills are unregulated or do not follow the official behavior.

Acid Demonstration:
-A.D. gets element modification

 Voice of Siren (Skill ID# 2420, iRO Name: Siren's Voice):
-Works less than 1 sec in chars above level 175

**Comment by philg666** [comment]
In kRO Acid demonstration is always forced neutral but it is an official behavior to add some damage modifiers from elements (but always return neutral dmg)

For Voice Of Siren name check your data folder and/or update your data

For the duration : 
http://irowiki.org/wiki/Siren's_Voice
You said for chars above lvl 175... the more the target is high lvl (both base and job) the less time it will be active, so that may be depending on what is your max lvl in your server.

**Comment by aleos89** [comment]
I wouldn't say Voice of Siren is our problem. Officially 175 is the max level and as it stands now works just fine.

**Comment by Playtester** [comment]
Tested duration of Voice of Siren:

Skill 1 - Level 99/70 or 150/50 or 100/50 = 4-5 Hearts = ~10 seconds
Skill 3 - Level 99/70 or 150/50 or 100/50 = 4-5 Hearts = ~10 seconds
Skill 5 - Level 99/70 or 150/50 or 100/50 = 4-5 Hearts = ~10 seconds

Skill 1 - Level 18/11 = 5 Hearts = ~11 seconds
Skill 3 - Level 18/11 = 8 Hearts = ~17 seconds
Skill 5 - Level 18/11 = 11 Hearts = ~23 seconds

Skill 1 - Level 22/70 = 4-5 Hearts = ~10 seconds
Skill 3 - Level 22/70 = 4-5 Hearts = ~10 seconds
Skill 5 - Level 22/70 = 5 Hearts = ~11 seconds

Conclusion: While our base duration and reduction is already correct, there seems to be a min duration of 10 seconds we haven't implemented yet. Reopening this.
