### ISSUE TITLE
Genetic Shoropo Bug

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#524]
The skills shows attack but nothings happen to enemy

**Comment by RagnarokNova** [comment]
You mean Genetic Spore Explosion right?

**Comment by aleos89** [comment]
Just tested and I was able to damage my target. Make sure you have the Bomb Mushroom Spore (6212) in your inventory. Also keep in mind there is a delay after the skill is used before it explodes.

**Comment by RagnarokNova** [comment]
Was also able to reproduce this. These tests are all being done on a clean rA downloaded a few minutes ago from the git.
http://i.imgur.com/btsUzcG.png
http://i.imgur.com/442AQsH.png
Poring not dead. Not even aggro.

**Comment by aleos89** [comment]
Ok I just tested this again with hash c4dab3c. I used Spore Explosion on a monster in PvP and Non-PvP (since I saw that in your images) and after a few seconds the spore exploded and killed the monster. Tried it against @spawn'ed monster and naturally spawned monster, both died normally from the explosion.
