### ISSUE TITLE
Mystical Amp Revamp to continued buff and add icon status 

### ISSUE THREAD

**Issue by as70873463** [rathena/rathena#5242]
rAthena Hash: 
Client Date: 20200715
Server Mode: Renewal
Description of Issue: I want update skill and icon status to kro official.
![RO_MysticalAmplificationIcon tga](https://user-images.githubusercontent.com/20542927/88214576-9a9dbe80-cc84-11ea-8ad8-c85f4848c8c3.png)
Result: 
How to Reproduce:
Official Information: [https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/8/&tab=comments#comment-7777](https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/8/&tab=comments#comment-7777)
Modifications that may affect results:

**Comment by aleos89** [comment]
If you could fill out the report using the template it will help with tracking. Thanks.

**Comment by aleos89** [comment]
From your link, that's the post 3rd class update, which hasn't made it's way to main yet. Because of that, this could change or be completely nullified. I'll close this for now because we will eventually have a new issue created for all the classes that were changed, rather than the individual skills.
