### ISSUE TITLE
Item: Explosive Kunai

### ISSUE THREAD

**Issue by FrFrMako** [rathena/rathena#534]
Can't equip explosive kunai with a character level 100 and above.

**Comment by aleos89** [comment]
I would assume it's because of a mis-translated description. The description from ROClientSide/Translation states "Level Limit: 100" but on iRO DBWiki it states "Required Level: 100".

**Comment by nanakiwurtz** [comment]
Which one to choose?

**Comment by aleos89** [comment]
It's a complete assumption (I haven't searched more to confirm the correct data of it) but I would say that "Level Limit" means "Required Level". So minimum level to equip it would be 100. This being since to become a Kagerou/Oboro, you must be a 99/70 Ninja. This is to keep Ninjas from equipping the Explosive Kunai and reserving it only for Kagerou/Oboro.

So just removing the "1:" from the level requirement section of the item should fix it.
