### ISSUE TITLE
Suggestion: Option to enable future Critical nerfs from kRO

### ISSUE THREAD

**Issue by HenryAlvarez12** [rathena/rathena#5406]
Hello,

right now, on 99% of the servers GX and RK dominate like mad. With very little effort and very little equipment (budget builds) they make every other class look extremely bad and rAthena also does not have the content to match this power creep. 

I feel like we got these balance changes too early (even though its official). This causes a lot of complaints from players who play other classes and I'm sure everyone understands it. 

My suggestion would be to implement the future kRO nerfs in critical / gx skills / rk skills, BUT with a toggle. So whoever does not want these nerfs just yet can disable them. 

I know this ain't an "issue" and it's a very unusual thing to do for rAthena but I really didn't know where else to post this, since the forums are more dead than anything. 

I believe this "issue" was worth opening since before we got the balance updates, the game felt somewhat "balanced". it feels extremely messy right now.

**Comment by SoulboundRO** [comment]
Please doing this.
Assassin in mora equipment do 20m

**Comment by poporing** [comment]
@HenryAlvarez12  Hi do you have any official info about the nerf?

**Comment by aleos89** [comment]
I think this was discussed in one of the other issues. The thing is for some skills this would be a simple thing but for others it becomes complicated because of a major rework of the skill.
Examples:
1. Bash receives a damage increase -> simple with a battle_config.
2. Comet receives cast time changes -> this becomes more complicated because now we have differences in cast times. There's no way to differentiate this unless one version is hard coded into the source which defeats the purpose of the skill_db and one of our goals it to avoid hard coding as much as we can.

This just makes for more spaghetti code. Our focus is to match kRO and provide the latest content we can. If you don't agree with a skill change then you're more than welcome to revert the skill to fit your server's needs.

Keep in mind, this is why we have spent a lot of time into producing the import feature for the databases. You can simply copy over the specific skills you want to change into the import file without touching the main file. Skill source on the other hand will just have to be reverted to the old behavior until we modularize skills into classes which will allow for much simpler edits.

**Comment by poporing** [comment]
@aleos89 He his talking about Critical only not skills part. But I duno what nerf he his talking about.
