### ISSUE TITLE
Missing Sql upgrades, to convert the old item_db to new.

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#5499]
* **rAthena Hash**: 8682a9e02eeeef1b445250e5700e629e9f30c890

* **Client Date**: 

2020-09-02

* **Server Mode**: 

PRE / RE

* **Description of Issue**: 
For those who still use the old item_db2 / item_db2_re structure, "sql upgrades" are missing to be able to use the latest rA, so as not to lose items.

**Comment by aleos89** [comment]
There is no method for us to develop a solution for this. You will need to convert your SQL item_db2(_re) database to TXT -> convert to YAML with CSV2YAML -> convert to SQL with YAML2SQL.

The reason I say there is no solution is because the old SQL item_db doesn't contain any of the data from the other TXT item databases (item_trade, item_flag, etc). If we were to provide an upgrade script then your items that rely on values from these other TXT databases will be severely broken as they will just be default (0) values (Say an item that shouldn't be tradeable but now is fully tradeable).

**Comment by zdurexz** [comment]
@aleos89 How to change item_db txt to yml.

**Comment by RagnaWay** [comment]
How convert SQL to TXT ?

**Comment by aleos89** [comment]
I believe [Tokei's database editor](https://rathena.org/board/files/file/3269-server-database-editor/) supports connecting to a SQL db and then exporting it out.

**Comment by RagnaWay** [comment]
Not supported! what a problem now to lose all my items.

**Comment by Atemo** [comment]
https://rathena.org/board/topic/112154-sql-item-database-to-txt/#comment-330236 eventually?

**Comment by aleos89** [comment]
Run this query:
```sql
SELECT
	`id`, `name_english`, `name_japanese`, `type`, IFNULL(`price_buy`, ''), IFNULL(`price_sell`, ''), IFNULL(`weight`, ''), IFNULL(`attack`, ''), IFNULL(`defence`, ''), IFNULL(`range`, ''), IFNULL(`slots`, ''), IFNULL(`equip_jobs`, ''), IFNULL(`equip_upper`, ''), IFNULL(`equip_genders`, ''), IFNULL(`equip_locations`, ''), IFNULL(`weapon_level`, ''), IFNULL(`equip_level`, ''), IFNULL(`refineable`, ''), IFNULL(`view`, ''),
	CASE
		WHEN ISNULL(`script`) THEN "{}"
		ELSE CONCAT("{ ", `script`, " }")
	END,
	CASE
		WHEN ISNULL(`equip_script`) THEN "{}"
		ELSE CONCAT("{ ", `equip_script`, " }")
	END,
	CASE
		WHEN ISNULL(`unequip_script`) THEN "{}"
		ELSE CONCAT("{ ", `unequip_script`, " }")
	END
FROM `item_db`
INTO OUTFILE 'C:/item_db.txt'
FIELDS OPTIONALLY ENCLOSED BY '"'
TERMINATED BY ','
ESCAPED BY ''
LINES TERMINATED BY '\r\n';
```

Change the table and the output location. Open up the resulting file, find `"` and replace with nothing. You now have a SQL -> TXT database.

**Comment by RagnaWay** [comment]
![image](https://user-images.githubusercontent.com/53480357/98298466-cc693580-1f94-11eb-89dd-619c1db51cd1.png)
@aleos89
