### ISSUE TITLE
Found unknown gender 2014 client.

### ISSUE THREAD

**Issue by joven15** [rathena/rathena#5515]
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...

Im actually using a latest rathena emulator downloaded from here. then i use a 2014-04-16aRagexe client. heres the error if i login i saw the warning from charserv.bat. from selection character 4 warning then plus 1 when i already in the map.

btw i use packet_obfuscation.

[Info]: Loading Char Data (2000000)
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Info]: Char load request (150000)
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 2000000), returning account gender...
[Info]: Loaded char (150000 - Joven15): status memo 0 skills friends hotkeys mercenary
[Info]: Selected char: (Account 2000000: 1 - Joven15)
[Info]: Subnet check [127.0.0.1]: Matches 127.0.0.0/255.0.0.0

as you can see im using a latest rathena emulator come from here.

![image](https://user-images.githubusercontent.com/73867685/97963571-5a58eb00-1df2-11eb-8924-c9afe9bc9c6b.png)

* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
You forgot to run sql-files/upgrade_20200604.sql

**Comment by joven15** [comment]
i already read your documentation regarding this i also run the upgrade as
you mentioned but still no luck.

**Comment by Tonipzr** [comment]
In src/char/char.cpp, function char_mmo_gender.

`int char_mmo_gender( const struct char_session_data *sd, const struct mmo_charstatus *p, char sex ){
	switch( sex ){
#if PACKETVER >= 20141016
		case 'M':
			return SEX_MALE;
		case 'F':
			return SEX_FEMALE;
#else
		// No matter what the database says, always return the account gender
		// Per character gender is not supported before 2014-10-16
#endif
		default:
			// There are calls to this function that do not contain the session
			if( sd == nullptr ){
				int i;

				// Find player session
				ARR_FIND( 0, fd_max, i, session[i] && ( sd = (struct char_session_data*)session[i]->session_data ) && sd->account_id == p->account_id );

				if( i >= fd_max ){
					ShowWarning( "Session was not found for character '%s' (CID: %d, AID: %d), defaulting gender to male...\n", p->name, p->char_id, p->account_id );
					return SEX_MALE;
				}
			}

			ShowWarning( "Found unknown gender '%c' for character '%s' (CID: %d, AID: %d), returning account gender...\n", sex, p->name, p->char_id, p->account_id );
			return sd->sex;
	}
}`

As we can see here if PACKETVER is less than 20141016 always execute the default case.

The message "Found unknown gender 'M' for character 'Joven15'" is the correct behaviour.

In your use case is safe to just comment this line (886 in the in the mentioned file), since the only thing it's telling you is that since you use a lower version than the 20141016 it doesn't support sex by character.

Just keep in mind is a warning, not an error.

**Comment by Patotron** [comment]
In src/char/char.cpp, function char_mmo_gender.

```
int char_mmo_gender( const struct char_session_data *sd, const struct mmo_charstatus *p, char sex ){
	switch( sex ){
#if PACKETVER >= 20141016
		case 'M':
			return SEX_MALE;
		case 'F':
			return SEX_FEMALE;
#else
		// No matter what the database says, always return the account gender
		// Per character gender is not supported before 2014-10-16
#endif
		default:
			// There are calls to this function that do not contain the session
			if( sd == nullptr ){
				int i;

				// Find player session
				ARR_FIND( 0, fd_max, i, session[i] && ( sd = (struct char_session_data*)session[i]->session_data ) && sd->account_id == p->account_id );

				if( i >= fd_max ){
					ShowWarning( "Session was not found for character '%s' (CID: %d, AID: %d), defaulting gender to male...\n", p->name, p->char_id, p->account_id );
					return SEX_MALE;
				}
			}

			ShowWarning( "Found unknown gender '%c' for character '%s' (CID: %d, AID: %d), returning account gender...\n", sex, p->name, p->char_id, p->account_id );
			return sd->sex;
	}
}
```
As we can see here if PACKETVER is less than 20141016 always execute the default case.

The message "Found unknown gender 'M' for character 'Joven15'" is the correct behaviour.

In your use case is safe to just comment this line (886 in the in the mentioned file), since the only thing it's telling you is that since you use a lower version than the 20141016 it doesn't support sex by character.

Just keep in mind is a warning, not an error.
