### ISSUE TITLE
Items SQL Error Import

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#5526]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/868bdead9e5b33224c1faf03b6d1f63fd25a4255

* **Server Mode**: 

Renewal

* **Description of Issue**: 

Error import this items sql

```SQL
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`job_knight`,`class_third`,`class_third_upper`,`class_third_baby`,`location_shadow_shield`,`equip_level_min`,`refineable`,`script`) VALUES (24441,'S_Sonic_Shield','Sonic Shadow Shield﻿﻿','Shadowgear',true,true,true,true,true,99,true,'bonus bLongAtkRate,3; .@r = getrefine(); if (.@r >= 7) { bonus bLongAtkRate,3; } if (.@r >= 9) { bonus bLongAtkRate,4; }');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`job_blacksmith`,`class_third`,`class_third_upper`,`class_third_baby`,`location_shadow_shoes`,`equip_level_min`,`refineable`,`script`) VALUES (24472,'S_Vulcan_Shoes','Vulcan Shadow Shoes﻿','Shadowgear',true,true,true,true,true,99,true,'bonus2 bSkillUseSPrate,"NC_VULCANARM",2; .@r = getrefine(); if (.@r >= 2) { bonus2 bSkillUseSPrate,"NC_VULCANARM",.@r/2*2; }');
REPLACE INTO `item_db_re` (`id`,`name_aegis`,`name_english`,`type`,`job_blacksmith`,`class_third`,`class_third_upper`,`class_third_baby`,`location_shadow_weapon`,`equip_level_min`,`refineable`,`script`) VALUES (24473,'S_Arms_Weapon','Arm Shadow Weapon﻿','Shadowgear',true,true,true,true,true,99,true,'.@r = getrefine(); bonus bLongAtkRate,3+(.@r>=7?3:0)+(.@r>=9?4:0);');
```

```
Incorrect string value: '\xEF\xBB\xBF\xEF\xBB\xBF' for column `rathena`.`item_db_re`.`name_english` at row 1
```

**Comment by Patotron** [comment]
I had no problem importing these items. It seems to be a charset problem in your database. What is the encoding of your database? Try using UTF-8.

**Comment by sianromantic** [comment]
@Patotron 
did you know how to fix this error ?
[video[youtube]](https://youtu.be/__4YiHl2P5M)

**Comment by Patotron** [comment]
@sianromantic It looks the same, you are importing it as "Tradiotional Chinese big5" but the database is "UTF8". You do not need support for Chinese characters if you are not using them.

**Comment by sianromantic** [comment]
Could it be the problem of innodb_buffer_pool_size?
because i need big5 as default coding, so if i use "show variables like 'char%';" the result is 


<details>
  <summary>result</summary>

+--------------------------+-----------------------------------------------+
| Variable_name            | Value                                         |
+--------------------------+-----------------------------------------------+
| character_set_client     | latin1                                        |
| character_set_connection | latin1                                        |
| character_set_database   | latin1                                        |
| character_set_filesystem | binary                                        |
| character_set_results    | latin1                                        |
| character_set_server     | latin1                                        |
| character_set_system     | utf8                                          |
| character_sets_dir       | C:\Program Files\MariaDB 10.5\share\charsets\ |
+--------------------------+-----------------------------------------------+

</details>

but if i split files content (item_db_re_equip.sql) to two part then it can execute.

**Comment by Patotron** [comment]
If separating it into two parts allows you to run it without any problem, indeed the problem is in the runtime limit of the program you are using, which I do not know what it is. In phpmyadmin for example there is an option to remove the maximum runtime for this type of cases. @sianromantic
