### ISSUE TITLE
Unregistered ID. every time

### ISSUE THREAD

**Issue by benisda** [rathena/rathena#5655]
* **Client Date**: 
2020-03-22 (i saw this date in a log file how can i check the date to be sure ?)
* **Server Mode**: 
Renewal
* **Description of Issue**: 
Hello everyone, i'm trying to create a server.
When I log in from the client I can see a new entry in the loginlog table in phpMyAdmin,  but the user is field is empty (the id wasnt sent correctly to the server ?) and i'm getting the error : "Unregistered ID. Please make sure you have a registered account and you have correctly typed in the user..."
i took a client from a private server because I couldnt to find one :( (from DreameR RO)
Also if you have useful links with ressources i will be happy to look into it
If this isnt clear please tell me how to give you more infos
Thanks a lot

**Comment by RagnaWay** [comment]
This is an error with your conf/ in the emulator or patch. I tested it here in the last revision of the rA ( 2020-09-02 RE ) and it is working perfectly.

**Comment by benisda** [comment]
@RagnaWay so how can I get more informations about the issue ?

**Comment by randell1993** [comment]
It seems a problem with the client you are using,

First make sure you are entering the correct username and password (check if you are using MD5 or not)

but most probably its because you are using a client that you hadnt diffed yourself since that server where you took it from most probably and should be had made changes to that client thats why you are getting error.

**Comment by benisda** [comment]
Okay thanks

**Comment by aleos89** [comment]
Please use the forum for support related question.
