### ISSUE TITLE
The Sign Quest "Stone Delivery" Part - Stone does not get recognized

### ISSUE THREAD

**Issue by Erukanu** [rathena/rathena#5713]
* **rAthena Hash**: Up-to-date (fresh)

* **Client Date**: N/A

* **Server Mode**: Pre-Renewal

* **Description of Issue**: The  "Char name" Stone does not get recognized by the Knight NPC in Yuno
  * Result: Impossible to continue the Quest 
  * Expected Result: Stone gets recognized, and you get the receipt from the Knight 
  * How to Reproduce: Simply do the Quest until you reach that point.
  * Official Information: https://irowiki.org/wiki/Sign_Quest 
  

* **Modifications that may affect results**:  in Line 6827 
change 
set .@sign3, .@signid & 65535; 
into
set .@sign3, .@signid;

This fixes the problem since the Steward insert the real char id into the card slot 2 of the Stone item

**Comment by gengstergile** [comment]
yeap, i also got this issue, i will try your solution and check back

**Comment by Erukanu** [comment]
> yeap, i also got this issue, i will try your solution and check back

Any news? ^^


Also can anyone of the higher ups confirm this ?^^

**Comment by KrokusPokus** [comment]
I can confirm this bug. It is caused by line 6827 in "npc\quests\the_sign_quest.txt":
`set .@sign3, .@signid & 65535;`

Reason for causing the problems:
Variable .@sign3 in this case is supposed to contain the char_id which will be handed over to the countitem2 function.
A long time ago, char_id used to be of "long" type. Nowadays, char_id is of type "uint32". Since the script copies only the lower 16 bits of the char_id, the countitem2 function doesn't recognize the customized item as belonging to this character. Which of course leads to the NPC claiming it's the wrong item...

Simplest fix: Change line to
`set .@sign3, .@signid;`

**Comment by Erukanu** [comment]
> I can also confirm this bug. As mentioned above, it's caused by line 6827 in "npc\quests\the_sign_quest.txt":
> `set .@sign3, .@signid & 65535;`
> 
> Reason for causing the problems:
> Variable .@SIGN3 in this case is supposed to contain the char_id which will be handed over to the countitem2 function.
> A long time ago, char_id used to be of "long" type. Nowadays, char_id is of type "uint32". Since the script copies only the lower 16 bits of the char_id, the countitem2 function doesn't recognize the customized item as belonging to this character. Which of course leads to the NPC claiming it's the wrong item...

The oldest report about this bug, that I found, was from 2013. So yeah its pretty damn old 😅

People that were stuck at that part were able to continue after I removed the above mentioned part of the check.
If you check a few lines further top you find what the "steward" npc is doing with the item.
Maybe that's the part that needs fixing too?

**Comment by KrokusPokus** [comment]
It looks like card members in the item struct also used to be of a smaller type back in the day, and the functions and scripts were actually dividing the char_id up to be stored in two members instead of one.

The pull request from Balferian takes a different approach than yours by changing the getnameditem function, but does the trick as well. Check out his post, he has an sql script if you need it. When his fix gets included, you'll have to undo the change to your line 6827 to not get the same bug in reverse. :)

**Comment by gengstergile** [comment]
> > yeap, i also got this issue, i will try your solution and check back
> 
> Any news? ^^
> 
> Also can anyone of the higher ups confirm this ?^^

ops sorry, after use your solution player can continue the quest until the end..
thanks!
