### ISSUE TITLE
Command [at]mi/mobinfo issue after Mob YAML

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5756]
* **rAthena Hash**: 7d6c1c9

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
  * ![gambar](https://user-images.githubusercontent.com/8316103/109062956-2bf17980-771b-11eb-9828-d4d7e0de11f3.png)
  * Expected Result: 
  * Mystical Card Album should be 25% according to the settings in YAML 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by vstumpf** [comment]
It's not a bug.
You can only get one MVP drop. They both have a drop rate of 25%. MVP drops are ordered.

OPB has a 25% drop rate.
Which means you have a 75% chance of failing.

MCA has a 25% drop rate.
However, in order to reach here, you need to hit the 75% chance from above.

So the "real" MCA rate is `75% * 25%` which is `18.75% `

**Comment by mazvi** [comment]
Okay thanks information. If this is not issue. This issue can closed.
