### ISSUE TITLE
SC: Manhole + Earth Dive/Ganbantein/Crazy Weed allows you to bypass Manhole restrictions.

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#580]
Manholed Unit is supposed to be considered like manhole itself disallowing the shadow chaser to cast Manhole beside the unit affected by MH. this can be bypassed by removing Manhole on player by using Earth Dive , Ganbantein or Crazy weed allowing you to place another manhole besides player allowing you to trap multiple people indefinitely .

edit*
this can also be applicable to Genetic : Thorn Trap

**Comment by cydh** [comment]
so u say, "Earth Dive, Ganbantein, Carzy Weed" remove the Manhole unit area, right?

**Comment by Paoly28** [comment]
yes it currently removes manhole unit area and allows the caster to indefinitely manhole you, i don't know if this was intended but i'm certain this is a bug.

**Comment by cydh** [comment]
typos, edited my previous comment

**Comment by Enigma040125** [comment]
Since we all know that there is some changes that were made in Ganbantein.

I have a question regarding the manhole, do you have any kind of videos that shows the manhole someone getting caught and then remove by crazy weeds/earth drive and then manhole again continuously doing the same process is that normal or a bug in kRO?
