### ISSUE TITLE
small yaml2sql missmatch

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6090]
* **rAthena Hash**: 
4b339f7f6ebb01d50c7b956a8146551ad379b468

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: yaml to sql converter sets varchar of "name_english" back to 50 instead of keeping it at 100. This only affects item_db2 versions though, when converting the import folders.
  * Expected Result: varchar(100)
  * How to Reproduce: use the yaml to sql converter on import database files
  * Official Information: not related to official.

* **Modifications that may affect results**: 
custom item db entries.

**Comment by EbilPanda** [comment]
I think there is also still the problem that yaml2sql is not able to convert mob DB to SQL again - and without it, there is no way to import new mobs from YAML to SQL - as also the old `tools/convert_sql.pl" is broken!

So I guess these things also need to be fixed :)

**Comment by Everade** [comment]
@EbilPanda
"I think" and "i guess" and "is broken" is always very promising.
Maybe test it first, then share your results for people to be able to actualy re-produce your claims.

**Comment by EbilPanda** [comment]
That's good I guess :) I'm always happy if something looks promising ;)

and yes I tested it on friday... as I've written: yaml2sql is not even trying to read mob_db and the other tool is generating mob db sql... which contains item names instead of item ids which ofc result in an error when trying to import it - because you know... int != varchar ;)
