### ISSUE TITLE
Openmail not working on 2020 client

### ISSUE THREAD

**Issue by SynchronyMaster** [rathena/rathena#6159]
* **rAthena Hash**: 

8233b718c354518f7e5167e57e050a25b4eba9b3

* **Client Date**: 

2020-04-01

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: Openmail script command nor atcommand @mail can open the mail windows, it still can be open by button below character's name.

**Comment by mazvi** [comment]
Why not use mail on menu on top left?

**Comment by CairoLee** [comment]
This is as expected, since the client supports the RODEX mail system, the old `@mail` atcommand and `openmail` script command are no longer work (the client no longer responds to the packets)

It seems that this is not a server-side issue, so please close this issue if your question has been answered
