### ISSUE TITLE
Compile warning in GCC in 172ae93d4752fe95a686909c1b273203f0dd8d50

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#622]
script.c: In function 'get_val2':
script.c:2747: warning: cast to pointer from integer of different size

**Comment by cydh** [comment]
must we change this
````
return (data->type == C_INT ? (void*)__64BPRTSIZE(data->u.num) : (void*)__64BPRTSIZE(data->u.str));
````
to
````
return (data->type == C_INT ? (void*)__64BPRTSIZE((int)data->u.num) : (void*)__64BPRTSIZE(data->u.str));
````

I guess, because `__64BPRTSIZE`/`intptr` wants int32 for 32-bit OS but the `data->u.num` is int64.
Cast data->u.num to int32, means we assume no NPC and Instance variable never exceed int32.

But wait, all other variables are `int32` (see `script.c::get_val_`). So, does we really need `struct script_data::script_data_val::num` as int64 as well (yet)?
@aleos
