### ISSUE TITLE
sropho card

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#623]
crytallization is working when the script is "bonus3 bAddEff,Eff_Crystalize,500,ATF_TARGET;" like banaspaty's.. but in default script which is bonus4 bAddEff,Eff_Crystalize,500,ATF_SHORT,3000; the crytallization effects duration ends  very fast. that causes the inlifcted target to reduce hp for 2 times only.. and when you use the "bonus3 bAddEff,Eff_Crystalize,500,ATF_TARGET;" the duration stacks depending on the no. of sropho cards inserted in your weapon, is it the right behavior?  could someone check this too? not quite sure

**Comment by cydh** [comment]
My follow up, not because the effect was not working, just follow the official script.

and as additional info,
previously, the duration of `Eff_Crystalize` aka `SC_CRYSTALIZE` is using level `SO_DIAMONDDUST` duration2 from skill_cast_db.txt `
> 2447,5000:5500:6000:6500:7000,1000,0,500,12000:14000:16000:18000:20000,**5000**,800:600:400:200:-
then, by default bonus bAddEff type that doesn't have `t` param still also use that old behavior (use 5sec duration).

So, I doubt when u said **stack**, there was no duration increment in the first place.
````
-				type =  sd->addeff[i].id;
-				skill = skill_get_time2(status_sc2skill(type),7);
+				type = sd->addeff[i].sc;
+				time = sd->addeff[i].duration;
````

and talk about Eff_Crystalize, its debuff not only HP reduction, it makes enemy can't move and attack.
