### ISSUE TITLE
flash combo

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#627]
flash combo animation disappear, here it goes sir aleos.. hmm what i mean is when casting flash combo the sura should change stance every single blow but it appears that nothings happening , the sura is just standing while the japanese characters is flashing..

**Comment by cydh** [comment]
hmm?

**Comment by aleos89** [comment]
Please be more descriptive with the report.

**Comment by RagnarokNova** [comment]
The most recent update for Flash Combo changed the skill entirely, but from my personal testing it still did not manage to match the previously confirmed official behavior. The skill itself looks like a huge project and I've been actively avoiding it. 

From what I remember of my most recent rA tests, the latest version of it still did not add the 200 ATK to the caster, and while the separate skills of the combo were being casted, !!'s showed up on top of the character's head instead of the skill names themselves. 

My biggest issue with the skill is that kRO seems to update it every month or two, making the official implementation of it ever changing. Nowadays it's supposed to stop working if the target walks out of range, but if another player walks into range, it's supposed to target that new player.
