### ISSUE TITLE
@iteminfo

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#645]
Iteminfo does not show any monster as those who drop them.

Even @iteminfo 909 (jellopy) says -not dropped by any monsters

**Comment by aleos89** [comment]
Which hash are you on?

**Comment by MrAntares** [comment]
GIT svn info:
Revision: 13920
Last Changed Author: napster  
Last Changed Rev: 13920
Last Changed Date: 2015-08-28 11:32:23 +0200 (Fri, 28 Aug 2015)

**Comment by icxbb-xx** [comment]
maybe remove (battle_config.atcommand_mobinfo_type) this line or add for RE mode

"else if (!battle_config.atcommand_mobinfo_type && item_data->maxchance)"

// requires RENEWAL_EXP or RENEWAL_DROP to be enabled (src/config/renewal.h)
// modifies @mobinfo to display the users' real drop rate as per renewal_drop formula
// modifies @iteminfo to not display the minimum item drop rate (since it can't tell the mob level)
// modifies @whodrops to display the users' real drop rate as per renewal_drop formula
atcommand_mobinfo_type: 1
