### ISSUE TITLE
Can't upgrade rathena !!

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#649]
![untitled](https://cloud.githubusercontent.com/assets/14345362/9988849/46244e2c-607e-11e5-8237-433eefec1371.png)

**Comment by anacondaqq** [comment]
Subversion for git repository?
https://git-scm.com/documentation

rAthena git repository working fine.

**Comment by Playtester** [comment]
Are you checking out via SVN maybe? Git repository occassionally corrupts the SVN folders and then you can't properly access it anymore.

The only way I found to fix this problem is to do a fresh checkout on the revision I'm currently on, then merge my custom changes into that and then update to most recent revision.
