### ISSUE TITLE
searchstore problem

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#6608]
* **rAthena Hash**: c429747f73bc21f98d5febe53ce109a033e478fe

* **Client Date**: 20211103

* **Server Mode**: re

* **Description of Issue**: search by items name
![image](https://user-images.githubusercontent.com/60462533/153257232-d9f7c40f-e1c2-4565-954b-c9815aaaf76b.png)

mapserver
![image](https://user-images.githubusercontent.com/60462533/153257519-0c395f16-03cf-474e-a359-0ce62b184a51.png)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I would chalk this up to the client itself. That little tick box under Item seems to do some sort of wildcard search of the item name, but only returns the first item it finds. Since the Search Store sends some request to the itemInfo.lub which in turn returns the item ID to the server, the only "fix" is to just untick that box for items with spaces in the names to get exact item name results.

You can easily see the issue in the client by looking in the itemInfo.lub and seeing that 17194 is a real item called "RG Red Potion Box". It's returning the first result it comes across.
