### ISSUE TITLE
Updating mob_db Renewal

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#6610]
As some of you may know, I'm here updating Renewal's mob_db.yml according to Divine-Pride, however during the update I came across that some monsters still have the "JapaneseName" I asked Atemo if I could remove it, but he mentioned that he would have to remove it in src and tidy it up to be just the "Name". Another issue I asked was if I could rename all the monsters according to the card, so he told me to ask this here, so the devs can review it with me to see if they think it's better or not.

Example:
![image](https://user-images.githubusercontent.com/98105181/153610771-0b290b77-321c-4f35-a3bc-0ad142c525c7.png)
![image](https://user-images.githubusercontent.com/98105181/153610798-aa53f780-e05a-46ff-a2e0-31a90af8db50.png)

**Comment by aleos89** [comment]
So for the `Name` label it's mainly focused on what iRO has named the monster. This should be the first name listed on Divine-Pride. Obviously for newer content iRO won't have yet so it will end up being a Korean translated name (until iRO gets that content).

**Comment by Everade** [comment]
I don't care if we remove it.
In any case, iRO translations are incomplete, and Divine-Pride is a mix of everything.
Since we mainly base translations on Divine, that concludes that **Name** isn't bound to any specific translation eitherway.
As such we could also store "improved" versions directly in **Name** itself.

But in case we keep it as it is for easier divine-updates, at least let us rename it to either AthenaName or KoreanName?!
From what i can tell, _Japanese_ never made any sense.
