### ISSUE TITLE
Nowalkdelay Script not working, Endure from - Eddga Card and Ahura Mazdah

### ISSUE THREAD

**Issue by iraciz** [rathena/rathena#6636]
* **rAthena Hash**: 6663

* **Client Date**: 2018-06-20eRagexeRE

* **Server Mode**: Pre-Renwal

* **Description of Issue**: 
  * Result: Even equiped with an Eddga Card or Ahura Mazadh, the char still stop at being hit. 
  * Expected Result: Perma endure, I mean, no walk delay long as the gear with bonus bNoWalkDelay is equiped.
  * How to Reproduce: Equip an Eddga or Ahura Mazdah for a permanent endure effect and try to walk while being under hits.
  * Official Information: Dunno.

* **Modifications that may affect results**:

**Comment by Singe-Horizontal** [comment]
It's due to the premature return in that function, since sc->count == 0
`
/**
 * Modifies the damage delay time based on status changes
 * The lower your delay, the quicker you can act after taking damage
 * @param bl: Object to change aspd [PC|MOB|HOM|MER|ELEM]
 * @param sc: Object's status change information
 * @param dmotion: Object's current damage delay
 * @return modified delay rate
 */
static unsigned short status_calc_dmotion(struct block_list *bl, struct status_change *sc, int dmotion)
{
	if( !sc || !sc->count || map_flag_gvg2(bl->m) || map_getmapflag(bl->m, MF_BATTLEGROUND) )
		return cap_value(dmotion,0,USHRT_MAX);

	/// It has been confirmed on official servers that MvP mobs have no dmotion even without endure
	if( bl->type == BL_MOB && status_get_class_(bl) == CLASS_BOSS )
		return 0;
	if (bl->type == BL_PC && ((TBL_PC *)bl)->special_state.no_walk_delay)
		return 0;
	if( sc->data[SC_ENDURE] || sc->data[SC_RUN] || sc->data[SC_WUGDASH] )
		return 0;

	return (unsigned short)cap_value(dmotion,0,USHRT_MAX);
}
`

**Comment by Daraen1** [comment]
i can confirm, i have the same behavior. 
But i can't confirm how it work on KRO :/
