### ISSUE TITLE
Pre-Re Player Soft (VIT)DEF Formula

### ISSUE THREAD

**Issue by NeutralDev** [rathena/rathena#6648]
* **rAthena Hash**: af97f7f9b

* **Client Date**: 2018-06-21

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: While I was looking at some data/formulas in the rAthena source I discovered something that seemed extremely unusual. I fished around with git blame before making this issue to see if there were any changes that might of occurred, but that didn't seem to be the case, so I wanted to confirm what I found here. I think there is a mistake that has gone unnoticed for ages. If I'm wrong, please close this issue, but wanted to bring this to Dev attention just in case. In the calculation for Pre-Renewal Player Soft DEF, the formula is programmed and described in this comment as the following using rodatazone as the source:
https://github.com/rathena/rathena/blob/df65d5ddfc5d10e1834875cc7a1c1f543e404c74/src/map/battle.cpp#L5645-L5647
While it's clear to me that **def2/2 +** is supposed to be **[VIT*0.5] +**. The referenced formula suggests there's supposed to be a max statement of **max([VIT*0.3],[VIT^2/150]-1)**, but in the current rAthena formula it's either not clear that a max statement already occurs, or it simply is not in the formula to begin with.  Instead, it would appear that the right side of the max statement **[VIT^2/150]** is the only thing that gets calculated here with the **-1** missing. Meanwhile, **VIT^2** is being represented as **def2x(def2-15)**, and then does **/150** as expected. What's unusual about this to me is that it subtracts by 15, and doesn't -just- do VIT^2 as expected. Furthermore, the reference says rnd() should have a minimum of **[VIT*0.3]**, which is also the min param during the max() statement.
  * Expected Result: If rodatazone is still determined to be accurate, and the current Soft DEF formula implementation is in fact wrong, then the Soft DEF curve should be different compared to now. In theory the formula should actually look something like this:
```
vd_min = def2*30/100;
vit_def = max(vd_min, def2*def2/150-1);
vit_def = def2/2 + (vit_def>0?rnd()%vit_def+vd_min:0);
```
  * Official Information: ~~Unfortunately I have no way to test official pre-re, otherwise I would of for this issue.~~ **Update:** This Issue appears to be related in terms of how Soft DEF should actually be calculated, according to the provided sources: https://github.com/rathena/rathena/issues/5767
  

* **Modifications that may affect results**: N/A

**Comment by aleos89** [comment]
Maybe this is something @Playtester can elaborate on for us!

**Comment by zhakyvea** [comment]
Fix The Def Calculation Using Thanatos Card Will Have 1 Damage Over 255 to 500vit 2handed daggers using thanaphreeo2hydra 2hydra 2tg then using GR on armor and DEVILING on manteau then the items +10item then the def will 99+255 ot 99+500 will have 1 damage

**Comment by zhakyvea** [comment]
pls FIX THIS ISSUE
 20151104 20180620 20180621 20200420 

PRE RENEWAL SOFTDEF then the 1 damage over 255 to 1000def +10items 2hand dagger using thanatos card <-----

**Comment by Daraen1** [comment]
@zhakyvea If you are not satisfied with rAthena's services, try to fix it yourself and submit the fix.

**Comment by Playtester** [comment]
If I simplify the formula from the sources mrj posted in https://github.com/rathena/rathena/issues/5767, then it's actually: 
`[VIT*0.8] + rnd()%max(1, [VIT * VIT / 150 - VIT*0.3])`
(with some additional rounding down in between)

Official damage reduction:
VIT 1: 0-0
VIT 20: 16-16
VIT 30: 24-24
VIT 40: 32-32
VIT 50: 40-40
VIT 60: 46-51
VIT 70: 54-64
VIT 80: 64-81
VIT 90: 72-98
VIT 99: 78-113

rAthena reduction (assuming DEF2 is equal to VIT, this is hard to read):
VIT 1: 0-0
VIT 20: 10-10
VIT 30: 15-17
VIT 40: 20-25
VIT 50: 25-35
VIT 60: 30-47
VIT 70: 35-59
VIT 80: 40-73
VIT 90: 45-89
VIT 99: 49-103

Looks like our damage reduction from VIT, assuming no status changes or anything else, is slightly lower. This also means that def-piercing attacks against other players are weaker on rAthena.

Fixing only this would be fairly easy, however in combination with any passive trait or status change the formula would be completely wrong again. To fix this, a complete restructuring would be needed.

I think the original reason why eAthena did a different implementation of the calculation was so that you can see the real DEF2 in the status window instead of just seeing your VIT stat again. And of course it would be weird to include the randomness in the status window.

**Comment by Playtester** [comment]
Officially confirmed now. 

**Acolyte 18/12 with 11+1 VIT, 9 DEF vs Familiar**
Official: Familiar deals 9-15 damage
rAthena: Familiar deals 12-18 damage

Official formula above would result in 12 VIT reducing damage by 9.
rAthena formula above would result in 12 VIT reducing damage by 6.

Math checks out.

**Comment by zhakyvea** [comment]
yes change the formula now

**Comment by zhakyvea** [comment]
Change The Formula Now Pls Fix ASAP

**Comment by Relliksuriv** [comment]
rAthena is an open source software maintained for free by the community and the devs aren't even asking anything in return while you earn with your own private servers.

No need to be toxic in asking the people who do this without return.

Fix it yourself or you may find them pissed and not work on it due to your toxic behavior.

**Comment by Singe-Horizontal** [comment]
What do you think of this :
```
int vd_min = def2*3/10;
vit_def = def2*def2 / 150;
vit_def = def2 / 2 +vd_min+(vit_def>vd_min?rnd()%(vit_def-vd_min):0);

**Comment by Playtester** [comment]
It's not the same as the official formula, this here should work:
`#ifndef RENEWAL
		//Damage reduction: [VIT*0.3] + RND(0; [VIT^2/150] - [VIT*0.3]) + [VIT*0.5]
		vit_def = max(1, (def2 * def2 / 150) - ((3 * def2) / 10)); //Random bonus part
		vit_def = ((3 * def2) / 10) + (rnd() % vit_def) + (def2 / 2);
#else`
