### ISSUE TITLE
WFIFOSET: Maximum write buffer size

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#672]
I play instance , after some time , game become very lag and show message

<core>
[Error]: WFIFOSET: Maximum write buffer size for client connection 3 exceeded, m
ost likely caused by packet 0x01f3 (len=10, ip=127.0.0.1).
[Error]: WFIFOSET: Maximum write buffer size for client connection 3 exceeded, m
ost likely caused by packet 0x0080 (len=7, ip=127.0.0.1).
[Error]: WFIFOSET: Maximum write buffer size for client connection 3 exceeded, m
ost likely caused by packet 0x0857 (len=75, ip=127.0.0.1).
[Error]: WFIFOSET: Maximum write buffer size for client connection 3 exceeded, m
ost likely caused by packet 0x01f3 (len=10, ip=127.0.0.1).
[Error]: WFIFOSET: Maximum write buffer size for client connection 3 exceeded, m
ost likely caused by packet 0x00b6 (len=6, ip=127.0.0.1).
[Error]: WFIFOSET: Maximum write buffer size for client connection 3 exceeded, m
ost likely caused by packet 0x02cd (len=71, ip=127.0.0.1).</core>

I don't understand what happen..

version : https://github.com/rathena/rathena/commit/8c8c486b843be4728e2a34a6cfa942137a90ac6f

**Comment by cydh** [comment]
client?

**Comment by julia40124009** [comment]
client date : 20141022
packet_db_ver: default

**Comment by cydh** [comment]
maybe has relation with this line https://github.com/rathena/rathena/commit/79ef03e6563bb2d7647e15c006313624a7e10e15#diff-85d990dde8caf2d72d1e2b0f7dcf9786R15616
`WFIFOHEAD(fd,sd->avail_quests*15+8);`
that the actual size can be more than that, it's mostly should be:
`WFIFOHEAD(fd,sd->avail_quests*(8+15+((8+NAME_LENGTH)*MAX_QUEST_OBJECTIVES)));`

**Comment by julia40124009** [comment]
I will test it later

**Comment by julia40124009** [comment]
<image>
http://postimg.org/image/6fktzjbm9/
</image>

I will test remove this update and test
 https://github.com/rathena/rathena/commit/79ef03e6563bb2d7647e15c006313624a7e10e15#diff-85d990dde8caf2d72d1e2b0f7dcf9786R15616

**Comment by cydh** [comment]
please don't remove, just try apply my diff first. If u remove it, it doesn't solve anything and the supposed-to-be-fixed issue will comes.

**Comment by julia40124009** [comment]
I already test diff
the result is photos
I need to provide my instance script for you to do test it?

**Comment by cydh** [comment]
oh OK.
what's ur last rev before update?

**Comment by julia40124009** [comment]
version https://github.com/rathena/rathena/commit/a2d8b817ca07e4d4dfb2dd03c3d754947b2c1139
just edit mmo.h file
 #define PACKETVER 20141022

same problem

instance script pm

**Comment by cydh** [comment]
just as note,
I tested @julia40124009 script, nothing bad happened to me. just maybe there's hardware limitation there if we review the script itself, there's terrible nested codes make it likely infinity loop.

**Comment by lighta** [comment]
Cydh is right all along with this, the WFIFOHEAD should be set to 
WFIFOHEAD(fd,8+sd->avail_quests*(15+((8+NAME_LENGTH)*MAX_QUEST_OBJECTIVES)));
But the WBUF aproach is probably better.

Anyway I just don't understand something, the picture show packet 0x0857 overflow not 0x097a, well we don't know really since we only know our FIFO was busted when this packet was added but it seem to happen quite often.
Otherwise well I think the best way to go would be to see wichs packet was in the queue, see if that really happen.
Something like a little debug mode at each WFIFOSET
#ifdef DEBUG_FIFO 
 printf("adding to FIFO fd=%d packet=0x%04x, sz=%d, fifosz=%d",fd,WFIFOW(fd,0),len,s->wdata_size);
#endif
Then in send_from_fifo() (in the end)
#ifdef DEBUG_FIFO 
 printf("sending FIFO fd=%d, fifosz=%d",fd,session[fd]->wdata_size);
#endif
So we could have a better view of what have filled his queue.

Btw I'm wondering why we allow to resize/realloc our FIFO when we finally going to check for WMAX or socket_max_client_packet at the end...
Would make more sense to check this in WFIFOHEAD to even prevent packet creation. (It's time wasted imo).
