### ISSUE TITLE
Camouflage dont increase ATK using skills

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#678]
http://irowiki.org/wiki/Camouflage

The ability is giving 300% atk only for basic atk  and not for skill as Arrows of Rain, Arrows Storm, etc.

**Comment by MrAntares** [comment]
In renewal it is giving master atk, which is an additive bonus at the end of the calculation thus, skill atk rate modifiers don't affect it.

Eg:
100 atk

basic attack with bonus: 100 + 300 = 400atk (400% final increase)
10000%skill attack with bonus: (100 x 100) + 300 = 10000 + 300 = 10300 (3% final increase)

**Comment by panko11** [comment]
I will record a video to demonstrate . The skill is increasing only the basic attack other skills the damage remains the same. I see which version of the emulator am I using?

**Comment by MrAntares** [comment]
No, every skill receives a +300 damage, but since the variance is usually bigger of skill attacks than the mentioned 300 bonus, you will not notice it. Only in average.

To make it clear:
If you deal 25000~30000 damage with the skill, after receiving the buff, you will deal 25300~30300 damage, but since the variance is 5k you will hardly notice anything of it.

**Comment by panko11** [comment]
just realized the damage and very variable, but saw the formula and this right yeah, sorry.
