### ISSUE TITLE
I can't compile after update source

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#682]
Picture -> http://i.imgur.com/oc6bIoV.png

**Comment by Lemongrass3110** [comment]
Which git hash?
Any source modifications?
PACKETVER?
Other configurations?

**Comment by Dark8008** [comment]
I use tortoisesvn to update, not change any source mod and packet, i just config 3 file, map - char and inter to connect to server ( before still working normal, after upate i try to compile i get that error )

**Comment by Dark8008** [comment]
3>..\src\map\quest.c(283): error C2065: 'LOG_TYPE_QUEST' : undeclared identifier
3>..\src\map\quest.c(465): warning C4013: 'mobdb_exists' undefined; assuming extern returning int
3>..\src\map\quest.c(465): warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
3>..\src\map\quest.c(475): error C2065: 'MAX_QUEST_DROPS' : undeclared identifier
3>..\src\map\quest.c(480): warning C4047: '==' : 'int' differs in levels of indirection from 'void *'

all file normal, just have these error line when compile !

**Comment by aleos89** [comment]
Using TortoiseSVN or TortoiseGit with the SVN link for Git isn't a good choice. It often leads to merge conflicts. Either switch over to TortoiseGit or accept that you may get conflicts like these at times.

Since you said you didn't modify anything in the 'src' folder, just delete the 'src' folder and do a "SVN Update" again and it should re-download those files for you.
