### ISSUE TITLE
commenting out renewal_aspd in src/config/renewal.hpp locks all characters to their max aspd - even level 1 novice

### ISSUE THREAD

**Issue by jamesonfajardo** [rathena/rathena#6900]
* **rAthena Hash**: e56977b5f

* **Client Date**:  2021-11-17

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: commenting out renewal_aspd in src/config/renewal.hpp locks all character to their max aspd - even level 1 novice
  * Expected Result: it should not lock characters to max aspd
  * How to Reproduce: clone latest rAthena -> go to src/config/renewal.hpp -> comment out RENEWAL_ASPD -> compile then run
  * Official Information: no official information, but it is an obvious bug because even level 1 novices have 190 aspd. I tried comparing with having RENEWAL_ASPD enabled and disabled and the bug only shows when it is disabled/commented out

* **Modifications that may affect results**:  no modifications needed, a clean rAthena with commented out RENEWAL_ASPD will do

![unknown](https://user-images.githubusercontent.com/54289743/165930943-1e4b6f18-c396-466c-b4e4-ea0f24545c7f.png)

**Comment by bgamez23** [comment]
i can confirm this.

**Comment by aleos89** [comment]
I'm not sure this is something worthwhile fixing. The issue at hand is you're mixing the renewal job_stats.yml with pre-renewal ASPD rates which are vastly different.

The simple fix is to just uncomment PRERE at build in true pre-renewal mode.

**Comment by Playtester** [comment]
At the very least the define should be removed if it's not working anyway.

But there might be reasons why people want this?

**Comment by bgamez23** [comment]
i think it should be remove since its totally useless to use that features if its no longer working. and also it might affect the other define RENEWAL_ features.

**Comment by jamesonfajardo** [comment]
My server is trans only and the idea is bringing trans characters to the vast world of renewal while retaining the stat computation of pre re to boost their stat than if they are trans in renewal. For example, ASPD is slower for trans in renewal because they can only have a max of 99 stats, and Cast time has fixed value so it will be slower for casters... something like that.

Please close if there's no plan to enable mixing of pre-re and re. just asked since it was working for my server before.

**Comment by Playtester** [comment]
@jamesonfajardo 
The best way to go about that would be to just compile with PRERE. You don't need any renewal code if you just want to add renewal content to pre-re.
The thing you want to do instead is converting items and monsters from the renewal database so they are suitable with pre-renewal, you can then add these for example to import, similar to how you add custom stuff. Once you're done with that, you add the renewal NPCs (some might need conversion too, for example you'd want adjust 3rd job related stuff so players cannot actually change to 3rd job), at the very least the warps and spawns.
Then it's basically good to go.
I recommend doing this episode-by-episode as otherwise it's a lot of work at once.

**Comment by slammer86** [comment]
> * **rAthena Hash**: [e56977b](https://github.com/rathena/rathena/commit/e56977b5f2abf0d3245a437cd1070643ccfea2c3)
> 
>     * **Client Date**:  2021-11-17
> 
>     * **Server Mode**:  Renewal
> 
>     * **Description of Issue**:
>       
>       * Result: commenting out renewal_aspd in src/config/renewal.hpp locks all character to their max aspd - even level 1 novice
>       * Expected Result: it should not lock characters to max aspd
>       * How to Reproduce: clone latest rAthena -> go to src/config/renewal.hpp -> comment out RENEWAL_ASPD -> compile then run
>       * Official Information: no official information, but it is an obvious bug because even level 1 novices have 190 aspd. I tried comparing with having RENEWAL_ASPD enabled and disabled and the bug only shows when it is disabled/commented out
> 
>     * **Modifications that may affect results**:  no modifications needed, a clean rAthena with commented out RENEWAL_ASPD will do
> 
> 
> ![unknown](https://user-images.githubusercontent.com/54289743/165930943-1e4b6f18-c396-466c-b4e4-ea0f24545c7f.png)

try this works for me :
- copy job_stats.yml pre-renewa to renewal
- change aspd to pre-renewal on src\config\renewal.hpp
- recompile the server

i don't know src problem mybe other guy can fix it.

**Comment by bgamez23** [comment]
> is there any plan to fix this issue?you can't make revo classic setup if this issue is exist.

I think they don't have a plan to fix that bug. But if you really want the revo classic setup.much better to switch to more stable emulator like herc.as of now lots of trial and error happening at the moment because of this convertion

**Comment by bgamez23** [comment]
> > I think they don't have a plan to fix that bug. But if you really want the revo classic setup.much better to switch to more stable emulator like herc.as of now lots of trial and error happening at the moment because of this convertion
> 
> Herc is missing a thousand bugfixes though, I don't really recommend using it if you want an authentic experience.
> 
> Going by the post above the only issue here is that we are reading the wrong YAML file. Should be easy to fix.

Yes that true.but base on @aleos89 they don't have plan do fix it. I just gave him/her suggestion since revo classic setup will work on herc if he/she doesnt want some latest features of rathena.but at the moment it will not fix his concerned regarding on this issue.

**Comment by freakmastersx** [comment]
> > is there any plan to fix this issue?you can't make revo classic setup if this issue is exist.
> 
> I think they don't have a plan to fix that bug. But if you really want the revo classic setup.much better to switch to more stable emulator like herc.as of now lots of trial and error happening at the moment because of this convertion

i already switches before to herc when there is a lot of trial and error happening on rathena because of lighta updates rathena became unstable before. but recently i switch back to rathena after seeing it became stable.how ever this was before switch db to yml. at the moment this is the only issue i got encountered on my revo classic setup.im looking forward for this bug can still fixable.

**Comment by Playtester** [comment]
Well the easy fix is described above, just update the DB file.

If you don't use RENEWAL_ASPD, you also don't want the renewal database values for ASPD.

For example I wouldn't even know what base ASPD Revo Classic is using. Is it using the same as pre-re or it is using renewal ASPD but multiplied by 10? etc.

You as a server owner can easily do that decision and just update your DB file, fixing this on rAthena is harder because we need to find an automated solution, which is not easy because job_stats.yml does not only include ASPD but also other values.

Aleos is currently looking on into a solution such a for example making a separately file for only the ASPD values, but you don't need to wait for that, just put the base ASPD you want.

**Comment by aleos89** [comment]
rAthena officially supports renewal and pre-renewal (classic). Anything in between is bound to produce mixed results and is totally up to the user's thoughts on how they want that behavior to be.
