### ISSUE TITLE
Freeze target asura strike behavior

### ISSUE THREAD

**Issue by jofvgaming** [rathena/rathena#6919]
* **rAthena Hash**: Latest

* **Client Date**: 20180621

* **Server Mode**: Both

* **Description of Issue**: Freeze target attack with asura strike using a weapon with 4 Stormy knight card,(for high chance can freeze)
  * Result:  The freeze target receive damage this is correct but still target receive freeze status,
  * Expected Result:  The freeze target received damage then freeze status should be break. Also the other skills same behavior as expected result should be fix.
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  
Already applied this Fixed status change chance from items #6907
Nothing else

**Comment by Playtester** [comment]
Just to make sure: You mean you cast Asura Strike while the target is already Frozen, correct?

I thought aleos fixed this here: https://github.com/rathena/rathena/commit/53bc2376a60f01bfcde568fa1eaff144fb3c4fdc
```
			// Don't let OPT1 that have RemoveOnDamaged start a new effect in the same attack.
			if (sc->data[it] || sc->lastEffect == it)
```
It stores the last status change in a variable and then should prevent the target from receiving this status change again. Maybe it doesn't work with Asura Strike, would need to check.

But that's only a temporary solution anyway, I already told aleos how to fix this up properly but it will require a lot of restructuring. Basically on Aegis all effects and damage of a skill are determined at skill start and then only applied at skill end (after attack delay), we will need to create a similar structure for fully official behavior.

Also, please try to always state the commit you're currently on (you only need to copy the first 7 digits of the hash) instead of just writing "Latest".

**Comment by Playtester** [comment]
Can't reproduce this, if I use Asure Strike a frozen target, Freeze will break.

**Comment by jofvgaming** [comment]
What i experience it this will result to frost lock to the target, target cant do any move it always receive freeze status, casting asura strike to freeze target with items that has a high chance of freezing a enemy(4stormy card 80%) will result to another freeze status in instant, it should be an delay of breaked freeze then freeze again if other skill or attack do to target. 

Yes will try to add the hash details new on this my mistake.

**Comment by Playtester** [comment]
As said, on the current version on master I cannot reproduce this. If you use an attack on a frozen target it will not freeze the target again until you do a second attack. In other words if you use Asura on a frozen target the chance to freeze that target is 0%.

This is assuming you are up-to-date and don't have a customized status.yml.

**Comment by jofvgaming** [comment]
Thanks @Playtester for your answer, i try to back track all updates and i missed to remove a line. this is okay now.
