### ISSUE TITLE
Misc type is affected by reduction modifiers ( Hunter / Ranger Traps )

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#732]
Traps should ignore modifiers regardless if it's negative ( ex. Alice ) or such as thara frog cards and only get affected by element.

**Comment by RagnarokNova** [comment]
Partly confirmed: 
Blast Mine should ignore Demi-Human reductions
Claymore Trap should ignore Demi-Human reductions
Land Mine should ignore Demi-Human reductions

Both Firing and Freezing Trap show extremely minimal changes in damage in reaction to a Thara Frog Card

http://i.imgur.com/ZW2QvRL.png
http://i.imgur.com/Ith5Pic.png
http://i.imgur.com/wqIyZzr.png
http://i.imgur.com/BNxPXxh.png

As the damage of these two skills increase, the variance due to Thara Frog decreases

http://i.imgur.com/bLoZ2ND.png
http://i.imgur.com/11TY5Jj.png

**Comment by Playtester** [comment]
Pre-renewal traps don't have the caster as source so the source is technically not demihuman. (I wonder if traps have any race, though.)

Renewal traps are weird, seems they have a normal trap damage part and an additional damage part that comes directly from the caster.

**Comment by Playtester** [comment]
Just like Nova, I confirm this for Blast Mine, Claymore Trap and Land Mine. Other traps seems to have a reduction, so I won't touch them (e.g. Freeze Trap damage went from 92 to 36 with Thara Frog Card).
