### ISSUE TITLE
Mob_Db.yml change

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7335]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

right now in Mob_Db.yml you have

Aegisname (which is sprite)
Name (monster name)

why not rename Aegisname to Sprite to make it less confusing?

**Comment by Daegaladh** [comment]
Because is not only used for sprites but for pretty much everything in official servers, hence the name.
I don't think is confusing at all, in fact is way less confusing than before (Sprite_Name / kROName / iROName) and makes it easier for us to add new monsters.
Aegisname is just the internal name and Name the visual name.
