### ISSUE TITLE
Allow usage of Variables on mapwarp, areawarp, nosave mapflag, etc.

### ISSUE THREAD

**Issue by jasonch35** [rathena/rathena#7383]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

**I have an event script has this script:**
getmapxy(map$,mapx,mapy);

**I'd like to warp each player on the saved map and location after the event using mapwarp and areawarp:**
areawarp "quiz_01",182,94,228,88,map$,mapx,mapy;

**Also would like them to be able to return to that location when disconnected or logged out.**
mapname	mapflag	nosave	map$,mapx,mapy

### Describe alternatives you've considered

I've tried using _*getmapunits_ and _*getareaunits_, attach the script to the character, and then warp them 1 by 1 using _*for_ script but it was too complicated for me, I couldn't make it work.

As for mapflag, it just doesn't work completely.

Thank you!

**Comment by Lemongrass3110** [comment]
That is not possible, since the call is done once and inside the call it is done for each player, but at that point in time the variable has already been resolved.

The best we could offer would be to add support to special "mapnames" like with the normal warp command that allows you sending back everyone to their "SavePoint". Wondering if there is really no function that does that yet or I just cant find it right now. What do you say @Atemo?

**Comment by Atemo** [comment]
> That is not possible, since the call is done once and inside the call it is done for each player, but at that point in time the variable has already been resolved.
> 
> The best we could offer would be to add support to special "mapnames" like with the normal warp command that allows you sending back everyone to their "SavePoint". Wondering if there is really no function that does that yet or I just cant find it right now. What do you say @Atemo?

There is no function like this yet! The idea seems interesting in terms of management, it would seem clearer. But 50/50, imo the same result can be achieved without too much difficulty

**Comment by Lemongrass3110** [comment]
Support will not be added.
