### ISSUE TITLE
Guild position change

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#7387]
### rAthena Hash

d0e39fbea775815317ad18d31210df3d0db5440a

### Client Date

20130618 (but it happens on every version with custom client)

### Server Mode

Pre-Renewal, Renewal

### Result

Yes, I am using a custom client, but this is still a server issue, the server shouldn't let this happen:

If you are guild master the server lets you to change you position from 0 to anything else, but it won't let you to change you position back to 0. Again, custom client that doesn't respect client limits.

https://github.com/rathena/rathena/blob/master/src/map/clif.cpp
clif_parse_GuildChangeMemberPosition
Line 14204:
```
		if( position > 0 ){
			guild_change_memberposition(sd->status.guild_id,RFIFOL(fd,i),RFIFOL(fd,i+4),position);
		}
```

This only prevents you changing TO position 0 and not FROM position 0 to anything else.

### Relevant Log Output

```JavaScript
[Network] Send: PACKET_CZ_REQ_CHANGE_MEMBERPOS
	memberInfo: Array(10) 0: {
		AID: 2000272,
		GID: 150313,
		positionID: 0  // TRYING TO CHANGE GM BACK TO 0
	}
	1: {
		AID: 2000304,
		GID: 150351,
		positionID: 1
	}
	2: {
		AID: 2000303,
		GID: 150350,
		positionID: 2
	}
	3: {
		AID: 2000322,
		GID: 150381,
		positionID: 3
	}
	4: {
		AID: 2000027,
		GID: 150419,
		positionID: 4
	}
	5: {
		AID: 2000322,
		GID: 150375,
		positionID: 16
	}
	6: {
		AID: 2000305,
		GID: 150362,
		positionID: 16
	}
	7: {
		AID: 20000091,
		GID: 150478,
		positionID: 16
	}
	8: {
		AID: 20000129,
		GID: 150514,
		positionID: 16
	}
	9: {
		AID: 20000150,
		GID: 150538,
		positionID: 16
	}

// POSITION 0 PACKET IS MISSING, BECAUSE IT WAS DENIED	

[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 2000304,
		GID: 150351,
		positionID: 1
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 2000303,
		GID: 150350,
		positionID: 2
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 2000322,
		GID: 150381,
		positionID: 3
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 2000027,
		GID: 150419,
		positionID: 4
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 2000322,
		GID: 150375,
		positionID: 16
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 2000305,
		GID: 150362,
		positionID: 16
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 20000091,
		GID: 150478,
		positionID: 16
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 20000129,
		GID: 150514,
		positionID: 16
	}
[Network] Recv: PACKET_ZC_ACK_REQ_CHANGE_MEMBERS
	memberInfo: Array(1) 0: {
		AID: 20000150,
		GID: 150538,
		positionID: 16
	}
```

### Expected Result

The server shouldn't let the guild master to change it's position from 0 to anything else and if it is something else, then it should forcefully put it back to 0.

### How to Reproduce

No need to reproduce, this is a missing check on server side.
If you really want to reproduce, come and see (Though I will close this loophole soon in my client source):
https://play.ragna.ro

### Official Information

This is pretty far from official waters, but officially you can't change the position of a guild master because of client side block. That doesn't mean that that the server should allow it to be changed but not changed back either if someone uses packet hack or custom client.

**Comment by Lemongrass3110** [comment]
The real problem is not the > 0 check, but that you send multiple changes at once and therefore the check a few lines above `if( len == 16 && RFIFOL(fd,12) == 0 ){` fails the length check that sets your position TO 0 and makes you guild master.

Remember that when you change FROM 0 you lose your guild master status and therefore you cannot change back yourself.

**Comment by Lemongrass3110** [comment]
I still think that this is valid behavior, since when you look at your provided network output (entries 5 to 9 are really funny btw)  you have to think of it like this:
We and most likely also AEGIS process these packet entries one after another. So there is two choices:

1. We process the first one, the player loses his guild master status, the others should not be processed anymore, as his requests do not come from the guild master anymore.
2. We do not process the first one (as it should always come alone - thats what the official client does) and all the other requests go through.

So guess it is a matter of personal opinion if this is "wrong" or not. Nevertheless I will clean up the function a little and make it more readable.

**Comment by Lemongrass3110** [comment]
If you want to try and confirm what I said above:
Open an official client and try to change the guild master position to something else. The client wont let you.
The only way to achieve that is to right-click on the member that you want to assign as a guild leader and chose the "Assign guild leader" option, which will result in that expected 16 byte packet with only a single change entry.
