### ISSUE TITLE
Warg Bite / Warg Strike

### ISSUE THREAD

**Issue by RagnarokNova** [rathena/rathena#763]
Have been gathering information from Aegis and these are my findings:

Warg Strike:
Damage formula is off (Aegis base damage with 1 all stat is doing ~x2 rA)
Skill should ignore Demi-human reduction (Thara Frog)
Skill should ignore Neutral Reduction (Raydric)
ATK should not increase damage at all (Zipper Bear)
ATK %s should not affect damage at all (The Sign)

Warg Bite:
Damage formula is off (Aegis base damage with 1 all stat is doing ~x2 rA)
Skill should be affected by Demi-human reduction (Thara Frog) - Already accurate
Skill should be affected by Neutral Reduction (Raydric) - Already accurate
ATK should not increase damage at all (Zipper Bear)
ATK %s should not affect damage at all (The Sign)

**Comment by Barigas** [comment]
Can confirm all of these. Warg Strike should ignore demi-human and neutral reductions. It is only reduced by ghost element. The same should be with HP/SP part of Gate of Hell. Some source here, in Clogon's post "pets and traps ignore reductions": http://forums.irowiki.org/showpost.php?p=1278257&postcount=17

**Comment by Paoly28** [comment]
i think atk should increase since i know people wearing ice pick when building melee wargs with warg dance slaves and tooth of warg increase atk of warg ( mastery type ) and it does increase it by alot so i think atk should increase it.

there's a full test on this on idRO and iRO lying around on YT.

here's also an old thread about wargs

http://forums.irowiki.org/showthread.php?t=22880&page=9

**Comment by aleos89** [comment]
Fixed in 8e6a65f.
