### ISSUE TITLE
Spirit Handler stats bug (overflow?)

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#7634]
### rAthena Hash

68d1af4

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Spirit handler stats becomes weird with negative value bonus, HP/SP increased way too much.

![image](https://user-images.githubusercontent.com/31171415/224241212-ac75333b-84ea-4389-b163-b1ecb93b9c68.png)

### Expected Result

Only summoner class. Other class seems fine.

### How to Reproduce

1. Equip item Heavenly Order (itemid 19451) on Spirit handler
2. Spirit Handler status (include HP/SP) become weird (negative value)

### Official Information

-

**Comment by OptimusM** [comment]
> > Tried replicating it but I'm getting sprite error, is it from kRO?
> 
> It's jRO items. You can change or disable the View if you got sprite error.

it's because this aditional parameter on the item
![image](https://github.com/rathena/rathena/assets/40366993/acd1c61b-807b-4b66-b5a3-392dd41dae07)

Fixing that will fix your problem.
btw, if u have that item already on your server for some time now, your players probably bug their skill points (giving them infinite skill points)

**Comment by laziem** [comment]
Closed. Fixed by removing the extra parameter as @OptimusM said above.
