### ISSUE TITLE
PACKET_ZC_SKILL_SCALE not displaying properly

### ISSUE THREAD

**Issue by Tydus1** [rathena/rathena#7687]
### rAthena Hash

Latest (6136f7df3530ab1a0f40c383b3e2efbe319a536f)

### Client Date

2020-08-06

### Server Mode

Pre-Renewal

### Result

In some situations the packet is not displaying the area of effect correctly. 

### Expected Result

SkillScale shows the area of effect to all skills that have SkillScale Flag on Skill Database;

### How to Reproduce

How to reproduce:

1. Configure to pre-renewall and keep ShowSkillScale active on BattleConf/Client;
2. Summon Garm [Id: 1252] and run around it for a while until it casts NPC_WIDEFREEZE;
3. ShowSkill will show the area range for the NPC_WIDEFREEZE and then skill will activate;
4. At this point you can kill the mob;
5. Use "@useskill 664 5 <char_name>" // SkillId 664 = NPC_WIDEFREEZE
6. ShowSkill will NOT show the area range for the skill;

Another test you can try out is using the Weapon "Death Guidance" [Id: 1186]. This weapon grant a small chance of casting NPC_VAMPIREGIFT. Equipping and hitting some mob until it procs will NOT show the SkillScale area; (A good mob to quickly make it proc is 1906)

### Official Information

I don't have any official source of information related to this but maybe someone might be able to run those tests in there;

### Modifications that may affect results

None

**Comment by LadyNanuia** [comment]
Ive found a similiar thing with Wide Bleeding where the Scale on  ground is smaller than the actual effect

**Comment by Tokeiburu** [comment]
The skill scale/warning plane displays for the **casting** duration of the skill. When you use `@useskill 664 5`, there is no cast time so nothing will show. It will for Garm because it has a casting time. Similarly, autocast skills don't have cast times.

As for Wide Bleeding not showing the correct AoE, that would be because of your client skillinfo.lub having the wrong SkillScale defined. The AoE size displayed is defined client side, not server side. Plus that would be up for a new issue entirely (but what's in skill_db.xml looks fine to me).

**Comment by Tydus1** [comment]
@Tokeiburu Correct if i'm wrong, please: Even if you hardcore a casting time duration to some random value (taking your example from Hatii casting time, 1000ms ) still will NOT show the area. Shouldn't it display in that case? 

![image](https://user-images.githubusercontent.com/16859064/230650361-3546e19d-039f-4666-871f-7ae7bfce5666.png)

**Comment by Tokeiburu** [comment]
@Tydus1 Ah, you're right. I forgot SkillScale doesn't apply to players, only BL_MOB/BL_NPC.

**Comment by Tydus1** [comment]
Thanks for the informations, @Tokeiburu.
