### ISSUE TITLE
Buying shops / sell

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#790]
Hello good day, there is a problem with shopping NPCs or sales.

The bug occurs as follows:

If you start trading with a NPC buying or selling items, if you cancel the purchase or sale, when you talk to any NPC dialogue with the NPC just the bug and will not appear the button to end the conversation.

Client 2015-05-13

**Comment by admkakaroto** [comment]
Reproducing the problem:

1 - Talk to any NPC store: http://i.imgur.com/Abvs2lv.png

2 - Complete trading, buying or even canceling.

3 - Talk to any NPC that has dialogue: http://i.imgur.com/AhQni39.jpg

And ready, do not have the option to end the conversation, this occurs with any NPC.

**Comment by nanakiwurtz** [comment]
Oh I thought it was just my client... -_-'a
I'm using 2013-08-07 client and got this too D:

**Comment by sader1992** [comment]
this happen with the tool dealer ? 
the Official tool dealer ?

**Comment by Dark8008** [comment]
I have the same problem, all npc sometimes will have that errors !

**Comment by Lemongrass3110** [comment]
Confirmed with git hash: 5695dc5 on both renewal and prerenewal
Blame: cef2f9e

**Comment by aleos89** [comment]
I tried various ways and couldn't reproduce this, until I finally could reproduce the issue you got.

Talk to Fruit Gardener > Click Buy or Sell > Click cancel from the item list menu > Talked to Point Merchant; selected Scarlet Point; entered 0 > Close button is not displayed

I'll get this resolved now that I know which step is causing the problem. I tested all other cancel/buy/sell methods and it worked just fine, which is why I may have skipped this when I was testing this before.

**Comment by DeveloperNube** [comment]
This issue is from client packet.

We can find 'db/packet_db.txt'
search: 0x09D4,2,npcshopclosed,0

But, src/clif.c no add this function.

There is my fixed.
https://www.dropbox.com/s/153z5hqnklql2wu/callshop.patch?dl=0

**Comment by aleos89** [comment]
The issue still stands though for clients older than 2013-12-23 that do not support that packet.

**Comment by CairoLee** [comment]
@aleos89 Can you find out why 3ceam don't have the same problem about the shop system?

eg: 

The player can move when he talk with an callshop npc?
