### ISSUE TITLE
stats.rathena.org expired on 2015-11-28, charserver freezes for 20 seconds every 30 mins

### ISSUE THREAD

**Issue by theultramage** [rathena/rathena#793]
Charserver's chmapif_parse_fw_configstats() does a synchronous make_connection() call to stats.rathena.org with a 10-second timeout. The domain expired and the domain parking server is not responding with a RST, so every 30 minutes, every charserver freezes for 21 seconds (not sure why it's not respecting the timeout parameter).

I suggest:
1) urgently renewing the domain and making this subdomain work again.
2) fixing the code so that the timeout is 1 second or less, and that the value is actually obeyed.
3) considering making the code asynchronous.
4) server operators, for the time being, should compile with ```STATS_OPT_OUT```, or put ```127.0.0.1 stats.rathena.org``` into the etc\hosts file.

**Comment by anacondaqq** [comment]
I'm totally agree with you. It's not first time when rathena.org domain or host have a lot of problems.
I was several times suggest to help it (i do not need anything back from that, just want help to make it stable and always online), but my requests were ignored, and everyone was not interested.

And what we have for now? I have no money for now to help, domain do not work, tons of really important information -> lost because of access, nobody care.

Guys, rAthena is OpenSource project, based on community, why not to start to make official donation? There are 100500 admins with money from donations who can help by dollars, why admins of rathena do not ask for help and do anything by their own money? It's not correct i think.
Why you must pay a money from your wallet, if there are around a lot of people who doing real money and can help? Donation button at forum is hidden, really hard to make donation, there are no any request to help, and all services from rathena very unstable.

This problem is not new, few years (or year) ago we was have the same trouble, and rathena was offline for minimum of few weeks. And after that incident i was make a topic about it at forum, (sorry if i repeat) -> but nobody care...

Dear guys, who have right and access to domain name and hosting, please back it online again.
If you have no money for that -> organize donation. I thin 11$ or even 18$ per year for .org domain it's not a lot.

Hosting in now days is very cheap too, if you pay for that more then 20$ per month, i do not understand you.

And i totally agree with theultramage point... and can confirm that error too.

**Comment by aleos89** [comment]
@anacondaqq : Nothing is wrong with the host. It's an issue with the domain company changing policy rules which lead us to having to prove validity of our account against the domain name. We are trying to resolve that as fast as we can. But yes, I am working behind the scenes to get rA resolved in many areas. There are many issues which we can be discuss elsewhere if you wish. :)

@theultramage : Agreed. I think just disabling the stat reporter for now is the best option. Nothing was ever done with this feature and it has just become stale.
