### ISSUE TITLE
Monster moving weird when going to loot

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#8232]
### rAthena Hash

8cec8ce5605ac7933b40771cba51425ba64e3e43

### Client Date

20220602

### Server Mode

Renewal

### Result

https://github.com/rathena/rathena/assets/9493525/2c11637b-e805-4ec6-91e8-2332987c4804

Spawn 100 poring and kill it.

### Expected Result

Monster smooth moving like before.

### How to Reproduce

Please see above video.

### Official Information

-

**Comment by Playtester** [comment]
This is because on rAthena, we make monsters stop immediately when they lose their target. If we didn't send a "fixpos" packet (this is what teleports the porings to their real position which you perceive as stuttering), then you'd see the Porings move to the cell where the loot was, but they would actually not be there, which would create insane position lag.

I wonder how official servers handle that. It looks like the Poring always stop one they reached the next cell, but what kind of packet is send to the client to tell it that the move path was shortened?

**Comment by kaninhot004** [comment]
I see.

For method to solve I didn't know any about packet handling. 😵

**Comment by Playtester** [comment]
```
00:11:43.211 HEADER_ZC_NOTIFY_MOVEENTRY11 (Poring tries moving to loot)
    "PositionTo": {
      "SrcX": 132,
      "SrcY": 330,
      "SrcDir": 8,
      "DestX": 140,
      "DestY": 318,
      "DestDir": 7
    },
    "Movestarttime": 263881998,

00:11:45.883 HEADER_ZC_ITEM_PICKUP_ACK_V8
00:11:45.883 HEADER_ZC_ITEM_DISAPPEAR

00:11:45.904 HEADER_ZC_NOTIFY_MOVEENTRY11 (Poring stops)
    "PositionTo": {
      "SrcX": 137,
      "SrcY": 325,
      "SrcDir": 4,
      "DestX": 138,
      "DestY": 324,
      "DestDir": 10
    },
    "Movestarttime": 263884710,
    ```
The way it works on official servers is that it sends another "MOVEENTRY11" packet, but with just one cell movement.

**Comment by kaninhot004** [comment]
> ```
> 00:11:43.211 HEADER_ZC_NOTIFY_MOVEENTRY11 (Poring tries moving to loot)
>     "PositionTo": {
>       "SrcX": 132,
>       "SrcY": 330,
>       "SrcDir": 8,
>       "DestX": 140,
>       "DestY": 318,
>       "DestDir": 7
>     },
>     "Movestarttime": 263881998,
> 
> 00:11:45.883 HEADER_ZC_ITEM_PICKUP_ACK_V8
> 00:11:45.883 HEADER_ZC_ITEM_DISAPPEAR
> 
> 00:11:45.904 HEADER_ZC_NOTIFY_MOVEENTRY11 (Poring stops)
>     "PositionTo": {
>       "SrcX": 137,
>       "SrcY": 325,
>       "SrcDir": 4,
>       "DestX": 138,
>       "DestY": 324,
>       "DestDir": 10
>     },
>     "Movestarttime": 263884710,
> ```
> 
> The way it works on official servers is that it sends another "MOVEENTRY11" packet, but with just one cell movement.

Thank you so much!
