### ISSUE TITLE
Can't use Arrow Storm while equiping high refine Big Crossbow

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#824]
Server info : using commit 7489fab958951d502b14a42e681b14881384f255
Mode : Renewal
Client date : 2015-05-13
Source modification : none

Screenshot of +0 Big Crossbow and Arrow Storm working as intended : http://i.imgur.com/nOC0mSp.jpg
Screenshot of Arrow Storm not working (not enough SP) while equipping +14 Big Crossbow : http://i.imgur.com/dUO2b7E.jpg

Arrow Storm seems to be working fine while equipping up to +9 Big Crossbow.
I'm not sure what's causing this or if there's another item with the same problem.

**Comment by Historica** [comment]
18110,Big_CrossBow,Giant Crossbow,5,56000,,900,160,,5,2,0x00000800,63,2,34,4,110,1,11,{ .@r = getrefine(); bonus2 bSkillAtk,"RA_ARROWSTORM",(.@r*5); bonus2 bSkillUseSP,"RA_ARROWSTORM",(.@r*5); if(readparam(bAgi)>=120){ bonus bAspd,1; } },{},{}

Should be increase 5 SP per refine , put - on this one
bonus2 bSkillUseSP,"RA_ARROWSTORM",-(.@r*5)

**Comment by secretdataz** [comment]
Yeah, that's it. I'm submitting a PR.

**Comment by secretdataz** [comment]
Seems like this is caused by invalid script and skill cost being unsigned int.
+10 Big Crossbow will result in bonus2 bSkillUseSP,"RA_ARROWSTORM",-50;, causing overflow.

**Comment by nanakiwurtz** [comment]
Ah yes, I guess there's a misunderstanding of the bSkillUseSP.
Since each refine will increase the SP consumption, this should use - right?
The misunderstanding comes from the inconsistency of the item bonuses, where the bonuses are mixed between increase and decrease.
For example, bonus A will increase this, but bonus B will decrease that.
So we are tend to confuse between increasing & decreasing...

The current script use `bonus2 bSkillUseSP,"RA_ARROWSTORM",(.@r*5);` which will decrease the SP cost, and when the refine got to +10 like mentioned above, the user got free +2 SP by using the skill :sweat_smile:

**Comment by secretdataz** [comment]
Maybe we should rename or at least add an alias of these bonuses to avoid confusion.

**Comment by nanakiwurtz** [comment]
Alias sounds like a good idea :bulb:
