### ISSUE TITLE
Sharp Shooting Bug

### ISSUE THREAD

**Issue by zakeph** [rathena/rathena#8262]
### rAthena Hash

a768af85ee5adf368cd59e7c288f3239418e62b9

### Client Date

2018-06-21

### Server Mode

Pre-Renewal

### Result

good,
I have a bug on my server similar to the one in the video I show:
https://vimeo.com/936761029?share=copy

When I activate the skill_eightpath_algorithm the skill fails in diagonal ranges.

https://github.com/rathena/rathena/commit/6ad062f6e37d7d9e5663e280617442e3945cef62

### Expected Result

not fail

### How to Reproduce

added video

### Official Information

none

**Comment by Playtester** [comment]
That seems like expected behavior to me when you enable eightpath. You would need to stand at the exact diagonal range to hit a target.

However I don't understand how the skill is used in that video, it's a targetted skill but in the video it looks like the player is targetting the ground.

Usually the skill would hit at least the unit you target.

**Comment by vstumpf** [comment]
This is not a bug, this is how eightpath works. When enabled, sharpshoot (and north wind) calculate the closest of the 8 paths (up, up-right, right, down-right, down, down-left, left, up-left), and hits enemies on that path. The skill will also deal damage to the original target.

If you want the server to calculate the "true" path and damage the enemies in the path, then disable eightpath. 

@Playtester the video is a horrible example, it's on a heavily modified server.
