### ISSUE TITLE
RK_DRAGONBREATH Not a result of Abysmal Knight Card

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#834]
1. Use skill DRAGONBREATH and no weapon damage 230k
2. Use skill DRAGONBREATH and On weapon damage 230k

Mode. pre-re
I'm Using last git

sorry I bad english

**Comment by cold-hr** [comment]
and 
Not a result of Hydra Card

**Comment by MrAntares** [comment]
In pre-re this is the official, however after the 175/60 update, it should use elemental, ranged and racial modifiers, also it is demihuman damage:
http://irowiki.org/wiki/Dragon_Breath

New damage formula (after the 175/60 update):
Damage = [(CurrHP ÷ 50) + (MaxSP ÷ 4)] × (SkillLv × BaseLv ÷ 150) × (95 + DragonTraining_Lv × 5)% × (100 + Ranged Damage Modifers)% x (Elemental Modifiers)% x (100 + Racial Modifiers)%

The damage is affected by Demi Human, Ranged, or Elemental/Property reduction/addition items (this is after level 175 update)

(Note to self: this is a pretty stupid change, since it it the player's dragon's breath and not the player's, so why would player cards increase the damage? Te original formula was much more logical....)

**Comment by cold-hr** [comment]
@MrAntares 
OK thank

**Comment by Barigas** [comment]
Nope. Hydra and Abyssmal knight do not increase damage of Dragon Breath in officials since it is not atk based skill. Nobody uses 4x hydra weapon for DB there. Only Archer Skeleton and other ranged% items do. Thara, elemental reductions(like marse and jakk card) and %ranged reductions decrease damage.

**Comment by MrAntares** [comment]
@Barigas What "officials" are you referring to? Many still did not implement the 175/60 patch or did implement things in a customized form. 

Mine is from kRo and iRo.

https://forums.warpportal.com/index.php?/topic/154605-hayrohs-rune-knight-re-17560-wdb-lux-anima-update-buildsguide-iro-jro-new-sprite/

*New Fix/Nerf Dragon Breath (Fire/Water) Formula & Level Cap 175/60:*
*From iRO Wiki:*
*Damage = [(CurrHP ÷ 50) + (MaxSP ÷ 4)] × (SkillLv × BaseLv ÷ 150) × (95 + DragonTraining_Lv × 5)% × (100 + Ranged Damage Modifers)% x (Elemental Modifiers)% x (100 + Racial Modifiers)%*

*Official Server Test:*
*kRO Dragon Breath Water 175/60 Update New Formula Test Damage vs Demi Reductions [iRO Chaos]*
*https://www.youtube.com/watch?v=fM5HSYgaEk8*
*Expert Archer chants/Range % greatly boosts new DB dmg units, range %>SP>HP in equal or small units damage-wise."*

**Comment by Barigas** [comment]
Same as you do. Show me plz where have you seen that Hydra cards increase damage of Dragon Breath.
Formula on iRO wiki means that is is reduced by racial reductions, but it is not increased by them.

**Comment by Atemo** [comment]
>Show me plz where have you seen that Hydra cards increase damage of Dragon Breath.

Maybe the *x (100 + Racial Modifiers)%* part ?

**Comment by Barigas** [comment]
I meant screenshot. This formula is written wrong.  They meant that it is reduced by racials, not increased. As you can notice, even in your link he uses neither Abyssmal Knights for PvM nor Hydra Cards for PvP.

**Comment by reigneil** [comment]
pre-renewal do have Rune Knights?

**Comment by cydh** [comment]
Good news, I have friends now. LOL
I meant, I can ask someone to test your doubts about DB (read: Dragon Breath) on idRO. It implemented 175/60 since year ago.
