### ISSUE TITLE
Bowling Bash Calculating Knockback Amount Incorrect 

### ISSUE THREAD

**Issue by Haydrich** [rathena/rathena#8435]
### rAthena Hash

master

### Client Date

20230905

### Server Mode

Renewal

### Result

Using bowling bash on target with the max level of the skill should Knockback the target by 5 cells, but instead of this it Knockback 10 cells

### Expected Result

Bowling bash should Knockback the target 5 cells on max level

### How to Reproduce

1. Change your job to be Knight / Lord Knight
2. Test bowling bash skill on target
3. Target Knockback 10 cells

### Official Information

Bowling Bash should Knockback 5 cells on ma level

**Comment by LadyNanuia** [comment]
Can attest to this, i simply just cut the knockback down on Skill_Db.yml to fix the issue

**Comment by Playtester** [comment]
The problem is that the knockback effect specified in the database is applied automatically, but someone specifically coded an additional knockback into the source code.

Both knockbacks are also incorrect, at least according to Irowiki. The knockback is supposed to happen before the damage. So what should really be happening is that the manual knockback call should be there but happen before the damage and the damage itself needs to set blewcount to 0 to prevent doubling the effect.

**Comment by Playtester** [comment]
Tested on kRO:
Miss - No knockback
Hit - Knockback (once)
Safety Wall - Miss and no knockback (iroWiki is outdated here)
