### ISSUE TITLE
Executing char-server with "--char-config" doesn't work

### ISSUE THREAD

**Issue by joaogardenberg** [rathena/rathena#8618]
### rAthena Hash

f4cd68e42

### Client Date

N/A

### Server Mode

Pre-Renewal

### Result

When passing `--char-config conf/char_athena.conf` (the same file it already reads without the parameter) to `./char-server`, it doesn't work:

![image](https://github.com/user-attachments/assets/8d0ede6e-48d8-4744-b841-1f36fbdf4028)

### Expected Result

Running the char server without the param, just `./char_server`, it works properly:

![image](https://github.com/user-attachments/assets/5cdfe9b9-359e-4c1f-ab5f-53b98a273415)

### How to Reproduce

Just run the command `./char_server --char-config conf/char_athena.conf` after having it working with `./char-server`

### Official Information

N/A

### Modifications that may affect results

I'm on a fresh install, without any src modifications

**Comment by aleos89** [comment]
The quick hint here is in the "using password: NO" message. By default we send no password src side which lead me to believe the inter_athena.conf wasn't being loaded. After some debugging I found that the culprit was because we were passing the `--char-config` argument was being sent to the function that parses the inter-server config.
