### ISSUE TITLE
Weapon X Ammo Restriction Check

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#879]
Currently, the Weapon x Ammo check is done on battle.c while player attempts to attack.
Somehow, on idRO (maybe someone can check on other official server), the check is done while equipping the ammo or weapon.

````
			//Ammo check by Ishizu-chan
			if (sd->inventory_data[index]) {
				switch (sd->status.weapon) {
					case W_BOW:
						if (sd->inventory_data[index]->look != A_ARROW) {
							clif_arrow_fail(sd,0);
							return ATK_NONE;
						}
						break;
					case W_REVOLVER:
					case W_RIFLE:
					case W_GATLING:
					case W_SHOTGUN:
						if (sd->inventory_data[index]->look != A_BULLET) {
							clif_skill_fail(sd,0,USESKILL_FAIL_NEED_MORE_BULLET,0);
							return ATK_NONE;
						}
						break;
					case W_GRENADE:
						if (sd->inventory_data[index]->look != A_GRENADE) {
							clif_skill_fail(sd,0,USESKILL_FAIL_NEED_MORE_BULLET,0);
							return ATK_NONE;
						}
						break;
				}
			}
````

Example by using Gunslinger:

(Ammo equipped first)
* Equipped Bullet (type:bullet) attempts to equip Garrison (type:Revolver) => Succeed.
* Equipped Bullet (type:bullet) attempts to equip Inferno (type:Grenade Launcher) => Failed.
* Equipped Flare Sphere (type:grenade) attempts to equip Inferno (type:Grenade Launcher) => Succeed.
* Equipped Flare Sphere (type:grenade) attempts to equip Garrison (type:Revolver) => Failed.

(Weapon equipped first)
* Equipped Garrison (type:Revolver) attempts to equip Bullet (type:bullet) => Succeed.
* Equipped Garrison (type:Revolver) attempts to equip Flare Sphere (type:grenade) => Failed.
* Equipped Inferno (type:Grenade Launcher) attempts to equip Bullet (type:bullet) => Failed.
* Equipped Inferno (type:Grenade Launcher) attempts to equip Flare Sphere (type:grenade) => Succeed.

By meaning "Ammo equipped first", not I equip the ammo first then gun, but gun -> ammo -> unequip gun. Because, it doesn't let me wear ammo first if no weapon equipped.

**Comment by Lemongrass3110** [comment]
I tested on euRO with my ranger and my ninja. But those do not really run into those issues, because the arrows/kunais have a job mask that does not allow another job to equip it anyway.

From our current code:
1. If you try to equip a ammunition clientside
2. clif.c:clif_parse_EquipItem is called serverside
3. This function calls pc.c:pc_equipitem

We do not seem to have any checks in there for ammunitions yet. So it might be a good safety measure. The only possible scenario to try this on AEGIS though, is the one case you mentioned for gunslinger, where you switch between weapon types that require different ammunitions. All others would be sanity checks for custom items that might have a wrong job mask applied to them.

**Comment by cydh** [comment]
This is only for Gunslinger, Hunter class is still can equip arrow while equipping knives.
Also tested on Aegis.

**Comment by aleos89** [comment]
I would assume this is core logical behavior across all official servers from kRO. I don't think any official server would change something like this.

**Comment by Lemongrass3110** [comment]
Added a mini comment, but the rest looks ready to merge for me!
Nice work @cydh
