### ISSUE TITLE
serious Mob AI exploit from bool unit_can_reach_bl

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#884]
```unit_can_reach_bl``` doesnt check for walk path length but it's checked later, so rude attack doesn't happen but monster will also not reach its target because this is checked later

what this means is you can set up ice walls (as example) in a particular pattern against MVPs and it will see that a path to players exists, but the length will be far too long and do nothing, sitting in chase (dependent on their ai)

sample showing with SRH and greyworld GRF for easy counting (the teal is ice walls):

![screendomrjtest006](https://cloud.githubusercontent.com/assets/8746741/12186002/815a5870-b564-11e5-9290-4e344cf4b654.jpg)

![screendomrjtest007](https://cloud.githubusercontent.com/assets/8746741/12186006/88d34b34-b564-11e5-9c54-efa70985d065.jpg)

As you can see, the GTB just sits there getting JTed and ignores me. And never does rudeattack teleport. Of course if you waited too long and the ice walls expired, he walks up and bops your dumbass like normal. 

As at least a temporary fix, add a struct walkpath_data for use in the path_search.

```diff
-    return path_search(NULL,bl->m,bl->x,bl->y,tbl->x-dx,tbl->y-dy,easy,CELL_CHKNOREACH);
    
+    if (!path_search(&wpd,bl->m,bl->x,bl->y,tbl->x-dx,tbl->y-dy,easy,CELL_CHKNOPASS)) //count path length
+        return false; //no path
+    if (wpd.path_len > 14) // or rather, the mob chase range ?
+        return false; //path too long  
+    return true;
```

**Comment by Playtester** [comment]
Hmm, true he would probably teleport on official servers.

The code is pretty much a mess regarding monster behavior at the moment even though I cleaned it up a lot already. If you fix one thing two others things break.

unit_can_reach_bl already has a range it checks for but it ignores any kind of walls. The problem is also that you generally want it to be 100% in sync with the actual walking process, that doesn't only include checking for a walkpath range of 14 (this limit also only applies on complex path search), but also all 50+ other reasons why movement could fail...

Also somewhat related - what I think we don't have yet either is that ranged attackers would actually start attacking, even though they can't reach you by foot.

**Comment by mrjnumber1** [comment]
well either way, any server owner using rathena wants to use my temp fix so the monsters will be marked as rude attacked. otherwise tons of mvps become easy mode.

**Comment by mrjnumber1** [comment]
One more thing, I believe this doesn't happen with undeffed OFFICIAL_WALKPATH, but i can't confirm it.

**Comment by Lemongrass3110** [comment]
Thanks again to @mrjnumber1 

Here's a script to confirm this issue:
```
-	script	RudeAttack	-1,{
	end;

OnInit:
	.@map$ = "odin_tem03";

	setcell .@map$,339,270,339,280,CELL_ICEWALL,1;
	setcell .@map$,333,280,339,280,CELL_ICEWALL,1;

	setcell .@map$,332,279,332,279,CELL_ICEWALL,1;
	setcell .@map$,331,278,331,278,CELL_ICEWALL,1;
	setcell .@map$,330,277,330,277,CELL_ICEWALL,1;
	setcell .@map$,329,276,329,276,CELL_ICEWALL,1;

	setcell .@map$,339,270,339,280,CELL_WALKABLE,0;
	setcell .@map$,333,280,339,280,CELL_WALKABLE,0;

	setcell .@map$,332,279,332,279,CELL_WALKABLE,0;
	setcell .@map$,331,278,331,278,CELL_WALKABLE,0;
	setcell .@map$,330,277,330,277,CELL_WALKABLE,0;
	setcell .@map$,329,276,329,276,CELL_WALKABLE,0;

	monster .@map$,340,274,"GTB",1086,1;

	// Teleport yourself to @warp odin_tem03 337 272 and start jupitel on the GTB
}
```
