### ISSUE TITLE
map-server crash

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#911]
```
c_op get_com(unsigned char *script,int *pos)
{
	int i = 0, j = 0;

	if(script[*pos]>=0x80){
		return C_INT;
	}
	while(script[*pos]>=0x40){
		i=script[(*pos)++]<<j;
		j+=6;
	}
	return (c_op)(i+(script[(*pos)++]<<j));
}
```

Can we somehow make this function much safer then now?
I got several map-server crashes, and always i have the same gdb output.
Here it is gdb output:

```
(gdb)
#0  0x00000000005005ef in get_com (script=0x0, pos=0x7f892ec26b6c) at script.c:3455
No locals.
#1  0x00000000005027b8 in run_script_main (st=0x7f892ec26b5c) at script.c:4034
        c = <optimized out>
        cmdcount = 655309
        gotocount = 2047
        sd = <optimized out>
        stack = 0x7f892df93ee4
#2  0x00000000004c0f54 in npc_scriptcont (sd=0xf7cfaf0, id=<optimized out>, closing=<optimized out>) at npc.c:1319
        target = 0x7f892948f324
#3  0x000000000045517c in clif_parse (fd=41) at clif.c:18798
        cmd = <optimized out>
        packet_ver = <optimized out>
        packet_len = 7
        err = 0
        sd = 0xf7cfaf0
        pnum = 0
#4  0x00000000005a7e85 in do_sockets (next=<optimized out>) at socket.c:853
        rfd = {__fds_bits = {6203444922679360, 44117904883730, 0 <repeats 14 times>}}
        timeout = {tv_sec = 0, tv_usec = 19980}
        ret = <optimized out>
        i = 41
#5  0x0000000000404c7b in main (argc=1, argv=<optimized out>) at core.c:368
        next = <optimized out>
```

### Technical details
hash: bbe9601c0ddff82358d75242aa43de75e0c199e4
pre-re: 2012-04-10, packet_ver: 30
Packet Obf. :eneabled:

**Comment by Playtester** [comment]
Test length of array before accessing it, I guess?

**Comment by mrjnumber1** [comment]
and make sure i'ts not null.

**Comment by Lemongrass3110** [comment]
Could you please tell us what you are doing?
The problem is that the variable "cmd" is optimized out, so I do not know which command it is.

I would guess it has something to do with 01ba54c which @aleos89, @CairoLee, @admkakaroto and you tested. Might be related to progressbar, since that was the only usecase I did not see you test/mention for that commit.

**Comment by anacondaqq** [comment]
I have #SECURITY_TIMEOUT enabled.
I have Armor Enchanter with progress bar.
I did't tell how to reproduce, because i do not know. some guys do that shit just to get fresh spawn of MVPs. I'm not sure how, and don't know when, always when i wake up, i got a email report from gdb about "hello bro, your server got crashed, here is details about this issue, but i dunno why."

That's why i wrote, maybe is it possible somehow to optimzie this function, or add extra checks ? 
I think it's imposible to get information from abusers who they drop the map-server.

**Comment by anacondaqq** [comment]
again crash. again same gdb output as at post above.

Symptoms:
1.) Lags
2.) Then disconect
3.) Then reject from server.

**Comment by Lemongrass3110** [comment]
Could you please change your variable declarations in clif.c:clif_parse as follows:

```
static int clif_parse(int fd)
{
	volatile int cmd;
	int packet_ver, packet_len, err;
```

According to some articles I found that should stop it from being optimized out and we can learn which packet was sent by your users.
This will not fix the crash itself, but we might get a better knowledge of what's going wrong, since the most important things were optimized out by your gdb.

**Comment by Playtester** [comment]
Hmmm, so I think the problem is that there is no script_buf when it tries to run the script.

In npc.c (npc_scriptcont) you have:
```c
	/**
	 * WPE can get to this point with a progressbar; we deny it.
	 **/
	if( sd->progressbar.npc_id && DIFF_TICK(sd->progressbar.timeout,gettick()) > 0 )
		return 1;

	if (!sd->st)
		return 1;

	if( closing && sd->st && sd->st->state == CLOSE )
		sd->st->state = END;

	run_script_main(sd->st);

	return 0;
```
It takes the script from the map session data from the player. It checks if the script state exists, but it doesn't check if the script has a buffer and since it's "continue script" it doesn't create one either.

While it's easy to fix the crash by adding more checks, the question is however, how it can have the state "RUN" when it doesn't even have a script buffer.
It might open potential exploit if we just close the NPC script instead of crashing the server...

You could put something like...
```c
	if (!sd->st)
		return 1;

	//Check for empty script buffer
	if(!sd->st->script || !sd->st->script->script_buffer) {
		ShowDebug("Script crash bug caused by account %d\n", sd->bl.id);
		return 1;
	}

	if( closing && sd->st && sd->st->state == CLOSE )
		sd->st->state = END;
```
At least then you know who is causing it.

**Comment by anacondaqq** [comment]
i have at my server very oldschool cheaters, who love server restarts because of new mvp respawn with loot which they can sell. This happened usually when this guys online, maybe i'm wrong and it's paranoia. Anyway, thank you very very much, i will apply this changes, and will report about issue later.

**Comment by Playtester** [comment]
You could make MVPs not respawn after restart by making minor adjustments in npc_parse_mob2.

**Comment by admkakaroto** [comment]
The problem is that many players have easy access to basic emulator, sometimes find fault and use them in favor own.

**Comment by Lemongrass3110** [comment]
@anacondaqq any new info regarding this?

Would be nice if you could join us on discord so we can discuss this easier without giving your players the possibility to further read what we found out:
https://discord.gg/0XP9qqhUV9GrD7WV

**Comment by Lemongrass3110** [comment]
No more info on this for a month - closing this.

**Comment by anacondaqq** [comment]
please, reopen this, this issue under testing, and i did't saw your comment above.
Okay, after applying changes from Playtester above, i have no crashes at all, but i did't yet checked map-server logs.

**Comment by Playtester** [comment]
We should leave this open anyway, because it really is bad structure and should be improved. Maybe me suggested code fix could be applied.

**Comment by anacondaqq** [comment]
After ~3 months of testing, no crashes at all. 
If i will have any data related to this bug, i will reopen this issue. 

>  //Check for empty script buffer
    if(!sd->st->script || !sd->st->script->script_buffer) {
        ShowDebug("Script crash bug caused by account %d\n", sd->bl.id);
        return 1;
    }
