### ISSUE TITLE
Mystical Amplification in renewal

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#913]
As @reigneil pointed out in https://github.com/rathena/rathena/issues/903 there is an issue with fixed casttimes in renewal.

On official servers there are two things that can reduce the cast time of Mystical Amplification: Staff of Destruction and Sacrament.

That Sacrament works with Mystical Amplification would indicate that its cast time is defined as "fixed", at the same time, the skill-specific reduction of Staff of Destruction should reduce the cast time.

```2000,Destruction_Rod,Staff of Destruction,5,20,,2500,130:280,,1,1,0x00000200,18,2,34,4,80,1,23,{ .@r = getrefine; bonus bMatkRate,.@r/2; bonus bInt,3; bonus bAgi,10; bonus bUseSPrate,(.@r*2); bonus3 bAutoSpellWhenHit,"WZ_JUPITEL",5,(.@r*20); bonus2 bVariableCastrate,"HW_MAGICPOWER",-50; },{},{}```

But it's defined as bVariableCastrate so it effectively does nothing right now.

We either need to update the database to make the Staff of Destruction affect fixed cast time instead or do it the same way I did it in renewal and make the casttime variable but list it in castnodex as completely unreducable, then code an exception for skill-specific bonuses as well as Sacrament.

**Comment by aleos89** [comment]
The skill should be variable, not fixed. It's currently implemented wrong for the cast type in renewal.

So as you said, it would be like pre-renewal where it has specific checks to lower the cast time.

**Comment by Playtester** [comment]
But that means you need to make Sacrament reduce also variable cast time but only if castnodex says it's fixed?

**Comment by aleos89** [comment]
There are other issues as well with this skill for damage state. We will need to test further, but some skills should be granted increased damage for all hits, while some skills aren't affected by this at all.

Release - Should not have damage increased. Probably has to do with how Aegis has Release coded since it's a non-damaging skill but rA creates a new call for stored skills as if they were casted on their own, thus causing their damage to be increased.

Tetra Vortex - All hits from Tetra Vortex should have increased damage, not just the first.
