### ISSUE TITLE
autotrade

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#923]
i will temporary close this issue.
when i will get a lot of good information, i will reopen this.

**Comment by Playtester** [comment]
This only happens sometimes? How do you stop the server? Can I reproduce it by logging on, making autovend, stopping server and then starting it again?

p and data are pointers to a memory on your computer. "0x129b8274" is not invalid data it's just the data address on your harddisc that it accesses. At first they just point to nothing, but on CREATE there should actually be memory reserved for them and the location is written into data (and later into p at p = data).

What seems to be completely off is index, value and amount.

```c
            // Find item position in cart
            ARR_FIND(0, MAX_CART, entry->index, sd->status.cart[entry->index].id == entry->cartinventory_id);

            if (entry->index == MAX_CART) {
                count--;
                continue;
            }

            *index = entry->index + 2;
            *amount = itemdb_isstackable(sd->status.cart[entry->index].nameid) ? entry->amount : 1;
            *value = entry->price;

            p += 8;
```
Here is where it actually sets the values. I assume it either already fails setting them here properly or later it accesses memory that was reserved but not filled (because it reserved at->count*8 memory but might not fully place stuff into it if entry->index == MAX_CART?).

Maybe initializing the values with 0 could already help?

```c
            uint16 *index = (uint16*)(p + 0);
            uint16 *amount = (uint16*)(p + 2);
            uint32 *value = (uint32*)(p + 4);

            *index = 0;
            *amount = 0;
            *value = 0;
```

Just guessing though.
