### ISSUE TITLE
RK_ENCHANTBLADE

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#975]
[old Bug Tracker ](https://rathena.org/board/tracker/issue-5346-rk-enchantblade/)
now rA formula
`(100+20*skill_lv)*(status_get_lv(src)/150)+sstatus->int_`

no calculate matk part and reduced by target Mdef.

version : https://github.com/rathena/rathena/commit/de08a3677e43442b8b03be591731bf19252b8dc1
mode : renewal

**Comment by Playtester** [comment]
Reopening this as after the fix the damage increase is multiplied by 4 because it uses "RE_ALLATK_ADD" which increases all 4 types of attack.

Also the behavior is still not correct.

The skill works like this:

1. At STATUS START, a value x is calculated which is: `(100+20*skill_lv)*(status_get_lv(src)/150)+sstatus->int_`

2. This value x does not change even if INT changes in the meantime, but it's overwritten on recast.

3. Each attack the value x is added to the damage. This is fixed mastery damage addition that cannot be reduced.

4. Additional to that damage addition 100% magic attack damage is added. This uses the normal formulas for damage decrease and can NOT be reduced below 0. Also if you raise INT the MATK damage part is directly affected without having to recast the skill.

Reopening.

**Comment by Playtester** [comment]
Actually I did some miscalculation because I forgot about some database adjustments I did. Will try to gather exact data.

**Comment by Playtester** [comment]
1. The damage bonus is: [((SkillLv x 20) + 100) x srcBaseLevel / 150] + srcINT + srcMATK - tarMDEF - tarMDEF2

2. The damage bonus from base level and INT is calculated when the status change starts

3. The damage bonus from MATK and the reduction from MDEF/MDEF2 is calculated per hit
